// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
extern __kernel void CopyBuffer0(__global float *src, __global float *dst);
extern __kernel void CopyBuffer1(__global float *src, __global float *dst);
extern __kernel void CopyBuffer2(__global float *src, __global float *dst);
extern __kernel void CopyBuffer3(__global float *src, __global float *dst);
extern __kernel void CopyBuffer4(__global float *src, __global float *dst);
extern __kernel void CopyBuffer5(__global float *src, __global float *dst);
extern __kernel void CopyBuffer6(__global float *src, __global float *dst);
extern __kernel void CopyBuffer7(__global float *src, __global float *dst);
extern __kernel void CopyBuffer8(__global float *src, __global float *dst);
extern __kernel void CopyBuffer9(__global float *src, __global float *dst);
extern __kernel void CopyBuffer10(__global float *src, __global float *dst);
extern __kernel void CopyBuffer11(__global float *src, __global float *dst);
extern __kernel void CopyBuffer12(__global float *src, __global float *dst);
extern __kernel void CopyBuffer13(__global float *src, __global float *dst);
extern __kernel void CopyBuffer14(__global float *src, __global float *dst);
extern __kernel void CopyBuffer15(__global float *src, __global float *dst);
extern __kernel void CopyBuffer16(__global float *src, __global float *dst);
extern __kernel void CopyBuffer17(__global float *src, __global float *dst);
extern __kernel void CopyBuffer18(__global float *src, __global float *dst);
extern __kernel void CopyBuffer19(__global float *src, __global float *dst);
extern __kernel void CopyBuffer20(__global float *src, __global float *dst);
extern __kernel void CopyBuffer21(__global float *src, __global float *dst);
extern __kernel void CopyBuffer22(__global float *src, __global float *dst);
extern __kernel void CopyBuffer23(__global float *src, __global float *dst);
extern __kernel void CopyBuffer24(__global float *src, __global float *dst);
extern __kernel void CopyBuffer25(__global float *src, __global float *dst);
extern __kernel void CopyBuffer26(__global float *src, __global float *dst);
extern __kernel void CopyBuffer27(__global float *src, __global float *dst);
extern __kernel void CopyBuffer28(__global float *src, __global float *dst);
extern __kernel void CopyBuffer29(__global float *src, __global float *dst);
extern __kernel void CopyBuffer30(__global float *src, __global float *dst);
extern __kernel void CopyBuffer31(__global float *src, __global float *dst);
extern __kernel void CopyBuffer32(__global float *src, __global float *dst);
extern __kernel void CopyBuffer33(__global float *src, __global float *dst);
extern __kernel void CopyBuffer34(__global float *src, __global float *dst);
extern __kernel void CopyBuffer35(__global float *src, __global float *dst);
extern __kernel void CopyBuffer36(__global float *src, __global float *dst);
extern __kernel void CopyBuffer37(__global float *src, __global float *dst);
extern __kernel void CopyBuffer38(__global float *src, __global float *dst);
extern __kernel void CopyBuffer39(__global float *src, __global float *dst);
extern __kernel void CopyBuffer40(__global float *src, __global float *dst);
extern __kernel void CopyBuffer41(__global float *src, __global float *dst);
extern __kernel void CopyBuffer42(__global float *src, __global float *dst);
extern __kernel void CopyBuffer43(__global float *src, __global float *dst);
extern __kernel void CopyBuffer44(__global float *src, __global float *dst);
extern __kernel void CopyBuffer45(__global float *src, __global float *dst);
extern __kernel void CopyBuffer46(__global float *src, __global float *dst);
extern __kernel void CopyBuffer47(__global float *src, __global float *dst);
extern __kernel void CopyBuffer48(__global float *src, __global float *dst);
extern __kernel void CopyBuffer49(__global float *src, __global float *dst);
extern __kernel void CopyBuffer50(__global float *src, __global float *dst);
extern __kernel void CopyBuffer51(__global float *src, __global float *dst);
extern __kernel void CopyBuffer52(__global float *src, __global float *dst);
extern __kernel void CopyBuffer53(__global float *src, __global float *dst);
extern __kernel void CopyBuffer54(__global float *src, __global float *dst);
extern __kernel void CopyBuffer55(__global float *src, __global float *dst);
extern __kernel void CopyBuffer56(__global float *src, __global float *dst);
extern __kernel void CopyBuffer57(__global float *src, __global float *dst);
extern __kernel void CopyBuffer58(__global float *src, __global float *dst);
extern __kernel void CopyBuffer59(__global float *src, __global float *dst);
extern __kernel void CopyBuffer60(__global float *src, __global float *dst);
extern __kernel void CopyBuffer61(__global float *src, __global float *dst);
extern __kernel void CopyBuffer62(__global float *src, __global float *dst);
extern __kernel void CopyBuffer63(__global float *src, __global float *dst);
__kernel void CompositeKernel(__global float *src, __global float *dst) {
  CopyBuffer0(src, dst);
  CopyBuffer1(src, dst);
  CopyBuffer2(src, dst);
  CopyBuffer3(src, dst);
  CopyBuffer4(src, dst);
  CopyBuffer5(src, dst);
  CopyBuffer6(src, dst);
  CopyBuffer7(src, dst);
  CopyBuffer8(src, dst);
  CopyBuffer9(src, dst);
  CopyBuffer10(src, dst);
  CopyBuffer11(src, dst);
  CopyBuffer12(src, dst);
  CopyBuffer13(src, dst);
  CopyBuffer14(src, dst);
  CopyBuffer15(src, dst);
  CopyBuffer16(src, dst);
  CopyBuffer17(src, dst);
  CopyBuffer18(src, dst);
  CopyBuffer19(src, dst);
  CopyBuffer20(src, dst);
  CopyBuffer21(src, dst);
  CopyBuffer22(src, dst);
  CopyBuffer23(src, dst);
  CopyBuffer24(src, dst);
  CopyBuffer25(src, dst);
  CopyBuffer26(src, dst);
  CopyBuffer27(src, dst);
  CopyBuffer28(src, dst);
  CopyBuffer29(src, dst);
  CopyBuffer30(src, dst);
  CopyBuffer31(src, dst);
  CopyBuffer32(src, dst);
  CopyBuffer33(src, dst);
  CopyBuffer34(src, dst);
  CopyBuffer35(src, dst);
  CopyBuffer36(src, dst);
  CopyBuffer37(src, dst);
  CopyBuffer38(src, dst);
  CopyBuffer39(src, dst);
  CopyBuffer40(src, dst);
  CopyBuffer41(src, dst);
  CopyBuffer42(src, dst);
  CopyBuffer43(src, dst);
  CopyBuffer44(src, dst);
  CopyBuffer45(src, dst);
  CopyBuffer46(src, dst);
  CopyBuffer47(src, dst);
  CopyBuffer48(src, dst);
  CopyBuffer49(src, dst);
  CopyBuffer50(src, dst);
  CopyBuffer51(src, dst);
  CopyBuffer52(src, dst);
  CopyBuffer53(src, dst);
  CopyBuffer54(src, dst);
  CopyBuffer55(src, dst);
  CopyBuffer56(src, dst);
  CopyBuffer57(src, dst);
  CopyBuffer58(src, dst);
  CopyBuffer59(src, dst);
  CopyBuffer60(src, dst);
  CopyBuffer61(src, dst);
  CopyBuffer62(src, dst);
  CopyBuffer63(src, dst);
}
