// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
extern __kernel void CopyBuffer0(__global float *src, __global float *dst);
extern __kernel void CopyBuffer1(__global float *src, __global float *dst);
extern __kernel void CopyBuffer2(__global float *src, __global float *dst);
extern __kernel void CopyBuffer3(__global float *src, __global float *dst);
extern __kernel void CopyBuffer4(__global float *src, __global float *dst);
extern __kernel void CopyBuffer5(__global float *src, __global float *dst);
extern __kernel void CopyBuffer6(__global float *src, __global float *dst);
extern __kernel void CopyBuffer7(__global float *src, __global float *dst);
extern __kernel void CopyBuffer8(__global float *src, __global float *dst);
extern __kernel void CopyBuffer9(__global float *src, __global float *dst);
extern __kernel void CopyBuffer10(__global float *src, __global float *dst);
extern __kernel void CopyBuffer11(__global float *src, __global float *dst);
extern __kernel void CopyBuffer12(__global float *src, __global float *dst);
extern __kernel void CopyBuffer13(__global float *src, __global float *dst);
extern __kernel void CopyBuffer14(__global float *src, __global float *dst);
extern __kernel void CopyBuffer15(__global float *src, __global float *dst);
extern __kernel void CopyBuffer16(__global float *src, __global float *dst);
extern __kernel void CopyBuffer17(__global float *src, __global float *dst);
extern __kernel void CopyBuffer18(__global float *src, __global float *dst);
extern __kernel void CopyBuffer19(__global float *src, __global float *dst);
extern __kernel void CopyBuffer20(__global float *src, __global float *dst);
extern __kernel void CopyBuffer21(__global float *src, __global float *dst);
extern __kernel void CopyBuffer22(__global float *src, __global float *dst);
extern __kernel void CopyBuffer23(__global float *src, __global float *dst);
extern __kernel void CopyBuffer24(__global float *src, __global float *dst);
extern __kernel void CopyBuffer25(__global float *src, __global float *dst);
extern __kernel void CopyBuffer26(__global float *src, __global float *dst);
extern __kernel void CopyBuffer27(__global float *src, __global float *dst);
extern __kernel void CopyBuffer28(__global float *src, __global float *dst);
extern __kernel void CopyBuffer29(__global float *src, __global float *dst);
extern __kernel void CopyBuffer30(__global float *src, __global float *dst);
extern __kernel void CopyBuffer31(__global float *src, __global float *dst);
extern __kernel void CopyBuffer32(__global float *src, __global float *dst);
extern __kernel void CopyBuffer33(__global float *src, __global float *dst);
extern __kernel void CopyBuffer34(__global float *src, __global float *dst);
extern __kernel void CopyBuffer35(__global float *src, __global float *dst);
extern __kernel void CopyBuffer36(__global float *src, __global float *dst);
extern __kernel void CopyBuffer37(__global float *src, __global float *dst);
extern __kernel void CopyBuffer38(__global float *src, __global float *dst);
extern __kernel void CopyBuffer39(__global float *src, __global float *dst);
extern __kernel void CopyBuffer40(__global float *src, __global float *dst);
extern __kernel void CopyBuffer41(__global float *src, __global float *dst);
extern __kernel void CopyBuffer42(__global float *src, __global float *dst);
extern __kernel void CopyBuffer43(__global float *src, __global float *dst);
extern __kernel void CopyBuffer44(__global float *src, __global float *dst);
extern __kernel void CopyBuffer45(__global float *src, __global float *dst);
extern __kernel void CopyBuffer46(__global float *src, __global float *dst);
extern __kernel void CopyBuffer47(__global float *src, __global float *dst);
extern __kernel void CopyBuffer48(__global float *src, __global float *dst);
extern __kernel void CopyBuffer49(__global float *src, __global float *dst);
extern __kernel void CopyBuffer50(__global float *src, __global float *dst);
extern __kernel void CopyBuffer51(__global float *src, __global float *dst);
extern __kernel void CopyBuffer52(__global float *src, __global float *dst);
extern __kernel void CopyBuffer53(__global float *src, __global float *dst);
extern __kernel void CopyBuffer54(__global float *src, __global float *dst);
extern __kernel void CopyBuffer55(__global float *src, __global float *dst);
extern __kernel void CopyBuffer56(__global float *src, __global float *dst);
extern __kernel void CopyBuffer57(__global float *src, __global float *dst);
extern __kernel void CopyBuffer58(__global float *src, __global float *dst);
extern __kernel void CopyBuffer59(__global float *src, __global float *dst);
extern __kernel void CopyBuffer60(__global float *src, __global float *dst);
extern __kernel void CopyBuffer61(__global float *src, __global float *dst);
extern __kernel void CopyBuffer62(__global float *src, __global float *dst);
extern __kernel void CopyBuffer63(__global float *src, __global float *dst);
extern __kernel void CopyBuffer64(__global float *src, __global float *dst);
extern __kernel void CopyBuffer65(__global float *src, __global float *dst);
extern __kernel void CopyBuffer66(__global float *src, __global float *dst);
extern __kernel void CopyBuffer67(__global float *src, __global float *dst);
extern __kernel void CopyBuffer68(__global float *src, __global float *dst);
extern __kernel void CopyBuffer69(__global float *src, __global float *dst);
extern __kernel void CopyBuffer70(__global float *src, __global float *dst);
extern __kernel void CopyBuffer71(__global float *src, __global float *dst);
extern __kernel void CopyBuffer72(__global float *src, __global float *dst);
extern __kernel void CopyBuffer73(__global float *src, __global float *dst);
extern __kernel void CopyBuffer74(__global float *src, __global float *dst);
extern __kernel void CopyBuffer75(__global float *src, __global float *dst);
extern __kernel void CopyBuffer76(__global float *src, __global float *dst);
extern __kernel void CopyBuffer77(__global float *src, __global float *dst);
extern __kernel void CopyBuffer78(__global float *src, __global float *dst);
extern __kernel void CopyBuffer79(__global float *src, __global float *dst);
extern __kernel void CopyBuffer80(__global float *src, __global float *dst);
extern __kernel void CopyBuffer81(__global float *src, __global float *dst);
extern __kernel void CopyBuffer82(__global float *src, __global float *dst);
extern __kernel void CopyBuffer83(__global float *src, __global float *dst);
extern __kernel void CopyBuffer84(__global float *src, __global float *dst);
extern __kernel void CopyBuffer85(__global float *src, __global float *dst);
extern __kernel void CopyBuffer86(__global float *src, __global float *dst);
extern __kernel void CopyBuffer87(__global float *src, __global float *dst);
extern __kernel void CopyBuffer88(__global float *src, __global float *dst);
extern __kernel void CopyBuffer89(__global float *src, __global float *dst);
extern __kernel void CopyBuffer90(__global float *src, __global float *dst);
extern __kernel void CopyBuffer91(__global float *src, __global float *dst);
extern __kernel void CopyBuffer92(__global float *src, __global float *dst);
extern __kernel void CopyBuffer93(__global float *src, __global float *dst);
extern __kernel void CopyBuffer94(__global float *src, __global float *dst);
extern __kernel void CopyBuffer95(__global float *src, __global float *dst);
extern __kernel void CopyBuffer96(__global float *src, __global float *dst);
extern __kernel void CopyBuffer97(__global float *src, __global float *dst);
extern __kernel void CopyBuffer98(__global float *src, __global float *dst);
extern __kernel void CopyBuffer99(__global float *src, __global float *dst);
extern __kernel void CopyBuffer100(__global float *src, __global float *dst);
extern __kernel void CopyBuffer101(__global float *src, __global float *dst);
extern __kernel void CopyBuffer102(__global float *src, __global float *dst);
extern __kernel void CopyBuffer103(__global float *src, __global float *dst);
extern __kernel void CopyBuffer104(__global float *src, __global float *dst);
extern __kernel void CopyBuffer105(__global float *src, __global float *dst);
extern __kernel void CopyBuffer106(__global float *src, __global float *dst);
extern __kernel void CopyBuffer107(__global float *src, __global float *dst);
extern __kernel void CopyBuffer108(__global float *src, __global float *dst);
extern __kernel void CopyBuffer109(__global float *src, __global float *dst);
extern __kernel void CopyBuffer110(__global float *src, __global float *dst);
extern __kernel void CopyBuffer111(__global float *src, __global float *dst);
extern __kernel void CopyBuffer112(__global float *src, __global float *dst);
extern __kernel void CopyBuffer113(__global float *src, __global float *dst);
extern __kernel void CopyBuffer114(__global float *src, __global float *dst);
extern __kernel void CopyBuffer115(__global float *src, __global float *dst);
extern __kernel void CopyBuffer116(__global float *src, __global float *dst);
extern __kernel void CopyBuffer117(__global float *src, __global float *dst);
extern __kernel void CopyBuffer118(__global float *src, __global float *dst);
extern __kernel void CopyBuffer119(__global float *src, __global float *dst);
extern __kernel void CopyBuffer120(__global float *src, __global float *dst);
extern __kernel void CopyBuffer121(__global float *src, __global float *dst);
extern __kernel void CopyBuffer122(__global float *src, __global float *dst);
extern __kernel void CopyBuffer123(__global float *src, __global float *dst);
extern __kernel void CopyBuffer124(__global float *src, __global float *dst);
extern __kernel void CopyBuffer125(__global float *src, __global float *dst);
extern __kernel void CopyBuffer126(__global float *src, __global float *dst);
extern __kernel void CopyBuffer127(__global float *src, __global float *dst);
__kernel void CompositeKernel(__global float *src, __global float *dst) {
  CopyBuffer0(src, dst);
  CopyBuffer1(src, dst);
  CopyBuffer2(src, dst);
  CopyBuffer3(src, dst);
  CopyBuffer4(src, dst);
  CopyBuffer5(src, dst);
  CopyBuffer6(src, dst);
  CopyBuffer7(src, dst);
  CopyBuffer8(src, dst);
  CopyBuffer9(src, dst);
  CopyBuffer10(src, dst);
  CopyBuffer11(src, dst);
  CopyBuffer12(src, dst);
  CopyBuffer13(src, dst);
  CopyBuffer14(src, dst);
  CopyBuffer15(src, dst);
  CopyBuffer16(src, dst);
  CopyBuffer17(src, dst);
  CopyBuffer18(src, dst);
  CopyBuffer19(src, dst);
  CopyBuffer20(src, dst);
  CopyBuffer21(src, dst);
  CopyBuffer22(src, dst);
  CopyBuffer23(src, dst);
  CopyBuffer24(src, dst);
  CopyBuffer25(src, dst);
  CopyBuffer26(src, dst);
  CopyBuffer27(src, dst);
  CopyBuffer28(src, dst);
  CopyBuffer29(src, dst);
  CopyBuffer30(src, dst);
  CopyBuffer31(src, dst);
  CopyBuffer32(src, dst);
  CopyBuffer33(src, dst);
  CopyBuffer34(src, dst);
  CopyBuffer35(src, dst);
  CopyBuffer36(src, dst);
  CopyBuffer37(src, dst);
  CopyBuffer38(src, dst);
  CopyBuffer39(src, dst);
  CopyBuffer40(src, dst);
  CopyBuffer41(src, dst);
  CopyBuffer42(src, dst);
  CopyBuffer43(src, dst);
  CopyBuffer44(src, dst);
  CopyBuffer45(src, dst);
  CopyBuffer46(src, dst);
  CopyBuffer47(src, dst);
  CopyBuffer48(src, dst);
  CopyBuffer49(src, dst);
  CopyBuffer50(src, dst);
  CopyBuffer51(src, dst);
  CopyBuffer52(src, dst);
  CopyBuffer53(src, dst);
  CopyBuffer54(src, dst);
  CopyBuffer55(src, dst);
  CopyBuffer56(src, dst);
  CopyBuffer57(src, dst);
  CopyBuffer58(src, dst);
  CopyBuffer59(src, dst);
  CopyBuffer60(src, dst);
  CopyBuffer61(src, dst);
  CopyBuffer62(src, dst);
  CopyBuffer63(src, dst);
  CopyBuffer64(src, dst);
  CopyBuffer65(src, dst);
  CopyBuffer66(src, dst);
  CopyBuffer67(src, dst);
  CopyBuffer68(src, dst);
  CopyBuffer69(src, dst);
  CopyBuffer70(src, dst);
  CopyBuffer71(src, dst);
  CopyBuffer72(src, dst);
  CopyBuffer73(src, dst);
  CopyBuffer74(src, dst);
  CopyBuffer75(src, dst);
  CopyBuffer76(src, dst);
  CopyBuffer77(src, dst);
  CopyBuffer78(src, dst);
  CopyBuffer79(src, dst);
  CopyBuffer80(src, dst);
  CopyBuffer81(src, dst);
  CopyBuffer82(src, dst);
  CopyBuffer83(src, dst);
  CopyBuffer84(src, dst);
  CopyBuffer85(src, dst);
  CopyBuffer86(src, dst);
  CopyBuffer87(src, dst);
  CopyBuffer88(src, dst);
  CopyBuffer89(src, dst);
  CopyBuffer90(src, dst);
  CopyBuffer91(src, dst);
  CopyBuffer92(src, dst);
  CopyBuffer93(src, dst);
  CopyBuffer94(src, dst);
  CopyBuffer95(src, dst);
  CopyBuffer96(src, dst);
  CopyBuffer97(src, dst);
  CopyBuffer98(src, dst);
  CopyBuffer99(src, dst);
  CopyBuffer100(src, dst);
  CopyBuffer101(src, dst);
  CopyBuffer102(src, dst);
  CopyBuffer103(src, dst);
  CopyBuffer104(src, dst);
  CopyBuffer105(src, dst);
  CopyBuffer106(src, dst);
  CopyBuffer107(src, dst);
  CopyBuffer108(src, dst);
  CopyBuffer109(src, dst);
  CopyBuffer110(src, dst);
  CopyBuffer111(src, dst);
  CopyBuffer112(src, dst);
  CopyBuffer113(src, dst);
  CopyBuffer114(src, dst);
  CopyBuffer115(src, dst);
  CopyBuffer116(src, dst);
  CopyBuffer117(src, dst);
  CopyBuffer118(src, dst);
  CopyBuffer119(src, dst);
  CopyBuffer120(src, dst);
  CopyBuffer121(src, dst);
  CopyBuffer122(src, dst);
  CopyBuffer123(src, dst);
  CopyBuffer124(src, dst);
  CopyBuffer125(src, dst);
  CopyBuffer126(src, dst);
  CopyBuffer127(src, dst);
}
