__kernel void imageBandwidth_read_single(__read_only image2d_t image, __write_only image2d_t output)
{
sampler_t sampler = CLK_NORMALIZED_COORDS_FALSE | CLK_ADDRESS_CLAMP | CLK_FILTER_LINEAR;
uint4 val = (uint4)(0,0,0,0);
int2 coord = (int2)(get_global_id(0),get_global_id(1));
int2 index = (int2)(0,0);
val += read_imageui(image, sampler, (int2)(0, 0));
val += read_imageui(image, sampler, (int2)(1, 0));
val += read_imageui(image, sampler, (int2)(2, 0));
val += read_imageui(image, sampler, (int2)(3, 0));
val += read_imageui(image, sampler, (int2)(4, 0));
val += read_imageui(image, sampler, (int2)(5, 0));
val += read_imageui(image, sampler, (int2)(6, 0));
val += read_imageui(image, sampler, (int2)(7, 0));
val += read_imageui(image, sampler, (int2)(8, 0));
val += read_imageui(image, sampler, (int2)(9, 0));
val += read_imageui(image, sampler, (int2)(10, 0));
val += read_imageui(image, sampler, (int2)(11, 0));
val += read_imageui(image, sampler, (int2)(12, 0));
val += read_imageui(image, sampler, (int2)(13, 0));
val += read_imageui(image, sampler, (int2)(14, 0));
val += read_imageui(image, sampler, (int2)(15, 0));
val += read_imageui(image, sampler, (int2)(16, 0));
val += read_imageui(image, sampler, (int2)(17, 0));
val += read_imageui(image, sampler, (int2)(18, 0));
val += read_imageui(image, sampler, (int2)(19, 0));
val += read_imageui(image, sampler, (int2)(20, 0));
val += read_imageui(image, sampler, (int2)(21, 0));
val += read_imageui(image, sampler, (int2)(22, 0));
val += read_imageui(image, sampler, (int2)(23, 0));
val += read_imageui(image, sampler, (int2)(24, 0));
val += read_imageui(image, sampler, (int2)(25, 0));
val += read_imageui(image, sampler, (int2)(26, 0));
val += read_imageui(image, sampler, (int2)(27, 0));
val += read_imageui(image, sampler, (int2)(28, 0));
val += read_imageui(image, sampler, (int2)(29, 0));
val += read_imageui(image, sampler, (int2)(30, 0));
val += read_imageui(image, sampler, (int2)(31, 0));
val += read_imageui(image, sampler, (int2)(32, 0));
val += read_imageui(image, sampler, (int2)(33, 0));
val += read_imageui(image, sampler, (int2)(34, 0));
val += read_imageui(image, sampler, (int2)(35, 0));
val += read_imageui(image, sampler, (int2)(36, 0));
val += read_imageui(image, sampler, (int2)(37, 0));
val += read_imageui(image, sampler, (int2)(38, 0));
val += read_imageui(image, sampler, (int2)(39, 0));
val += read_imageui(image, sampler, (int2)(40, 0));
val += read_imageui(image, sampler, (int2)(41, 0));
val += read_imageui(image, sampler, (int2)(42, 0));
val += read_imageui(image, sampler, (int2)(43, 0));
val += read_imageui(image, sampler, (int2)(44, 0));
val += read_imageui(image, sampler, (int2)(45, 0));
val += read_imageui(image, sampler, (int2)(46, 0));
val += read_imageui(image, sampler, (int2)(47, 0));
val += read_imageui(image, sampler, (int2)(48, 0));
val += read_imageui(image, sampler, (int2)(49, 0));
val += read_imageui(image, sampler, (int2)(50, 0));
val += read_imageui(image, sampler, (int2)(51, 0));
val += read_imageui(image, sampler, (int2)(52, 0));
val += read_imageui(image, sampler, (int2)(53, 0));
val += read_imageui(image, sampler, (int2)(54, 0));
val += read_imageui(image, sampler, (int2)(55, 0));
val += read_imageui(image, sampler, (int2)(56, 0));
val += read_imageui(image, sampler, (int2)(57, 0));
val += read_imageui(image, sampler, (int2)(58, 0));
val += read_imageui(image, sampler, (int2)(59, 0));
val += read_imageui(image, sampler, (int2)(60, 0));
val += read_imageui(image, sampler, (int2)(61, 0));
val += read_imageui(image, sampler, (int2)(62, 0));
val += read_imageui(image, sampler, (int2)(63, 0));
val += read_imageui(image, sampler, (int2)(64, 0));
val += read_imageui(image, sampler, (int2)(65, 0));
val += read_imageui(image, sampler, (int2)(66, 0));
val += read_imageui(image, sampler, (int2)(67, 0));
val += read_imageui(image, sampler, (int2)(68, 0));
val += read_imageui(image, sampler, (int2)(69, 0));
val += read_imageui(image, sampler, (int2)(70, 0));
val += read_imageui(image, sampler, (int2)(71, 0));
val += read_imageui(image, sampler, (int2)(72, 0));
val += read_imageui(image, sampler, (int2)(73, 0));
val += read_imageui(image, sampler, (int2)(74, 0));
val += read_imageui(image, sampler, (int2)(75, 0));
val += read_imageui(image, sampler, (int2)(76, 0));
val += read_imageui(image, sampler, (int2)(77, 0));
val += read_imageui(image, sampler, (int2)(78, 0));
val += read_imageui(image, sampler, (int2)(79, 0));
val += read_imageui(image, sampler, (int2)(80, 0));
val += read_imageui(image, sampler, (int2)(81, 0));
val += read_imageui(image, sampler, (int2)(82, 0));
val += read_imageui(image, sampler, (int2)(83, 0));
val += read_imageui(image, sampler, (int2)(84, 0));
val += read_imageui(image, sampler, (int2)(85, 0));
val += read_imageui(image, sampler, (int2)(86, 0));
val += read_imageui(image, sampler, (int2)(87, 0));
val += read_imageui(image, sampler, (int2)(88, 0));
val += read_imageui(image, sampler, (int2)(89, 0));
val += read_imageui(image, sampler, (int2)(90, 0));
val += read_imageui(image, sampler, (int2)(91, 0));
val += read_imageui(image, sampler, (int2)(92, 0));
val += read_imageui(image, sampler, (int2)(93, 0));
val += read_imageui(image, sampler, (int2)(94, 0));
val += read_imageui(image, sampler, (int2)(95, 0));
val += read_imageui(image, sampler, (int2)(96, 0));
val += read_imageui(image, sampler, (int2)(97, 0));
val += read_imageui(image, sampler, (int2)(98, 0));
val += read_imageui(image, sampler, (int2)(99, 0));
val += read_imageui(image, sampler, (int2)(100, 0));
val += read_imageui(image, sampler, (int2)(101, 0));
val += read_imageui(image, sampler, (int2)(102, 0));
val += read_imageui(image, sampler, (int2)(103, 0));
val += read_imageui(image, sampler, (int2)(104, 0));
val += read_imageui(image, sampler, (int2)(105, 0));
val += read_imageui(image, sampler, (int2)(106, 0));
val += read_imageui(image, sampler, (int2)(107, 0));
val += read_imageui(image, sampler, (int2)(108, 0));
val += read_imageui(image, sampler, (int2)(109, 0));
val += read_imageui(image, sampler, (int2)(110, 0));
val += read_imageui(image, sampler, (int2)(111, 0));
val += read_imageui(image, sampler, (int2)(112, 0));
val += read_imageui(image, sampler, (int2)(113, 0));
val += read_imageui(image, sampler, (int2)(114, 0));
val += read_imageui(image, sampler, (int2)(115, 0));
val += read_imageui(image, sampler, (int2)(116, 0));
val += read_imageui(image, sampler, (int2)(117, 0));
val += read_imageui(image, sampler, (int2)(118, 0));
val += read_imageui(image, sampler, (int2)(119, 0));
val += read_imageui(image, sampler, (int2)(120, 0));
val += read_imageui(image, sampler, (int2)(121, 0));
val += read_imageui(image, sampler, (int2)(122, 0));
val += read_imageui(image, sampler, (int2)(123, 0));
val += read_imageui(image, sampler, (int2)(124, 0));
val += read_imageui(image, sampler, (int2)(125, 0));
val += read_imageui(image, sampler, (int2)(126, 0));
val += read_imageui(image, sampler, (int2)(127, 0));
val += read_imageui(image, sampler, (int2)(128, 0));
val += read_imageui(image, sampler, (int2)(129, 0));
val += read_imageui(image, sampler, (int2)(130, 0));
val += read_imageui(image, sampler, (int2)(131, 0));
val += read_imageui(image, sampler, (int2)(132, 0));
val += read_imageui(image, sampler, (int2)(133, 0));
val += read_imageui(image, sampler, (int2)(134, 0));
val += read_imageui(image, sampler, (int2)(135, 0));
val += read_imageui(image, sampler, (int2)(136, 0));
val += read_imageui(image, sampler, (int2)(137, 0));
val += read_imageui(image, sampler, (int2)(138, 0));
val += read_imageui(image, sampler, (int2)(139, 0));
val += read_imageui(image, sampler, (int2)(140, 0));
val += read_imageui(image, sampler, (int2)(141, 0));
val += read_imageui(image, sampler, (int2)(142, 0));
val += read_imageui(image, sampler, (int2)(143, 0));
val += read_imageui(image, sampler, (int2)(144, 0));
val += read_imageui(image, sampler, (int2)(145, 0));
val += read_imageui(image, sampler, (int2)(146, 0));
val += read_imageui(image, sampler, (int2)(147, 0));
val += read_imageui(image, sampler, (int2)(148, 0));
val += read_imageui(image, sampler, (int2)(149, 0));
val += read_imageui(image, sampler, (int2)(150, 0));
val += read_imageui(image, sampler, (int2)(151, 0));
val += read_imageui(image, sampler, (int2)(152, 0));
val += read_imageui(image, sampler, (int2)(153, 0));
val += read_imageui(image, sampler, (int2)(154, 0));
val += read_imageui(image, sampler, (int2)(155, 0));
val += read_imageui(image, sampler, (int2)(156, 0));
val += read_imageui(image, sampler, (int2)(157, 0));
val += read_imageui(image, sampler, (int2)(158, 0));
val += read_imageui(image, sampler, (int2)(159, 0));
val += read_imageui(image, sampler, (int2)(160, 0));
val += read_imageui(image, sampler, (int2)(161, 0));
val += read_imageui(image, sampler, (int2)(162, 0));
val += read_imageui(image, sampler, (int2)(163, 0));
val += read_imageui(image, sampler, (int2)(164, 0));
val += read_imageui(image, sampler, (int2)(165, 0));
val += read_imageui(image, sampler, (int2)(166, 0));
val += read_imageui(image, sampler, (int2)(167, 0));
val += read_imageui(image, sampler, (int2)(168, 0));
val += read_imageui(image, sampler, (int2)(169, 0));
val += read_imageui(image, sampler, (int2)(170, 0));
val += read_imageui(image, sampler, (int2)(171, 0));
val += read_imageui(image, sampler, (int2)(172, 0));
val += read_imageui(image, sampler, (int2)(173, 0));
val += read_imageui(image, sampler, (int2)(174, 0));
val += read_imageui(image, sampler, (int2)(175, 0));
val += read_imageui(image, sampler, (int2)(176, 0));
val += read_imageui(image, sampler, (int2)(177, 0));
val += read_imageui(image, sampler, (int2)(178, 0));
val += read_imageui(image, sampler, (int2)(179, 0));
val += read_imageui(image, sampler, (int2)(180, 0));
val += read_imageui(image, sampler, (int2)(181, 0));
val += read_imageui(image, sampler, (int2)(182, 0));
val += read_imageui(image, sampler, (int2)(183, 0));
val += read_imageui(image, sampler, (int2)(184, 0));
val += read_imageui(image, sampler, (int2)(185, 0));
val += read_imageui(image, sampler, (int2)(186, 0));
val += read_imageui(image, sampler, (int2)(187, 0));
val += read_imageui(image, sampler, (int2)(188, 0));
val += read_imageui(image, sampler, (int2)(189, 0));
val += read_imageui(image, sampler, (int2)(190, 0));
val += read_imageui(image, sampler, (int2)(191, 0));
val += read_imageui(image, sampler, (int2)(192, 0));
val += read_imageui(image, sampler, (int2)(193, 0));
val += read_imageui(image, sampler, (int2)(194, 0));
val += read_imageui(image, sampler, (int2)(195, 0));
val += read_imageui(image, sampler, (int2)(196, 0));
val += read_imageui(image, sampler, (int2)(197, 0));
val += read_imageui(image, sampler, (int2)(198, 0));
val += read_imageui(image, sampler, (int2)(199, 0));
val += read_imageui(image, sampler, (int2)(200, 0));
val += read_imageui(image, sampler, (int2)(201, 0));
val += read_imageui(image, sampler, (int2)(202, 0));
val += read_imageui(image, sampler, (int2)(203, 0));
val += read_imageui(image, sampler, (int2)(204, 0));
val += read_imageui(image, sampler, (int2)(205, 0));
val += read_imageui(image, sampler, (int2)(206, 0));
val += read_imageui(image, sampler, (int2)(207, 0));
val += read_imageui(image, sampler, (int2)(208, 0));
val += read_imageui(image, sampler, (int2)(209, 0));
val += read_imageui(image, sampler, (int2)(210, 0));
val += read_imageui(image, sampler, (int2)(211, 0));
val += read_imageui(image, sampler, (int2)(212, 0));
val += read_imageui(image, sampler, (int2)(213, 0));
val += read_imageui(image, sampler, (int2)(214, 0));
val += read_imageui(image, sampler, (int2)(215, 0));
val += read_imageui(image, sampler, (int2)(216, 0));
val += read_imageui(image, sampler, (int2)(217, 0));
val += read_imageui(image, sampler, (int2)(218, 0));
val += read_imageui(image, sampler, (int2)(219, 0));
val += read_imageui(image, sampler, (int2)(220, 0));
val += read_imageui(image, sampler, (int2)(221, 0));
val += read_imageui(image, sampler, (int2)(222, 0));
val += read_imageui(image, sampler, (int2)(223, 0));
val += read_imageui(image, sampler, (int2)(224, 0));
val += read_imageui(image, sampler, (int2)(225, 0));
val += read_imageui(image, sampler, (int2)(226, 0));
val += read_imageui(image, sampler, (int2)(227, 0));
val += read_imageui(image, sampler, (int2)(228, 0));
val += read_imageui(image, sampler, (int2)(229, 0));
val += read_imageui(image, sampler, (int2)(230, 0));
val += read_imageui(image, sampler, (int2)(231, 0));
val += read_imageui(image, sampler, (int2)(232, 0));
val += read_imageui(image, sampler, (int2)(233, 0));
val += read_imageui(image, sampler, (int2)(234, 0));
val += read_imageui(image, sampler, (int2)(235, 0));
val += read_imageui(image, sampler, (int2)(236, 0));
val += read_imageui(image, sampler, (int2)(237, 0));
val += read_imageui(image, sampler, (int2)(238, 0));
val += read_imageui(image, sampler, (int2)(239, 0));
val += read_imageui(image, sampler, (int2)(240, 0));
val += read_imageui(image, sampler, (int2)(241, 0));
val += read_imageui(image, sampler, (int2)(242, 0));
val += read_imageui(image, sampler, (int2)(243, 0));
val += read_imageui(image, sampler, (int2)(244, 0));
val += read_imageui(image, sampler, (int2)(245, 0));
val += read_imageui(image, sampler, (int2)(246, 0));
val += read_imageui(image, sampler, (int2)(247, 0));
val += read_imageui(image, sampler, (int2)(248, 0));
val += read_imageui(image, sampler, (int2)(249, 0));
val += read_imageui(image, sampler, (int2)(250, 0));
val += read_imageui(image, sampler, (int2)(251, 0));
val += read_imageui(image, sampler, (int2)(252, 0));
val += read_imageui(image, sampler, (int2)(253, 0));
val += read_imageui(image, sampler, (int2)(254, 0));
val += read_imageui(image, sampler, (int2)(255, 0));
write_imageui(output, coord, val);
}


__kernel void imageBandwidth_read_linear(__read_only image2d_t image, __write_only image2d_t output)
{
sampler_t sampler = CLK_NORMALIZED_COORDS_FALSE | CLK_ADDRESS_CLAMP | CLK_FILTER_LINEAR;
uint4 val = (uint4)(0,0,0,0);
int2 coord = (int2)(get_global_id(0),get_global_id(1));
int2 index = (int2)(0,0);
val += read_imageui(image, sampler, (int2)(coord.x + 0, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 1, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 2, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 3, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 4, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 5, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 6, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 7, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 8, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 9, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 10, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 11, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 12, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 13, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 14, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 15, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 16, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 17, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 18, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 19, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 20, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 21, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 22, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 23, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 24, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 25, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 26, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 27, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 28, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 29, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 30, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 31, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 32, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 33, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 34, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 35, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 36, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 37, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 38, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 39, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 40, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 41, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 42, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 43, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 44, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 45, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 46, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 47, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 48, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 49, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 50, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 51, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 52, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 53, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 54, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 55, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 56, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 57, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 58, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 59, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 60, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 61, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 62, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 63, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 64, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 65, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 66, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 67, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 68, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 69, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 70, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 71, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 72, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 73, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 74, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 75, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 76, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 77, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 78, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 79, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 80, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 81, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 82, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 83, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 84, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 85, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 86, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 87, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 88, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 89, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 90, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 91, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 92, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 93, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 94, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 95, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 96, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 97, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 98, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 99, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 100, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 101, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 102, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 103, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 104, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 105, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 106, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 107, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 108, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 109, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 110, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 111, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 112, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 113, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 114, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 115, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 116, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 117, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 118, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 119, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 120, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 121, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 122, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 123, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 124, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 125, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 126, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 127, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 128, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 129, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 130, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 131, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 132, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 133, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 134, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 135, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 136, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 137, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 138, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 139, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 140, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 141, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 142, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 143, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 144, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 145, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 146, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 147, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 148, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 149, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 150, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 151, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 152, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 153, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 154, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 155, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 156, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 157, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 158, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 159, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 160, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 161, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 162, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 163, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 164, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 165, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 166, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 167, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 168, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 169, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 170, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 171, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 172, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 173, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 174, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 175, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 176, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 177, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 178, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 179, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 180, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 181, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 182, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 183, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 184, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 185, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 186, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 187, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 188, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 189, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 190, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 191, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 192, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 193, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 194, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 195, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 196, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 197, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 198, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 199, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 200, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 201, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 202, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 203, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 204, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 205, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 206, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 207, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 208, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 209, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 210, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 211, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 212, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 213, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 214, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 215, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 216, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 217, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 218, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 219, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 220, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 221, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 222, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 223, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 224, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 225, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 226, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 227, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 228, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 229, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 230, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 231, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 232, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 233, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 234, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 235, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 236, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 237, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 238, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 239, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 240, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 241, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 242, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 243, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 244, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 245, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 246, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 247, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 248, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 249, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 250, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 251, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 252, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 253, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 254, coord.y));
val += read_imageui(image, sampler, (int2)(coord.x + 255, coord.y));
write_imageui(output, coord, val);
}

__kernel void imageBandwidth_write_linear(__read_only image2d_t image, __write_only image2d_t output)
{
sampler_t sampler = CLK_NORMALIZED_COORDS_FALSE | CLK_ADDRESS_CLAMP | CLK_FILTER_LINEAR;
uint4 val = (uint4)(0,0,0,0);
int2 coord = (int2)(get_global_id(0),get_global_id(1));
write_imageui(output, (int2)(coord.x + 0, coord.y), val);
write_imageui(output, (int2)(coord.x + 1, coord.y), val);
write_imageui(output, (int2)(coord.x + 2, coord.y), val);
write_imageui(output, (int2)(coord.x + 3, coord.y), val);
write_imageui(output, (int2)(coord.x + 4, coord.y), val);
write_imageui(output, (int2)(coord.x + 5, coord.y), val);
write_imageui(output, (int2)(coord.x + 6, coord.y), val);
write_imageui(output, (int2)(coord.x + 7, coord.y), val);
write_imageui(output, (int2)(coord.x + 8, coord.y), val);
write_imageui(output, (int2)(coord.x + 9, coord.y), val);
write_imageui(output, (int2)(coord.x + 10, coord.y), val);
write_imageui(output, (int2)(coord.x + 11, coord.y), val);
write_imageui(output, (int2)(coord.x + 12, coord.y), val);
write_imageui(output, (int2)(coord.x + 13, coord.y), val);
write_imageui(output, (int2)(coord.x + 14, coord.y), val);
write_imageui(output, (int2)(coord.x + 15, coord.y), val);
write_imageui(output, (int2)(coord.x + 16, coord.y), val);
write_imageui(output, (int2)(coord.x + 17, coord.y), val);
write_imageui(output, (int2)(coord.x + 18, coord.y), val);
write_imageui(output, (int2)(coord.x + 19, coord.y), val);
write_imageui(output, (int2)(coord.x + 20, coord.y), val);
write_imageui(output, (int2)(coord.x + 21, coord.y), val);
write_imageui(output, (int2)(coord.x + 22, coord.y), val);
write_imageui(output, (int2)(coord.x + 23, coord.y), val);
write_imageui(output, (int2)(coord.x + 24, coord.y), val);
write_imageui(output, (int2)(coord.x + 25, coord.y), val);
write_imageui(output, (int2)(coord.x + 26, coord.y), val);
write_imageui(output, (int2)(coord.x + 27, coord.y), val);
write_imageui(output, (int2)(coord.x + 28, coord.y), val);
write_imageui(output, (int2)(coord.x + 29, coord.y), val);
write_imageui(output, (int2)(coord.x + 30, coord.y), val);
write_imageui(output, (int2)(coord.x + 31, coord.y), val);
write_imageui(output, (int2)(coord.x + 32, coord.y), val);
write_imageui(output, (int2)(coord.x + 33, coord.y), val);
write_imageui(output, (int2)(coord.x + 34, coord.y), val);
write_imageui(output, (int2)(coord.x + 35, coord.y), val);
write_imageui(output, (int2)(coord.x + 36, coord.y), val);
write_imageui(output, (int2)(coord.x + 37, coord.y), val);
write_imageui(output, (int2)(coord.x + 38, coord.y), val);
write_imageui(output, (int2)(coord.x + 39, coord.y), val);
write_imageui(output, (int2)(coord.x + 40, coord.y), val);
write_imageui(output, (int2)(coord.x + 41, coord.y), val);
write_imageui(output, (int2)(coord.x + 42, coord.y), val);
write_imageui(output, (int2)(coord.x + 43, coord.y), val);
write_imageui(output, (int2)(coord.x + 44, coord.y), val);
write_imageui(output, (int2)(coord.x + 45, coord.y), val);
write_imageui(output, (int2)(coord.x + 46, coord.y), val);
write_imageui(output, (int2)(coord.x + 47, coord.y), val);
write_imageui(output, (int2)(coord.x + 48, coord.y), val);
write_imageui(output, (int2)(coord.x + 49, coord.y), val);
write_imageui(output, (int2)(coord.x + 50, coord.y), val);
write_imageui(output, (int2)(coord.x + 51, coord.y), val);
write_imageui(output, (int2)(coord.x + 52, coord.y), val);
write_imageui(output, (int2)(coord.x + 53, coord.y), val);
write_imageui(output, (int2)(coord.x + 54, coord.y), val);
write_imageui(output, (int2)(coord.x + 55, coord.y), val);
write_imageui(output, (int2)(coord.x + 56, coord.y), val);
write_imageui(output, (int2)(coord.x + 57, coord.y), val);
write_imageui(output, (int2)(coord.x + 58, coord.y), val);
write_imageui(output, (int2)(coord.x + 59, coord.y), val);
write_imageui(output, (int2)(coord.x + 60, coord.y), val);
write_imageui(output, (int2)(coord.x + 61, coord.y), val);
write_imageui(output, (int2)(coord.x + 62, coord.y), val);
write_imageui(output, (int2)(coord.x + 63, coord.y), val);
write_imageui(output, (int2)(coord.x + 64, coord.y), val);
write_imageui(output, (int2)(coord.x + 65, coord.y), val);
write_imageui(output, (int2)(coord.x + 66, coord.y), val);
write_imageui(output, (int2)(coord.x + 67, coord.y), val);
write_imageui(output, (int2)(coord.x + 68, coord.y), val);
write_imageui(output, (int2)(coord.x + 69, coord.y), val);
write_imageui(output, (int2)(coord.x + 70, coord.y), val);
write_imageui(output, (int2)(coord.x + 71, coord.y), val);
write_imageui(output, (int2)(coord.x + 72, coord.y), val);
write_imageui(output, (int2)(coord.x + 73, coord.y), val);
write_imageui(output, (int2)(coord.x + 74, coord.y), val);
write_imageui(output, (int2)(coord.x + 75, coord.y), val);
write_imageui(output, (int2)(coord.x + 76, coord.y), val);
write_imageui(output, (int2)(coord.x + 77, coord.y), val);
write_imageui(output, (int2)(coord.x + 78, coord.y), val);
write_imageui(output, (int2)(coord.x + 79, coord.y), val);
write_imageui(output, (int2)(coord.x + 80, coord.y), val);
write_imageui(output, (int2)(coord.x + 81, coord.y), val);
write_imageui(output, (int2)(coord.x + 82, coord.y), val);
write_imageui(output, (int2)(coord.x + 83, coord.y), val);
write_imageui(output, (int2)(coord.x + 84, coord.y), val);
write_imageui(output, (int2)(coord.x + 85, coord.y), val);
write_imageui(output, (int2)(coord.x + 86, coord.y), val);
write_imageui(output, (int2)(coord.x + 87, coord.y), val);
write_imageui(output, (int2)(coord.x + 88, coord.y), val);
write_imageui(output, (int2)(coord.x + 89, coord.y), val);
write_imageui(output, (int2)(coord.x + 90, coord.y), val);
write_imageui(output, (int2)(coord.x + 91, coord.y), val);
write_imageui(output, (int2)(coord.x + 92, coord.y), val);
write_imageui(output, (int2)(coord.x + 93, coord.y), val);
write_imageui(output, (int2)(coord.x + 94, coord.y), val);
write_imageui(output, (int2)(coord.x + 95, coord.y), val);
write_imageui(output, (int2)(coord.x + 96, coord.y), val);
write_imageui(output, (int2)(coord.x + 97, coord.y), val);
write_imageui(output, (int2)(coord.x + 98, coord.y), val);
write_imageui(output, (int2)(coord.x + 99, coord.y), val);
write_imageui(output, (int2)(coord.x + 100, coord.y), val);
write_imageui(output, (int2)(coord.x + 101, coord.y), val);
write_imageui(output, (int2)(coord.x + 102, coord.y), val);
write_imageui(output, (int2)(coord.x + 103, coord.y), val);
write_imageui(output, (int2)(coord.x + 104, coord.y), val);
write_imageui(output, (int2)(coord.x + 105, coord.y), val);
write_imageui(output, (int2)(coord.x + 106, coord.y), val);
write_imageui(output, (int2)(coord.x + 107, coord.y), val);
write_imageui(output, (int2)(coord.x + 108, coord.y), val);
write_imageui(output, (int2)(coord.x + 109, coord.y), val);
write_imageui(output, (int2)(coord.x + 110, coord.y), val);
write_imageui(output, (int2)(coord.x + 111, coord.y), val);
write_imageui(output, (int2)(coord.x + 112, coord.y), val);
write_imageui(output, (int2)(coord.x + 113, coord.y), val);
write_imageui(output, (int2)(coord.x + 114, coord.y), val);
write_imageui(output, (int2)(coord.x + 115, coord.y), val);
write_imageui(output, (int2)(coord.x + 116, coord.y), val);
write_imageui(output, (int2)(coord.x + 117, coord.y), val);
write_imageui(output, (int2)(coord.x + 118, coord.y), val);
write_imageui(output, (int2)(coord.x + 119, coord.y), val);
write_imageui(output, (int2)(coord.x + 120, coord.y), val);
write_imageui(output, (int2)(coord.x + 121, coord.y), val);
write_imageui(output, (int2)(coord.x + 122, coord.y), val);
write_imageui(output, (int2)(coord.x + 123, coord.y), val);
write_imageui(output, (int2)(coord.x + 124, coord.y), val);
write_imageui(output, (int2)(coord.x + 125, coord.y), val);
write_imageui(output, (int2)(coord.x + 126, coord.y), val);
write_imageui(output, (int2)(coord.x + 127, coord.y), val);
write_imageui(output, (int2)(coord.x + 128, coord.y), val);
write_imageui(output, (int2)(coord.x + 129, coord.y), val);
write_imageui(output, (int2)(coord.x + 130, coord.y), val);
write_imageui(output, (int2)(coord.x + 131, coord.y), val);
write_imageui(output, (int2)(coord.x + 132, coord.y), val);
write_imageui(output, (int2)(coord.x + 133, coord.y), val);
write_imageui(output, (int2)(coord.x + 134, coord.y), val);
write_imageui(output, (int2)(coord.x + 135, coord.y), val);
write_imageui(output, (int2)(coord.x + 136, coord.y), val);
write_imageui(output, (int2)(coord.x + 137, coord.y), val);
write_imageui(output, (int2)(coord.x + 138, coord.y), val);
write_imageui(output, (int2)(coord.x + 139, coord.y), val);
write_imageui(output, (int2)(coord.x + 140, coord.y), val);
write_imageui(output, (int2)(coord.x + 141, coord.y), val);
write_imageui(output, (int2)(coord.x + 142, coord.y), val);
write_imageui(output, (int2)(coord.x + 143, coord.y), val);
write_imageui(output, (int2)(coord.x + 144, coord.y), val);
write_imageui(output, (int2)(coord.x + 145, coord.y), val);
write_imageui(output, (int2)(coord.x + 146, coord.y), val);
write_imageui(output, (int2)(coord.x + 147, coord.y), val);
write_imageui(output, (int2)(coord.x + 148, coord.y), val);
write_imageui(output, (int2)(coord.x + 149, coord.y), val);
write_imageui(output, (int2)(coord.x + 150, coord.y), val);
write_imageui(output, (int2)(coord.x + 151, coord.y), val);
write_imageui(output, (int2)(coord.x + 152, coord.y), val);
write_imageui(output, (int2)(coord.x + 153, coord.y), val);
write_imageui(output, (int2)(coord.x + 154, coord.y), val);
write_imageui(output, (int2)(coord.x + 155, coord.y), val);
write_imageui(output, (int2)(coord.x + 156, coord.y), val);
write_imageui(output, (int2)(coord.x + 157, coord.y), val);
write_imageui(output, (int2)(coord.x + 158, coord.y), val);
write_imageui(output, (int2)(coord.x + 159, coord.y), val);
write_imageui(output, (int2)(coord.x + 160, coord.y), val);
write_imageui(output, (int2)(coord.x + 161, coord.y), val);
write_imageui(output, (int2)(coord.x + 162, coord.y), val);
write_imageui(output, (int2)(coord.x + 163, coord.y), val);
write_imageui(output, (int2)(coord.x + 164, coord.y), val);
write_imageui(output, (int2)(coord.x + 165, coord.y), val);
write_imageui(output, (int2)(coord.x + 166, coord.y), val);
write_imageui(output, (int2)(coord.x + 167, coord.y), val);
write_imageui(output, (int2)(coord.x + 168, coord.y), val);
write_imageui(output, (int2)(coord.x + 169, coord.y), val);
write_imageui(output, (int2)(coord.x + 170, coord.y), val);
write_imageui(output, (int2)(coord.x + 171, coord.y), val);
write_imageui(output, (int2)(coord.x + 172, coord.y), val);
write_imageui(output, (int2)(coord.x + 173, coord.y), val);
write_imageui(output, (int2)(coord.x + 174, coord.y), val);
write_imageui(output, (int2)(coord.x + 175, coord.y), val);
write_imageui(output, (int2)(coord.x + 176, coord.y), val);
write_imageui(output, (int2)(coord.x + 177, coord.y), val);
write_imageui(output, (int2)(coord.x + 178, coord.y), val);
write_imageui(output, (int2)(coord.x + 179, coord.y), val);
write_imageui(output, (int2)(coord.x + 180, coord.y), val);
write_imageui(output, (int2)(coord.x + 181, coord.y), val);
write_imageui(output, (int2)(coord.x + 182, coord.y), val);
write_imageui(output, (int2)(coord.x + 183, coord.y), val);
write_imageui(output, (int2)(coord.x + 184, coord.y), val);
write_imageui(output, (int2)(coord.x + 185, coord.y), val);
write_imageui(output, (int2)(coord.x + 186, coord.y), val);
write_imageui(output, (int2)(coord.x + 187, coord.y), val);
write_imageui(output, (int2)(coord.x + 188, coord.y), val);
write_imageui(output, (int2)(coord.x + 189, coord.y), val);
write_imageui(output, (int2)(coord.x + 190, coord.y), val);
write_imageui(output, (int2)(coord.x + 191, coord.y), val);
write_imageui(output, (int2)(coord.x + 192, coord.y), val);
write_imageui(output, (int2)(coord.x + 193, coord.y), val);
write_imageui(output, (int2)(coord.x + 194, coord.y), val);
write_imageui(output, (int2)(coord.x + 195, coord.y), val);
write_imageui(output, (int2)(coord.x + 196, coord.y), val);
write_imageui(output, (int2)(coord.x + 197, coord.y), val);
write_imageui(output, (int2)(coord.x + 198, coord.y), val);
write_imageui(output, (int2)(coord.x + 199, coord.y), val);
write_imageui(output, (int2)(coord.x + 200, coord.y), val);
write_imageui(output, (int2)(coord.x + 201, coord.y), val);
write_imageui(output, (int2)(coord.x + 202, coord.y), val);
write_imageui(output, (int2)(coord.x + 203, coord.y), val);
write_imageui(output, (int2)(coord.x + 204, coord.y), val);
write_imageui(output, (int2)(coord.x + 205, coord.y), val);
write_imageui(output, (int2)(coord.x + 206, coord.y), val);
write_imageui(output, (int2)(coord.x + 207, coord.y), val);
write_imageui(output, (int2)(coord.x + 208, coord.y), val);
write_imageui(output, (int2)(coord.x + 209, coord.y), val);
write_imageui(output, (int2)(coord.x + 210, coord.y), val);
write_imageui(output, (int2)(coord.x + 211, coord.y), val);
write_imageui(output, (int2)(coord.x + 212, coord.y), val);
write_imageui(output, (int2)(coord.x + 213, coord.y), val);
write_imageui(output, (int2)(coord.x + 214, coord.y), val);
write_imageui(output, (int2)(coord.x + 215, coord.y), val);
write_imageui(output, (int2)(coord.x + 216, coord.y), val);
write_imageui(output, (int2)(coord.x + 217, coord.y), val);
write_imageui(output, (int2)(coord.x + 218, coord.y), val);
write_imageui(output, (int2)(coord.x + 219, coord.y), val);
write_imageui(output, (int2)(coord.x + 220, coord.y), val);
write_imageui(output, (int2)(coord.x + 221, coord.y), val);
write_imageui(output, (int2)(coord.x + 222, coord.y), val);
write_imageui(output, (int2)(coord.x + 223, coord.y), val);
write_imageui(output, (int2)(coord.x + 224, coord.y), val);
write_imageui(output, (int2)(coord.x + 225, coord.y), val);
write_imageui(output, (int2)(coord.x + 226, coord.y), val);
write_imageui(output, (int2)(coord.x + 227, coord.y), val);
write_imageui(output, (int2)(coord.x + 228, coord.y), val);
write_imageui(output, (int2)(coord.x + 229, coord.y), val);
write_imageui(output, (int2)(coord.x + 230, coord.y), val);
write_imageui(output, (int2)(coord.x + 231, coord.y), val);
write_imageui(output, (int2)(coord.x + 232, coord.y), val);
write_imageui(output, (int2)(coord.x + 233, coord.y), val);
write_imageui(output, (int2)(coord.x + 234, coord.y), val);
write_imageui(output, (int2)(coord.x + 235, coord.y), val);
write_imageui(output, (int2)(coord.x + 236, coord.y), val);
write_imageui(output, (int2)(coord.x + 237, coord.y), val);
write_imageui(output, (int2)(coord.x + 238, coord.y), val);
write_imageui(output, (int2)(coord.x + 239, coord.y), val);
write_imageui(output, (int2)(coord.x + 240, coord.y), val);
write_imageui(output, (int2)(coord.x + 241, coord.y), val);
write_imageui(output, (int2)(coord.x + 242, coord.y), val);
write_imageui(output, (int2)(coord.x + 243, coord.y), val);
write_imageui(output, (int2)(coord.x + 244, coord.y), val);
write_imageui(output, (int2)(coord.x + 245, coord.y), val);
write_imageui(output, (int2)(coord.x + 246, coord.y), val);
write_imageui(output, (int2)(coord.x + 247, coord.y), val);
write_imageui(output, (int2)(coord.x + 248, coord.y), val);
write_imageui(output, (int2)(coord.x + 249, coord.y), val);
write_imageui(output, (int2)(coord.x + 250, coord.y), val);
write_imageui(output, (int2)(coord.x + 251, coord.y), val);
write_imageui(output, (int2)(coord.x + 252, coord.y), val);
write_imageui(output, (int2)(coord.x + 253, coord.y), val);
write_imageui(output, (int2)(coord.x + 254, coord.y), val);
write_imageui(output, (int2)(coord.x + 255, coord.y), val);
}


// buildOptions=
// RUN: %occ-cli %s --cl-options="-I%cwd -I%S " %cfg_path --cl-device=%cl_device 2>&1
