//Primary input is original surface
__kernel void specialKernel0(read_only image2d_t inputImage, write_only image2d_t outputImage)
{
    const sampler_t sampler=CLK_NORMALIZED_COORDS_FALSE|CLK_ADDRESS_CLAMP_TO_EDGE|CLK_FILTER_NEAREST;
    int i = get_global_id(0);
    int j = get_global_id(1);
    //if (i>=src[0]) return;
    //if (j>=src[1]) return;
    float accumWeights = 0;
    float4 pixel_orig=read_imagef(inputImage,sampler,(int2)(i,j));
    //long4 pixel_orig_long=convert_long4(pixel_orig);
    float4 pixel_new = (float4)(0, 0, 0, 255);
    float4 pixel0 = read_imagef(inputImage,sampler,(int2)(i-0,j+1));
    float4 pixel1 = read_imagef(inputImage,sampler,(int2)(i+1,j+1));
    float4 pixel2 = read_imagef(inputImage,sampler,(int2)(i-1,j+1));
    float4 pixel3 = read_imagef(inputImage,sampler,(int2)(i+2,j+1));
    float4 pixel4 = read_imagef(inputImage,sampler,(int2)(i-2,j+1));
    float4 pixel5 = read_imagef(inputImage,sampler,(int2)(i-0,j+2));
    float4 pixel6 = read_imagef(inputImage,sampler,(int2)(i+1,j+2));
    float4 pixel7 = read_imagef(inputImage,sampler,(int2)(i-1,j+2));
    float4 pixel8 = read_imagef(inputImage,sampler,(int2)(i+2,j+2));
    float4 pixel9 = read_imagef(inputImage,sampler,(int2)(i-2,j+2));
    float4 pixel10 = read_imagef(inputImage,sampler,(int2)(i-0,j-1));
    float4 pixel11 = read_imagef(inputImage,sampler,(int2)(i+1,j-1));
    float4 pixel12 = read_imagef(inputImage,sampler,(int2)(i-1,j-1));
    float4 pixel13 = read_imagef(inputImage,sampler,(int2)(i+2,j-1));
    float4 pixel14 = read_imagef(inputImage,sampler,(int2)(i-2,j-1));
    float4 pixel15 = read_imagef(inputImage,sampler,(int2)(i-0,j-2));
    float4 pixel16 = read_imagef(inputImage,sampler,(int2)(i+1,j-2));
    float4 pixel17 = read_imagef(inputImage,sampler,(int2)(i-1,j-2));
    float4 pixel18 = read_imagef(inputImage,sampler,(int2)(i+2,j-2));
    float4 pixel19 = read_imagef(inputImage,sampler,(int2)(i-2,j-2));
    pixel_new -= (pixel0)*(float)17.0; accumWeights -= 17;
    pixel_new -= (pixel1)*(float)10.0; accumWeights -= 10;
    pixel_new -= (pixel2)*(float)10.0; accumWeights -= 10;
    pixel_new -= (pixel3)*(float)2.0; accumWeights -= 2;
    pixel_new -= (pixel4)*(float)2.0; accumWeights -= 2;
    pixel_new -= (pixel5)*(float)7.0; accumWeights -= 7;
    pixel_new -= (pixel6)*(float)4.0; accumWeights -= 4;
    pixel_new -= (pixel7)*(float)4.0; accumWeights -= 4;
    pixel_new -= (pixel8)*(float)1.0; accumWeights -= 1;
    pixel_new -= (pixel9)*(float)1.0; accumWeights -= 1;
    pixel_new += (pixel10)*(float)17.0; accumWeights += 17;
    pixel_new += (pixel11)*(float)10.0; accumWeights += 10;
    pixel_new += (pixel12)*(float)10.0; accumWeights += 10;
    pixel_new += (pixel13)*(float)2.0; accumWeights += 2;
    pixel_new += (pixel14)*(float)2.0; accumWeights += 2;
    pixel_new += (pixel15)*(float)7.0; accumWeights += 7;
    pixel_new += (pixel16)*(float)4.0; accumWeights += 4;
    pixel_new += (pixel17)*(float)4.0; accumWeights += 4;
    pixel_new += (pixel18)*(float)1.0; accumWeights += 1;
    pixel_new += (pixel19)*(float)1.0; accumWeights += 1;
    pixel_new.w = 255;
    write_imagef(outputImage,(int2)(i,j), pixel_new);
};
//Secondary input is output of Pass0
//Primary input is original surface
__kernel void specialKernel1(read_only image2d_t inputImage, write_only image2d_t outputImage, read_only image2d_t inputImage2)
{
    const sampler_t sampler=CLK_NORMALIZED_COORDS_FALSE|CLK_ADDRESS_CLAMP_TO_EDGE|CLK_FILTER_NEAREST;
    int i = get_global_id(0);
    int j = get_global_id(1);
    //if (i>=src[0]) return;
    //if (j>=src[1]) return;
    float accumWeights = 0;
    float4 pixel_orig=read_imagef(inputImage,sampler,(int2)(i,j));
    //long4 pixel_orig_long=convert_long4(pixel_orig);
    float4 pixel_new = (float4)(0, 0, 0, 255);
    float4 pixel0 = read_imagef(inputImage,sampler,(int2)(i+2,j+0));
    float4 pixel1 = read_imagef(inputImage,sampler,(int2)(i+2,j-1));
    float4 pixel2 = read_imagef(inputImage,sampler,(int2)(i+2,j+1));
    float4 pixel3 = read_imagef(inputImage,sampler,(int2)(i+2,j+2));
    float4 pixel4 = read_imagef(inputImage,sampler,(int2)(i+2,j-2));
    float4 pixel5 = read_imagef(inputImage,sampler,(int2)(i+1,j+0));
    float4 pixel6 = read_imagef(inputImage,sampler,(int2)(i+1,j+1));
    float4 pixel7 = read_imagef(inputImage,sampler,(int2)(i+1,j-1));
    float4 pixel8 = read_imagef(inputImage,sampler,(int2)(i+1,j+2));
    float4 pixel9 = read_imagef(inputImage,sampler,(int2)(i+1,j-2));
    float4 pixel10 = read_imagef(inputImage,sampler,(int2)(i-1,j+0));
    float4 pixel11 = read_imagef(inputImage,sampler,(int2)(i-1,j+1));
    float4 pixel12 = read_imagef(inputImage,sampler,(int2)(i-1,j-1));
    float4 pixel13 = read_imagef(inputImage,sampler,(int2)(i-1,j+2));
    float4 pixel14 = read_imagef(inputImage,sampler,(int2)(i-1,j-2));
    float4 pixel15 = read_imagef(inputImage,sampler,(int2)(i-2,j+0));
    float4 pixel16 = read_imagef(inputImage,sampler,(int2)(i-2,j+1));
    float4 pixel17 = read_imagef(inputImage,sampler,(int2)(i-2,j-1));
    float4 pixel18 = read_imagef(inputImage,sampler,(int2)(i-2,j-2));
    float4 pixel19 = read_imagef(inputImage,sampler,(int2)(i-2,j+2));
    pixel_new += (pixel0)*(float)7.0; accumWeights += 7;
    pixel_new += (pixel1)*(float)4.0; accumWeights += 4;
    pixel_new += (pixel2)*(float)4.0; accumWeights += 4;
    pixel_new += (pixel3)*(float)1.0; accumWeights += 1;
    pixel_new += (pixel4)*(float)1.0; accumWeights += 1;
    pixel_new += (pixel5)*(float)17.0; accumWeights += 17;
    pixel_new += (pixel6)*(float)10.0; accumWeights += 10;
    pixel_new += (pixel7)*(float)10.0; accumWeights += 10;
    pixel_new += (pixel8)*(float)2.0; accumWeights += 2;
    pixel_new += (pixel9)*(float)2.0; accumWeights += 2;
    pixel_new -= (pixel10)*(float)17.0; accumWeights -= 17;
    pixel_new -= (pixel11)*(float)10.0; accumWeights -= 10;
    pixel_new -= (pixel12)*(float)10.0; accumWeights -= 10;
    pixel_new -= (pixel13)*(float)2.0; accumWeights -= 2;
    pixel_new -= (pixel14)*(float)2.0; accumWeights -= 2;
    pixel_new -= (pixel15)*(float)7.0; accumWeights -= 7;
    pixel_new -= (pixel16)*(float)4.0; accumWeights -= 4;
    pixel_new -= (pixel17)*(float)4.0; accumWeights -= 4;
    pixel_new -= (pixel18)*(float)1.0; accumWeights -= 1;
    pixel_new -= (pixel19)*(float)1.0; accumWeights -= 1;
    float4 pixel_2ndary=read_imagef(inputImage2,sampler,(int2)(i,j));
    pixel_new.x = sqrt((float)(pixel_new.x*pixel_new.x+pixel_2ndary.x*pixel_2ndary.x));
    pixel_new.y = sqrt((float)(pixel_new.y*pixel_new.y+pixel_2ndary.y*pixel_2ndary.y));
    pixel_new.z = sqrt((float)(pixel_new.z*pixel_new.z+pixel_2ndary.z*pixel_2ndary.z));
    pixel_new = fabs(pixel_new);
    if (pixel_new.x>255) pixel_new.x = 255;
    if (pixel_new.y>255) pixel_new.y = 255;
    if (pixel_new.z>255) pixel_new.z = 255;
    pixel_new.w = 255;
    write_imagef(outputImage,(int2)(i,j), pixel_new);
};


// buildOptions=
// RUN: %occ-cli %s --cl-options="-I%cwd -I%S " %cfg_path --cl-device=%cl_device 2>&1
