//Primary input is original surface
__kernel void specialKernel0(read_only image2d_t inputImage, write_only image2d_t outputImage)
{
    const sampler_t sampler=CLK_NORMALIZED_COORDS_FALSE|CLK_ADDRESS_CLAMP_TO_EDGE|CLK_FILTER_NEAREST;
    int i = get_global_id(0);
    int j = get_global_id(1);
    //if (i>=src[0]) return;
    //if (j>=src[1]) return;
    float accumWeights = 0;
    float4 pixel_orig=read_imagef(inputImage,sampler,(int2)(i,j));
    //long4 pixel_orig_long=convert_long4(pixel_orig);
    float4 pixel_new = (float4)(0, 0, 0, 255);
    float4 pixel0 = read_imagef(inputImage,sampler,(int2)(i-0,j+1));
    float4 pixel1 = read_imagef(inputImage,sampler,(int2)(i+1,j+1));
    float4 pixel2 = read_imagef(inputImage,sampler,(int2)(i-1,j+1));
    float4 pixel3 = read_imagef(inputImage,sampler,(int2)(i+2,j+1));
    float4 pixel4 = read_imagef(inputImage,sampler,(int2)(i-2,j+1));
    float4 pixel5 = read_imagef(inputImage,sampler,(int2)(i+3,j+1));
    float4 pixel6 = read_imagef(inputImage,sampler,(int2)(i-3,j+1));
    float4 pixel7 = read_imagef(inputImage,sampler,(int2)(i-0,j+2));
    float4 pixel8 = read_imagef(inputImage,sampler,(int2)(i+1,j+2));
    float4 pixel9 = read_imagef(inputImage,sampler,(int2)(i-1,j+2));
    float4 pixel10 = read_imagef(inputImage,sampler,(int2)(i+2,j+2));
    float4 pixel11 = read_imagef(inputImage,sampler,(int2)(i-2,j+2));
    float4 pixel12 = read_imagef(inputImage,sampler,(int2)(i+3,j+2));
    float4 pixel13 = read_imagef(inputImage,sampler,(int2)(i-3,j+2));
    float4 pixel14 = read_imagef(inputImage,sampler,(int2)(i-0,j+3));
    float4 pixel15 = read_imagef(inputImage,sampler,(int2)(i+1,j+3));
    float4 pixel16 = read_imagef(inputImage,sampler,(int2)(i-1,j+3));
    float4 pixel17 = read_imagef(inputImage,sampler,(int2)(i+2,j+3));
    float4 pixel18 = read_imagef(inputImage,sampler,(int2)(i-2,j+3));
    float4 pixel19 = read_imagef(inputImage,sampler,(int2)(i+3,j+3));
    float4 pixel20 = read_imagef(inputImage,sampler,(int2)(i-3,j+3));
    float4 pixel21 = read_imagef(inputImage,sampler,(int2)(i-0,j-1));
    float4 pixel22 = read_imagef(inputImage,sampler,(int2)(i+1,j-1));
    float4 pixel23 = read_imagef(inputImage,sampler,(int2)(i-1,j-1));
    float4 pixel24 = read_imagef(inputImage,sampler,(int2)(i+2,j-1));
    float4 pixel25 = read_imagef(inputImage,sampler,(int2)(i-2,j-1));
    float4 pixel26 = read_imagef(inputImage,sampler,(int2)(i+3,j-1));
    float4 pixel27 = read_imagef(inputImage,sampler,(int2)(i-3,j-1));
    float4 pixel28 = read_imagef(inputImage,sampler,(int2)(i-0,j-2));
    float4 pixel29 = read_imagef(inputImage,sampler,(int2)(i+1,j-2));
    float4 pixel30 = read_imagef(inputImage,sampler,(int2)(i-1,j-2));
    float4 pixel31 = read_imagef(inputImage,sampler,(int2)(i+2,j-2));
    float4 pixel32 = read_imagef(inputImage,sampler,(int2)(i-2,j-2));
    float4 pixel33 = read_imagef(inputImage,sampler,(int2)(i+3,j-2));
    float4 pixel34 = read_imagef(inputImage,sampler,(int2)(i-3,j-2));
    float4 pixel35 = read_imagef(inputImage,sampler,(int2)(i-0,j-3));
    float4 pixel36 = read_imagef(inputImage,sampler,(int2)(i+1,j-3));
    float4 pixel37 = read_imagef(inputImage,sampler,(int2)(i-1,j-3));
    float4 pixel38 = read_imagef(inputImage,sampler,(int2)(i+2,j-3));
    float4 pixel39 = read_imagef(inputImage,sampler,(int2)(i-2,j-3));
    float4 pixel40 = read_imagef(inputImage,sampler,(int2)(i+3,j-3));
    float4 pixel41 = read_imagef(inputImage,sampler,(int2)(i-3,j-3));
    pixel_new -= (pixel0)*(float)40.0; accumWeights -= 40;
    pixel_new -= (pixel1)*(float)30.0; accumWeights -= 30;
    pixel_new -= (pixel2)*(float)30.0; accumWeights -= 30;
    pixel_new -= (pixel3)*(float)13.0; accumWeights -= 13;
    pixel_new -= (pixel4)*(float)13.0; accumWeights -= 13;
    pixel_new -= (pixel5)*(float)3.0; accumWeights -= 3;
    pixel_new -= (pixel6)*(float)3.0; accumWeights -= 3;
    pixel_new -= (pixel7)*(float)34.0; accumWeights -= 34;
    pixel_new -= (pixel8)*(float)26.0; accumWeights -= 26;
    pixel_new -= (pixel9)*(float)26.0; accumWeights -= 26;
    pixel_new -= (pixel10)*(float)11.0; accumWeights -= 11;
    pixel_new -= (pixel11)*(float)11.0; accumWeights -= 11;
    pixel_new -= (pixel12)*(float)3.0; accumWeights -= 3;
    pixel_new -= (pixel13)*(float)3.0; accumWeights -= 3;
    pixel_new -= (pixel14)*(float)13.0; accumWeights -= 13;
    pixel_new -= (pixel15)*(float)9.0; accumWeights -= 9;
    pixel_new -= (pixel16)*(float)9.0; accumWeights -= 9;
    pixel_new -= (pixel17)*(float)4.0; accumWeights -= 4;
    pixel_new -= (pixel18)*(float)4.0; accumWeights -= 4;
    pixel_new -= (pixel19)*(float)1.0; accumWeights -= 1;
    pixel_new -= (pixel20)*(float)1.0; accumWeights -= 1;
    pixel_new += (pixel21)*(float)40.0; accumWeights += 40;
    pixel_new += (pixel22)*(float)30.0; accumWeights += 30;
    pixel_new += (pixel23)*(float)30.0; accumWeights += 30;
    pixel_new += (pixel24)*(float)13.0; accumWeights += 13;
    pixel_new += (pixel25)*(float)13.0; accumWeights += 13;
    pixel_new += (pixel26)*(float)3.0; accumWeights += 3;
    pixel_new += (pixel27)*(float)3.0; accumWeights += 3;
    pixel_new += (pixel28)*(float)34.0; accumWeights += 34;
    pixel_new += (pixel29)*(float)26.0; accumWeights += 26;
    pixel_new += (pixel30)*(float)26.0; accumWeights += 26;
    pixel_new += (pixel31)*(float)11.0; accumWeights += 11;
    pixel_new += (pixel32)*(float)11.0; accumWeights += 11;
    pixel_new += (pixel33)*(float)3.0; accumWeights += 3;
    pixel_new += (pixel34)*(float)3.0; accumWeights += 3;
    pixel_new += (pixel35)*(float)13.0; accumWeights += 13;
    pixel_new += (pixel36)*(float)9.0; accumWeights += 9;
    pixel_new += (pixel37)*(float)9.0; accumWeights += 9;
    pixel_new += (pixel38)*(float)4.0; accumWeights += 4;
    pixel_new += (pixel39)*(float)4.0; accumWeights += 4;
    pixel_new += (pixel40)*(float)1.0; accumWeights += 1;
    pixel_new += (pixel41)*(float)1.0; accumWeights += 1;
    pixel_new.w = 255;
    write_imagef(outputImage,(int2)(i,j), pixel_new);
};
//Secondary input is output of Pass0
//Primary input is original surface
__kernel void specialKernel1(read_only image2d_t inputImage, write_only image2d_t outputImage, read_only image2d_t inputImage2)
{
    const sampler_t sampler=CLK_NORMALIZED_COORDS_FALSE|CLK_ADDRESS_CLAMP_TO_EDGE|CLK_FILTER_NEAREST;
    int i = get_global_id(0);
    int j = get_global_id(1);
    //if (i>=src[0]) return;
    //if (j>=src[1]) return;
    float accumWeights = 0;
    float4 pixel_orig=read_imagef(inputImage,sampler,(int2)(i,j));
    //long4 pixel_orig_long=convert_long4(pixel_orig);
    float4 pixel_new = (float4)(0, 0, 0, 255);
    float4 pixel0 = read_imagef(inputImage,sampler,(int2)(i+1,j+0));
    float4 pixel1 = read_imagef(inputImage,sampler,(int2)(i+1,j-1));
    float4 pixel2 = read_imagef(inputImage,sampler,(int2)(i+1,j+1));
    float4 pixel3 = read_imagef(inputImage,sampler,(int2)(i+1,j-2));
    float4 pixel4 = read_imagef(inputImage,sampler,(int2)(i+1,j+2));
    float4 pixel5 = read_imagef(inputImage,sampler,(int2)(i-1,j+0));
    float4 pixel6 = read_imagef(inputImage,sampler,(int2)(i-1,j-1));
    float4 pixel7 = read_imagef(inputImage,sampler,(int2)(i-1,j-2));
    float4 pixel8 = read_imagef(inputImage,sampler,(int2)(i-1,j+1));
    float4 pixel9 = read_imagef(inputImage,sampler,(int2)(i-1,j+2));
    float4 pixel10 = read_imagef(inputImage,sampler,(int2)(i-1,j+3));
    float4 pixel11 = read_imagef(inputImage,sampler,(int2)(i-1,j-3));
    float4 pixel12 = read_imagef(inputImage,sampler,(int2)(i+1,j-3));
    float4 pixel13 = read_imagef(inputImage,sampler,(int2)(i+1,j+3));
    float4 pixel14 = read_imagef(inputImage,sampler,(int2)(i+2,j+3));
    float4 pixel15 = read_imagef(inputImage,sampler,(int2)(i+2,j-3));
    float4 pixel16 = read_imagef(inputImage,sampler,(int2)(i+2,j-2));
    float4 pixel17 = read_imagef(inputImage,sampler,(int2)(i+2,j+2));
    float4 pixel18 = read_imagef(inputImage,sampler,(int2)(i+2,j-1));
    float4 pixel19 = read_imagef(inputImage,sampler,(int2)(i+2,j+1));
    float4 pixel20 = read_imagef(inputImage,sampler,(int2)(i+2,j+0));
    float4 pixel21 = read_imagef(inputImage,sampler,(int2)(i-2,j+0));
    float4 pixel22 = read_imagef(inputImage,sampler,(int2)(i-2,j+1));
    float4 pixel23 = read_imagef(inputImage,sampler,(int2)(i-2,j-1));
    float4 pixel24 = read_imagef(inputImage,sampler,(int2)(i-2,j+2));
    float4 pixel25 = read_imagef(inputImage,sampler,(int2)(i-2,j-2));
    float4 pixel26 = read_imagef(inputImage,sampler,(int2)(i-2,j+3));
    float4 pixel27 = read_imagef(inputImage,sampler,(int2)(i-2,j-3));
    float4 pixel28 = read_imagef(inputImage,sampler,(int2)(i+3,j+0));
    float4 pixel29 = read_imagef(inputImage,sampler,(int2)(i-3,j+0));
    float4 pixel30 = read_imagef(inputImage,sampler,(int2)(i+3,j+1));
    float4 pixel31 = read_imagef(inputImage,sampler,(int2)(i+3,j-1));
    float4 pixel32 = read_imagef(inputImage,sampler,(int2)(i-3,j-1));
    float4 pixel33 = read_imagef(inputImage,sampler,(int2)(i-3,j+1));
    float4 pixel34 = read_imagef(inputImage,sampler,(int2)(i-3,j+2));
    float4 pixel35 = read_imagef(inputImage,sampler,(int2)(i-3,j-2));
    float4 pixel36 = read_imagef(inputImage,sampler,(int2)(i+3,j-2));
    float4 pixel37 = read_imagef(inputImage,sampler,(int2)(i+3,j+2));
    float4 pixel38 = read_imagef(inputImage,sampler,(int2)(i+3,j+3));
    float4 pixel39 = read_imagef(inputImage,sampler,(int2)(i+3,j-3));
    float4 pixel40 = read_imagef(inputImage,sampler,(int2)(i-3,j+3));
    float4 pixel41 = read_imagef(inputImage,sampler,(int2)(i-3,j-3));
    pixel_new += (pixel0)*(float)40.0; accumWeights += 40;
    pixel_new += (pixel1)*(float)30.0; accumWeights += 30;
    pixel_new += (pixel2)*(float)30.0; accumWeights += 30;
    pixel_new += (pixel3)*(float)13.0; accumWeights += 13;
    pixel_new += (pixel4)*(float)13.0; accumWeights += 13;
    pixel_new -= (pixel5)*(float)40.0; accumWeights -= 40;
    pixel_new -= (pixel6)*(float)30.0; accumWeights -= 30;
    pixel_new -= (pixel7)*(float)13.0; accumWeights -= 13;
    pixel_new -= (pixel8)*(float)30.0; accumWeights -= 30;
    pixel_new -= (pixel9)*(float)13.0; accumWeights -= 13;
    pixel_new -= (pixel10)*(float)3.0; accumWeights -= 3;
    pixel_new -= (pixel11)*(float)3.0; accumWeights -= 3;
    pixel_new += (pixel12)*(float)3.0; accumWeights += 3;
    pixel_new += (pixel13)*(float)3.0; accumWeights += 3;
    pixel_new += (pixel14)*(float)3.0; accumWeights += 3;
    pixel_new += (pixel15)*(float)3.0; accumWeights += 3;
    pixel_new += (pixel16)*(float)11.0; accumWeights += 11;
    pixel_new += (pixel17)*(float)11.0; accumWeights += 11;
    pixel_new += (pixel18)*(float)26.0; accumWeights += 26;
    pixel_new += (pixel19)*(float)26.0; accumWeights += 26;
    pixel_new += (pixel20)*(float)34.0; accumWeights += 34;
    pixel_new -= (pixel21)*(float)34.0; accumWeights -= 34;
    pixel_new -= (pixel22)*(float)26.0; accumWeights -= 26;
    pixel_new -= (pixel23)*(float)26.0; accumWeights -= 26;
    pixel_new -= (pixel24)*(float)11.0; accumWeights -= 11;
    pixel_new -= (pixel25)*(float)11.0; accumWeights -= 11;
    pixel_new -= (pixel26)*(float)3.0; accumWeights -= 3;
    pixel_new -= (pixel27)*(float)3.0; accumWeights -= 3;
    pixel_new += (pixel28)*(float)13.0; accumWeights += 13;
    pixel_new -= (pixel29)*(float)13.0; accumWeights -= 13;
    pixel_new += (pixel30)*(float)9.0; accumWeights += 9;
    pixel_new += (pixel31)*(float)9.0; accumWeights += 9;
    pixel_new -= (pixel32)*(float)9.0; accumWeights -= 9;
    pixel_new -= (pixel33)*(float)9.0; accumWeights -= 9;
    pixel_new -= (pixel34)*(float)4.0; accumWeights -= 4;
    pixel_new -= (pixel35)*(float)4.0; accumWeights -= 4;
    pixel_new += (pixel36)*(float)4.0; accumWeights += 4;
    pixel_new += (pixel37)*(float)4.0; accumWeights += 4;
    pixel_new += (pixel38)*(float)1.0; accumWeights += 1;
    pixel_new += (pixel39)*(float)1.0; accumWeights += 1;
    pixel_new -= (pixel40)*(float)1.0; accumWeights -= 1;
    pixel_new -= (pixel41)*(float)1.0; accumWeights -= 1;
    float4 pixel_2ndary=read_imagef(inputImage2,sampler,(int2)(i,j));
    pixel_new.x = sqrt((float)(pixel_new.x*pixel_new.x+pixel_2ndary.x*pixel_2ndary.x));
    pixel_new.y = sqrt((float)(pixel_new.y*pixel_new.y+pixel_2ndary.y*pixel_2ndary.y));
    pixel_new.z = sqrt((float)(pixel_new.z*pixel_new.z+pixel_2ndary.z*pixel_2ndary.z));
    pixel_new = fabs(pixel_new);
    if (pixel_new.x>255) pixel_new.x = 255;
    if (pixel_new.y>255) pixel_new.y = 255;
    if (pixel_new.z>255) pixel_new.z = 255;
    pixel_new.w = 255;
    write_imagef(outputImage,(int2)(i,j), pixel_new);
};


// buildOptions=
// RUN: %occ-cli %s --cl-options="-I%cwd -I%S " %cfg_path --cl-device=%cl_device 2>&1
