//Primary input is original surface
__kernel void specialKernel0(read_only image2d_t inputImage, write_only image2d_t outputImage)
{
    const sampler_t sampler=CLK_NORMALIZED_COORDS_FALSE|CLK_ADDRESS_CLAMP_TO_EDGE|CLK_FILTER_NEAREST;
    int i = get_global_id(0);
    int j = get_global_id(1);
    //if (i>=src[0]) return;
    //if (j>=src[1]) return;
    float accumWeights = 0;
    float4 pixel_orig=read_imagef(inputImage,sampler,(int2)(i,j));
    //long4 pixel_orig_long=convert_long4(pixel_orig);
    float4 pixel_new = (float4)(0, 0, 0, 255);
    float4 pixel0 = read_imagef(inputImage,sampler,(int2)(i-0,j+0));
    float4 pixel1 = read_imagef(inputImage,sampler,(int2)(i-1,j+0));
    float4 pixel2 = read_imagef(inputImage,sampler,(int2)(i-0,j-1));
    float4 pixel3 = read_imagef(inputImage,sampler,(int2)(i+1,j+0));
    float4 pixel4 = read_imagef(inputImage,sampler,(int2)(i-0,j+1));
    float4 pixel5 = read_imagef(inputImage,sampler,(int2)(i+1,j-1));
    float4 pixel6 = read_imagef(inputImage,sampler,(int2)(i+1,j+1));
    float4 pixel7 = read_imagef(inputImage,sampler,(int2)(i-1,j+1));
    float4 pixel8 = read_imagef(inputImage,sampler,(int2)(i-1,j-1));
    pixel_new += (pixel0)*(float)4.0; accumWeights += 4;
    pixel_new += (pixel1)*(float)2.0; accumWeights += 2;
    pixel_new += (pixel2)*(float)2.0; accumWeights += 2;
    pixel_new += (pixel3)*(float)2.0; accumWeights += 2;
    pixel_new += (pixel4)*(float)2.0; accumWeights += 2;
    pixel_new += (pixel5)*(float)1.0; accumWeights += 1;
    pixel_new += (pixel6)*(float)1.0; accumWeights += 1;
    pixel_new += (pixel7)*(float)1.0; accumWeights += 1;
    pixel_new += (pixel8)*(float)1.0; accumWeights += 1;
    pixel_new = (accumWeights==0)?0:pixel_new/accumWeights; pixel_new.w = 255;
    pixel_new.w = 255;
    write_imagef(outputImage,(int2)(i,j), pixel_new);
};
//Primary input is original surface
__kernel void specialKernel1(read_only image2d_t inputImage, write_only image2d_t outputImage)
{
    const sampler_t sampler=CLK_NORMALIZED_COORDS_FALSE|CLK_ADDRESS_CLAMP_TO_EDGE|CLK_FILTER_NEAREST;
    int i = get_global_id(0);
    int j = get_global_id(1);
    //if (i>=src[0]) return;
    //if (j>=src[1]) return;
    float accumWeights = 0;
    float4 pixel_orig=read_imagef(inputImage,sampler,(int2)(i,j));
    //long4 pixel_orig_long=convert_long4(pixel_orig);
    float4 pixel_new = (float4)(0, 0, 0, 255);
    float4 pixel0 = read_imagef(inputImage,sampler,(int2)(i-0,j+0));
    float4 pixel1 = read_imagef(inputImage,sampler,(int2)(i-0,j-1));
    float4 pixel2 = read_imagef(inputImage,sampler,(int2)(i+1,j+0));
    float4 pixel3 = read_imagef(inputImage,sampler,(int2)(i-0,j+1));
    float4 pixel4 = read_imagef(inputImage,sampler,(int2)(i-1,j+0));
    float4 pixel5 = read_imagef(inputImage,sampler,(int2)(i+1,j-1));
    float4 pixel6 = read_imagef(inputImage,sampler,(int2)(i+1,j+1));
    float4 pixel7 = read_imagef(inputImage,sampler,(int2)(i-1,j+1));
    float4 pixel8 = read_imagef(inputImage,sampler,(int2)(i-1,j-1));
    float4 pixel9 = read_imagef(inputImage,sampler,(int2)(i-2,j+0));
    float4 pixel10 = read_imagef(inputImage,sampler,(int2)(i-0,j-2));
    float4 pixel11 = read_imagef(inputImage,sampler,(int2)(i+2,j+0));
    float4 pixel12 = read_imagef(inputImage,sampler,(int2)(i-0,j+2));
    float4 pixel13 = read_imagef(inputImage,sampler,(int2)(i-2,j+1));
    float4 pixel14 = read_imagef(inputImage,sampler,(int2)(i-1,j+2));
    float4 pixel15 = read_imagef(inputImage,sampler,(int2)(i+1,j+2));
    float4 pixel16 = read_imagef(inputImage,sampler,(int2)(i+2,j+1));
    float4 pixel17 = read_imagef(inputImage,sampler,(int2)(i+2,j-1));
    float4 pixel18 = read_imagef(inputImage,sampler,(int2)(i+1,j-2));
    float4 pixel19 = read_imagef(inputImage,sampler,(int2)(i-1,j-2));
    float4 pixel20 = read_imagef(inputImage,sampler,(int2)(i-2,j-1));
    float4 pixel21 = read_imagef(inputImage,sampler,(int2)(i-2,j-2));
    float4 pixel22 = read_imagef(inputImage,sampler,(int2)(i+2,j-2));
    float4 pixel23 = read_imagef(inputImage,sampler,(int2)(i+2,j+2));
    float4 pixel24 = read_imagef(inputImage,sampler,(int2)(i-2,j+2));
    pixel_new += (pixel0)*(float)127.0; accumWeights += 127;
    pixel_new += (pixel1)*(float)52.0; accumWeights += 52;
    pixel_new += (pixel2)*(float)52.0; accumWeights += 52;
    pixel_new += (pixel3)*(float)52.0; accumWeights += 52;
    pixel_new += (pixel4)*(float)52.0; accumWeights += 52;
    pixel_new += (pixel5)*(float)31.0; accumWeights += 31;
    pixel_new += (pixel6)*(float)31.0; accumWeights += 31;
    pixel_new += (pixel7)*(float)31.0; accumWeights += 31;
    pixel_new += (pixel8)*(float)31.0; accumWeights += 31;
    pixel_new += (pixel9)*(float)12.0; accumWeights += 12;
    pixel_new += (pixel10)*(float)12.0; accumWeights += 12;
    pixel_new += (pixel11)*(float)12.0; accumWeights += 12;
    pixel_new += (pixel12)*(float)12.0; accumWeights += 12;
    pixel_new += (pixel13)*(float)7.0; accumWeights += 7;
    pixel_new += (pixel14)*(float)7.0; accumWeights += 7;
    pixel_new += (pixel15)*(float)7.0; accumWeights += 7;
    pixel_new += (pixel16)*(float)7.0; accumWeights += 7;
    pixel_new += (pixel17)*(float)7.0; accumWeights += 7;
    pixel_new += (pixel18)*(float)7.0; accumWeights += 7;
    pixel_new += (pixel19)*(float)7.0; accumWeights += 7;
    pixel_new += (pixel20)*(float)7.0; accumWeights += 7;
    pixel_new += (pixel21)*(float)2.0; accumWeights += 2;
    pixel_new += (pixel22)*(float)2.0; accumWeights += 2;
    pixel_new += (pixel23)*(float)2.0; accumWeights += 2;
    pixel_new += (pixel24)*(float)2.0; accumWeights += 2;
    pixel_new = (accumWeights==0)?0:pixel_new/accumWeights; pixel_new.w = 255;
    pixel_new.w = 255;
    write_imagef(outputImage,(int2)(i,j), pixel_new);
};
//Primary input is original surface
__kernel void specialKernel2(read_only image2d_t inputImage, write_only image2d_t outputImage)
{
    const sampler_t sampler=CLK_NORMALIZED_COORDS_FALSE|CLK_ADDRESS_CLAMP_TO_EDGE|CLK_FILTER_NEAREST;
    int i = get_global_id(0);
    int j = get_global_id(1);
    //if (i>=src[0]) return;
    //if (j>=src[1]) return;
    float accumWeights = 0;
    float4 pixel_orig=read_imagef(inputImage,sampler,(int2)(i,j));
    //long4 pixel_orig_long=convert_long4(pixel_orig);
    float4 pixel_new = (float4)(0, 0, 0, 255);
    float4 pixel0 = read_imagef(inputImage,sampler,(int2)(i+4,j+4));
    float4 pixel1 = read_imagef(inputImage,sampler,(int2)(i+4,j+3));
    float4 pixel2 = read_imagef(inputImage,sampler,(int2)(i+4,j+2));
    float4 pixel3 = read_imagef(inputImage,sampler,(int2)(i+4,j+1));
    float4 pixel4 = read_imagef(inputImage,sampler,(int2)(i+4,j+0));
    float4 pixel5 = read_imagef(inputImage,sampler,(int2)(i+4,j-1));
    float4 pixel6 = read_imagef(inputImage,sampler,(int2)(i+4,j-2));
    float4 pixel7 = read_imagef(inputImage,sampler,(int2)(i+4,j-3));
    float4 pixel8 = read_imagef(inputImage,sampler,(int2)(i+4,j-4));
    float4 pixel9 = read_imagef(inputImage,sampler,(int2)(i+3,j+4));
    float4 pixel10 = read_imagef(inputImage,sampler,(int2)(i+3,j+3));
    float4 pixel11 = read_imagef(inputImage,sampler,(int2)(i+3,j+2));
    float4 pixel12 = read_imagef(inputImage,sampler,(int2)(i+3,j+1));
    float4 pixel13 = read_imagef(inputImage,sampler,(int2)(i+3,j+0));
    float4 pixel14 = read_imagef(inputImage,sampler,(int2)(i+3,j-1));
    float4 pixel15 = read_imagef(inputImage,sampler,(int2)(i+3,j-2));
    float4 pixel16 = read_imagef(inputImage,sampler,(int2)(i+3,j-3));
    float4 pixel17 = read_imagef(inputImage,sampler,(int2)(i+3,j-4));
    float4 pixel18 = read_imagef(inputImage,sampler,(int2)(i+2,j+4));
    float4 pixel19 = read_imagef(inputImage,sampler,(int2)(i+2,j+3));
    float4 pixel20 = read_imagef(inputImage,sampler,(int2)(i+2,j+2));
    float4 pixel21 = read_imagef(inputImage,sampler,(int2)(i+2,j+1));
    float4 pixel22 = read_imagef(inputImage,sampler,(int2)(i+2,j+0));
    float4 pixel23 = read_imagef(inputImage,sampler,(int2)(i+2,j-1));
    float4 pixel24 = read_imagef(inputImage,sampler,(int2)(i+2,j-2));
    float4 pixel25 = read_imagef(inputImage,sampler,(int2)(i+2,j-3));
    float4 pixel26 = read_imagef(inputImage,sampler,(int2)(i+2,j-4));
    float4 pixel27 = read_imagef(inputImage,sampler,(int2)(i+1,j+4));
    float4 pixel28 = read_imagef(inputImage,sampler,(int2)(i+1,j+3));
    float4 pixel29 = read_imagef(inputImage,sampler,(int2)(i+1,j+2));
    float4 pixel30 = read_imagef(inputImage,sampler,(int2)(i+1,j+1));
    float4 pixel31 = read_imagef(inputImage,sampler,(int2)(i+1,j+0));
    float4 pixel32 = read_imagef(inputImage,sampler,(int2)(i+1,j-1));
    float4 pixel33 = read_imagef(inputImage,sampler,(int2)(i+1,j-2));
    float4 pixel34 = read_imagef(inputImage,sampler,(int2)(i+1,j-3));
    float4 pixel35 = read_imagef(inputImage,sampler,(int2)(i+1,j-4));
    float4 pixel36 = read_imagef(inputImage,sampler,(int2)(i-0,j+4));
    float4 pixel37 = read_imagef(inputImage,sampler,(int2)(i-0,j+3));
    float4 pixel38 = read_imagef(inputImage,sampler,(int2)(i-0,j+2));
    float4 pixel39 = read_imagef(inputImage,sampler,(int2)(i-0,j+1));
    float4 pixel40 = read_imagef(inputImage,sampler,(int2)(i-0,j+0));
    float4 pixel41 = read_imagef(inputImage,sampler,(int2)(i-0,j-1));
    float4 pixel42 = read_imagef(inputImage,sampler,(int2)(i-0,j-2));
    float4 pixel43 = read_imagef(inputImage,sampler,(int2)(i-0,j-3));
    float4 pixel44 = read_imagef(inputImage,sampler,(int2)(i-0,j-4));
    float4 pixel45 = read_imagef(inputImage,sampler,(int2)(i-1,j+4));
    float4 pixel46 = read_imagef(inputImage,sampler,(int2)(i-1,j+3));
    float4 pixel47 = read_imagef(inputImage,sampler,(int2)(i-1,j+2));
    float4 pixel48 = read_imagef(inputImage,sampler,(int2)(i-1,j+1));
    float4 pixel49 = read_imagef(inputImage,sampler,(int2)(i-1,j+0));
    float4 pixel50 = read_imagef(inputImage,sampler,(int2)(i-1,j-1));
    float4 pixel51 = read_imagef(inputImage,sampler,(int2)(i-1,j-2));
    float4 pixel52 = read_imagef(inputImage,sampler,(int2)(i-1,j-3));
    float4 pixel53 = read_imagef(inputImage,sampler,(int2)(i-1,j-4));
    float4 pixel54 = read_imagef(inputImage,sampler,(int2)(i-2,j+4));
    float4 pixel55 = read_imagef(inputImage,sampler,(int2)(i-2,j+3));
    float4 pixel56 = read_imagef(inputImage,sampler,(int2)(i-2,j+2));
    float4 pixel57 = read_imagef(inputImage,sampler,(int2)(i-2,j+1));
    float4 pixel58 = read_imagef(inputImage,sampler,(int2)(i-2,j+0));
    float4 pixel59 = read_imagef(inputImage,sampler,(int2)(i-2,j-1));
    float4 pixel60 = read_imagef(inputImage,sampler,(int2)(i-2,j-2));
    float4 pixel61 = read_imagef(inputImage,sampler,(int2)(i-2,j-3));
    float4 pixel62 = read_imagef(inputImage,sampler,(int2)(i-2,j-4));
    float4 pixel63 = read_imagef(inputImage,sampler,(int2)(i-3,j+4));
    float4 pixel64 = read_imagef(inputImage,sampler,(int2)(i-3,j+3));
    float4 pixel65 = read_imagef(inputImage,sampler,(int2)(i-3,j+2));
    float4 pixel66 = read_imagef(inputImage,sampler,(int2)(i-3,j+1));
    float4 pixel67 = read_imagef(inputImage,sampler,(int2)(i-3,j+0));
    float4 pixel68 = read_imagef(inputImage,sampler,(int2)(i-3,j-1));
    float4 pixel69 = read_imagef(inputImage,sampler,(int2)(i-3,j-2));
    float4 pixel70 = read_imagef(inputImage,sampler,(int2)(i-3,j-3));
    float4 pixel71 = read_imagef(inputImage,sampler,(int2)(i-3,j-4));
    float4 pixel72 = read_imagef(inputImage,sampler,(int2)(i-4,j+4));
    float4 pixel73 = read_imagef(inputImage,sampler,(int2)(i-4,j+3));
    float4 pixel74 = read_imagef(inputImage,sampler,(int2)(i-4,j+2));
    float4 pixel75 = read_imagef(inputImage,sampler,(int2)(i-4,j+1));
    float4 pixel76 = read_imagef(inputImage,sampler,(int2)(i-4,j+0));
    float4 pixel77 = read_imagef(inputImage,sampler,(int2)(i-4,j-1));
    float4 pixel78 = read_imagef(inputImage,sampler,(int2)(i-4,j-2));
    float4 pixel79 = read_imagef(inputImage,sampler,(int2)(i-4,j-3));
    float4 pixel80 = read_imagef(inputImage,sampler,(int2)(i-4,j-4));
    pixel_new += (pixel0)*(float)4.0; accumWeights += 4;
    pixel_new += (pixel1)*(float)8.0; accumWeights += 8;
    pixel_new += (pixel2)*(float)13.0; accumWeights += 13;
    pixel_new += (pixel3)*(float)18.0; accumWeights += 18;
    pixel_new += (pixel4)*(float)20.0; accumWeights += 20;
    pixel_new += (pixel5)*(float)18.0; accumWeights += 18;
    pixel_new += (pixel6)*(float)13.0; accumWeights += 13;
    pixel_new += (pixel7)*(float)8.0; accumWeights += 8;
    pixel_new += (pixel8)*(float)4.0; accumWeights += 4;
    pixel_new += (pixel9)*(float)8.0; accumWeights += 8;
    pixel_new += (pixel10)*(float)16.0; accumWeights += 16;
    pixel_new += (pixel11)*(float)27.0; accumWeights += 27;
    pixel_new += (pixel12)*(float)36.0; accumWeights += 36;
    pixel_new += (pixel13)*(float)40.0; accumWeights += 40;
    pixel_new += (pixel14)*(float)36.0; accumWeights += 36;
    pixel_new += (pixel15)*(float)27.0; accumWeights += 27;
    pixel_new += (pixel16)*(float)16.0; accumWeights += 16;
    pixel_new += (pixel17)*(float)8.0; accumWeights += 8;
    pixel_new += (pixel18)*(float)13.0; accumWeights += 13;
    pixel_new += (pixel19)*(float)27.0; accumWeights += 27;
    pixel_new += (pixel20)*(float)44.0; accumWeights += 44;
    pixel_new += (pixel21)*(float)60.0; accumWeights += 60;
    pixel_new += (pixel22)*(float)67.0; accumWeights += 67;
    pixel_new += (pixel23)*(float)60.0; accumWeights += 60;
    pixel_new += (pixel24)*(float)44.0; accumWeights += 44;
    pixel_new += (pixel25)*(float)27.0; accumWeights += 27;
    pixel_new += (pixel26)*(float)13.0; accumWeights += 13;
    pixel_new += (pixel27)*(float)18.0; accumWeights += 18;
    pixel_new += (pixel28)*(float)36.0; accumWeights += 36;
    pixel_new += (pixel29)*(float)60.0; accumWeights += 60;
    pixel_new += (pixel30)*(float)81.0; accumWeights += 81;
    pixel_new += (pixel31)*(float)90.0; accumWeights += 90;
    pixel_new += (pixel32)*(float)81.0; accumWeights += 81;
    pixel_new += (pixel33)*(float)60.0; accumWeights += 60;
    pixel_new += (pixel34)*(float)36.0; accumWeights += 36;
    pixel_new += (pixel35)*(float)18.0; accumWeights += 18;
    pixel_new += (pixel36)*(float)20.0; accumWeights += 20;
    pixel_new += (pixel37)*(float)40.0; accumWeights += 40;
    pixel_new += (pixel38)*(float)67.0; accumWeights += 67;
    pixel_new += (pixel39)*(float)90.0; accumWeights += 90;
    pixel_new += (pixel40)*(float)100.0; accumWeights += 100;
    pixel_new += (pixel41)*(float)90.0; accumWeights += 90;
    pixel_new += (pixel42)*(float)67.0; accumWeights += 67;
    pixel_new += (pixel43)*(float)40.0; accumWeights += 40;
    pixel_new += (pixel44)*(float)20.0; accumWeights += 20;
    pixel_new += (pixel45)*(float)18.0; accumWeights += 18;
    pixel_new += (pixel46)*(float)36.0; accumWeights += 36;
    pixel_new += (pixel47)*(float)60.0; accumWeights += 60;
    pixel_new += (pixel48)*(float)81.0; accumWeights += 81;
    pixel_new += (pixel49)*(float)90.0; accumWeights += 90;
    pixel_new += (pixel50)*(float)81.0; accumWeights += 81;
    pixel_new += (pixel51)*(float)60.0; accumWeights += 60;
    pixel_new += (pixel52)*(float)36.0; accumWeights += 36;
    pixel_new += (pixel53)*(float)18.0; accumWeights += 18;
    pixel_new += (pixel54)*(float)13.0; accumWeights += 13;
    pixel_new += (pixel55)*(float)27.0; accumWeights += 27;
    pixel_new += (pixel56)*(float)44.0; accumWeights += 44;
    pixel_new += (pixel57)*(float)60.0; accumWeights += 60;
    pixel_new += (pixel58)*(float)67.0; accumWeights += 67;
    pixel_new += (pixel59)*(float)60.0; accumWeights += 60;
    pixel_new += (pixel60)*(float)44.0; accumWeights += 44;
    pixel_new += (pixel61)*(float)27.0; accumWeights += 27;
    pixel_new += (pixel62)*(float)13.0; accumWeights += 13;
    pixel_new += (pixel63)*(float)8.0; accumWeights += 8;
    pixel_new += (pixel64)*(float)16.0; accumWeights += 16;
    pixel_new += (pixel65)*(float)27.0; accumWeights += 27;
    pixel_new += (pixel66)*(float)36.0; accumWeights += 36;
    pixel_new += (pixel67)*(float)40.0; accumWeights += 40;
    pixel_new += (pixel68)*(float)36.0; accumWeights += 36;
    pixel_new += (pixel69)*(float)27.0; accumWeights += 27;
    pixel_new += (pixel70)*(float)16.0; accumWeights += 16;
    pixel_new += (pixel71)*(float)8.0; accumWeights += 8;
    pixel_new += (pixel72)*(float)4.0; accumWeights += 4;
    pixel_new += (pixel73)*(float)8.0; accumWeights += 8;
    pixel_new += (pixel74)*(float)13.0; accumWeights += 13;
    pixel_new += (pixel75)*(float)18.0; accumWeights += 18;
    pixel_new += (pixel76)*(float)20.0; accumWeights += 20;
    pixel_new += (pixel77)*(float)18.0; accumWeights += 18;
    pixel_new += (pixel78)*(float)13.0; accumWeights += 13;
    pixel_new += (pixel79)*(float)8.0; accumWeights += 8;
    pixel_new += (pixel80)*(float)4.0; accumWeights += 4;
    pixel_new = (accumWeights==0)?0:pixel_new/accumWeights; pixel_new.w = 255;
    pixel_new.w = 255;
    write_imagef(outputImage,(int2)(i,j), pixel_new);
};
//Primary input is original surface
__kernel void specialKernel3(read_only image2d_t inputImage, write_only image2d_t outputImage)
{
    const sampler_t sampler=CLK_NORMALIZED_COORDS_FALSE|CLK_ADDRESS_CLAMP_TO_EDGE|CLK_FILTER_NEAREST;
    int i = get_global_id(0);
    int j = get_global_id(1);
    //if (i>=src[0]) return;
    //if (j>=src[1]) return;
    float accumWeights = 0;
    float4 pixel_orig=read_imagef(inputImage,sampler,(int2)(i,j));
    //long4 pixel_orig_long=convert_long4(pixel_orig);
    float4 pixel_new = (float4)(0, 0, 0, 255);
    float4 pixel0 = read_imagef(inputImage,sampler,(int2)(i+5,j+5));
    float4 pixel1 = read_imagef(inputImage,sampler,(int2)(i+5,j+4));
    float4 pixel2 = read_imagef(inputImage,sampler,(int2)(i+5,j+3));
    float4 pixel3 = read_imagef(inputImage,sampler,(int2)(i+5,j+2));
    float4 pixel4 = read_imagef(inputImage,sampler,(int2)(i+5,j+1));
    float4 pixel5 = read_imagef(inputImage,sampler,(int2)(i+5,j+0));
    float4 pixel6 = read_imagef(inputImage,sampler,(int2)(i+5,j-1));
    float4 pixel7 = read_imagef(inputImage,sampler,(int2)(i+5,j-2));
    float4 pixel8 = read_imagef(inputImage,sampler,(int2)(i+5,j-3));
    float4 pixel9 = read_imagef(inputImage,sampler,(int2)(i+5,j-4));
    float4 pixel10 = read_imagef(inputImage,sampler,(int2)(i+5,j-5));
    float4 pixel11 = read_imagef(inputImage,sampler,(int2)(i+4,j+5));
    float4 pixel12 = read_imagef(inputImage,sampler,(int2)(i+4,j+4));
    float4 pixel13 = read_imagef(inputImage,sampler,(int2)(i+4,j+3));
    float4 pixel14 = read_imagef(inputImage,sampler,(int2)(i+4,j+2));
    float4 pixel15 = read_imagef(inputImage,sampler,(int2)(i+4,j+1));
    float4 pixel16 = read_imagef(inputImage,sampler,(int2)(i+4,j+0));
    float4 pixel17 = read_imagef(inputImage,sampler,(int2)(i+4,j-1));
    float4 pixel18 = read_imagef(inputImage,sampler,(int2)(i+4,j-2));
    float4 pixel19 = read_imagef(inputImage,sampler,(int2)(i+4,j-3));
    float4 pixel20 = read_imagef(inputImage,sampler,(int2)(i+4,j-4));
    float4 pixel21 = read_imagef(inputImage,sampler,(int2)(i+4,j-5));
    float4 pixel22 = read_imagef(inputImage,sampler,(int2)(i+3,j+5));
    float4 pixel23 = read_imagef(inputImage,sampler,(int2)(i+3,j+4));
    float4 pixel24 = read_imagef(inputImage,sampler,(int2)(i+3,j+3));
    float4 pixel25 = read_imagef(inputImage,sampler,(int2)(i+3,j+2));
    float4 pixel26 = read_imagef(inputImage,sampler,(int2)(i+3,j+1));
    float4 pixel27 = read_imagef(inputImage,sampler,(int2)(i+3,j+0));
    float4 pixel28 = read_imagef(inputImage,sampler,(int2)(i+3,j-1));
    float4 pixel29 = read_imagef(inputImage,sampler,(int2)(i+3,j-2));
    float4 pixel30 = read_imagef(inputImage,sampler,(int2)(i+3,j-3));
    float4 pixel31 = read_imagef(inputImage,sampler,(int2)(i+3,j-4));
    float4 pixel32 = read_imagef(inputImage,sampler,(int2)(i+3,j-5));
    float4 pixel33 = read_imagef(inputImage,sampler,(int2)(i+2,j+5));
    float4 pixel34 = read_imagef(inputImage,sampler,(int2)(i+2,j+4));
    float4 pixel35 = read_imagef(inputImage,sampler,(int2)(i+2,j+3));
    float4 pixel36 = read_imagef(inputImage,sampler,(int2)(i+2,j+2));
    float4 pixel37 = read_imagef(inputImage,sampler,(int2)(i+2,j+1));
    float4 pixel38 = read_imagef(inputImage,sampler,(int2)(i+2,j+0));
    float4 pixel39 = read_imagef(inputImage,sampler,(int2)(i+2,j-1));
    float4 pixel40 = read_imagef(inputImage,sampler,(int2)(i+2,j-2));
    float4 pixel41 = read_imagef(inputImage,sampler,(int2)(i+2,j-3));
    float4 pixel42 = read_imagef(inputImage,sampler,(int2)(i+2,j-4));
    float4 pixel43 = read_imagef(inputImage,sampler,(int2)(i+2,j-5));
    float4 pixel44 = read_imagef(inputImage,sampler,(int2)(i+1,j+5));
    float4 pixel45 = read_imagef(inputImage,sampler,(int2)(i+1,j+4));
    float4 pixel46 = read_imagef(inputImage,sampler,(int2)(i+1,j+3));
    float4 pixel47 = read_imagef(inputImage,sampler,(int2)(i+1,j+2));
    float4 pixel48 = read_imagef(inputImage,sampler,(int2)(i+1,j+1));
    float4 pixel49 = read_imagef(inputImage,sampler,(int2)(i+1,j+0));
    float4 pixel50 = read_imagef(inputImage,sampler,(int2)(i+1,j-1));
    float4 pixel51 = read_imagef(inputImage,sampler,(int2)(i+1,j-2));
    float4 pixel52 = read_imagef(inputImage,sampler,(int2)(i+1,j-3));
    float4 pixel53 = read_imagef(inputImage,sampler,(int2)(i+1,j-4));
    float4 pixel54 = read_imagef(inputImage,sampler,(int2)(i+1,j-5));
    float4 pixel55 = read_imagef(inputImage,sampler,(int2)(i-0,j+5));
    float4 pixel56 = read_imagef(inputImage,sampler,(int2)(i-0,j+4));
    float4 pixel57 = read_imagef(inputImage,sampler,(int2)(i-0,j+3));
    float4 pixel58 = read_imagef(inputImage,sampler,(int2)(i-0,j+2));
    float4 pixel59 = read_imagef(inputImage,sampler,(int2)(i-0,j+1));
    float4 pixel60 = read_imagef(inputImage,sampler,(int2)(i-0,j+0));
    float4 pixel61 = read_imagef(inputImage,sampler,(int2)(i-0,j-1));
    float4 pixel62 = read_imagef(inputImage,sampler,(int2)(i-0,j-2));
    float4 pixel63 = read_imagef(inputImage,sampler,(int2)(i-0,j-3));
    float4 pixel64 = read_imagef(inputImage,sampler,(int2)(i-0,j-4));
    float4 pixel65 = read_imagef(inputImage,sampler,(int2)(i-0,j-5));
    float4 pixel66 = read_imagef(inputImage,sampler,(int2)(i-1,j+5));
    float4 pixel67 = read_imagef(inputImage,sampler,(int2)(i-1,j+4));
    float4 pixel68 = read_imagef(inputImage,sampler,(int2)(i-1,j+3));
    float4 pixel69 = read_imagef(inputImage,sampler,(int2)(i-1,j+2));
    float4 pixel70 = read_imagef(inputImage,sampler,(int2)(i-1,j+1));
    float4 pixel71 = read_imagef(inputImage,sampler,(int2)(i-1,j+0));
    float4 pixel72 = read_imagef(inputImage,sampler,(int2)(i-1,j-1));
    float4 pixel73 = read_imagef(inputImage,sampler,(int2)(i-1,j-2));
    float4 pixel74 = read_imagef(inputImage,sampler,(int2)(i-1,j-3));
    float4 pixel75 = read_imagef(inputImage,sampler,(int2)(i-1,j-4));
    float4 pixel76 = read_imagef(inputImage,sampler,(int2)(i-1,j-5));
    float4 pixel77 = read_imagef(inputImage,sampler,(int2)(i-2,j+5));
    float4 pixel78 = read_imagef(inputImage,sampler,(int2)(i-2,j+4));
    float4 pixel79 = read_imagef(inputImage,sampler,(int2)(i-2,j+3));
    float4 pixel80 = read_imagef(inputImage,sampler,(int2)(i-2,j+2));
    float4 pixel81 = read_imagef(inputImage,sampler,(int2)(i-2,j+1));
    float4 pixel82 = read_imagef(inputImage,sampler,(int2)(i-2,j+0));
    float4 pixel83 = read_imagef(inputImage,sampler,(int2)(i-2,j-1));
    float4 pixel84 = read_imagef(inputImage,sampler,(int2)(i-2,j-2));
    float4 pixel85 = read_imagef(inputImage,sampler,(int2)(i-2,j-3));
    float4 pixel86 = read_imagef(inputImage,sampler,(int2)(i-2,j-4));
    float4 pixel87 = read_imagef(inputImage,sampler,(int2)(i-2,j-5));
    float4 pixel88 = read_imagef(inputImage,sampler,(int2)(i-3,j+5));
    float4 pixel89 = read_imagef(inputImage,sampler,(int2)(i-3,j+4));
    float4 pixel90 = read_imagef(inputImage,sampler,(int2)(i-3,j+3));
    float4 pixel91 = read_imagef(inputImage,sampler,(int2)(i-3,j+2));
    float4 pixel92 = read_imagef(inputImage,sampler,(int2)(i-3,j+1));
    float4 pixel93 = read_imagef(inputImage,sampler,(int2)(i-3,j+0));
    float4 pixel94 = read_imagef(inputImage,sampler,(int2)(i-3,j-1));
    float4 pixel95 = read_imagef(inputImage,sampler,(int2)(i-3,j-2));
    float4 pixel96 = read_imagef(inputImage,sampler,(int2)(i-3,j-3));
    float4 pixel97 = read_imagef(inputImage,sampler,(int2)(i-3,j-4));
    float4 pixel98 = read_imagef(inputImage,sampler,(int2)(i-3,j-5));
    float4 pixel99 = read_imagef(inputImage,sampler,(int2)(i-4,j+5));
    float4 pixel100 = read_imagef(inputImage,sampler,(int2)(i-4,j+4));
    float4 pixel101 = read_imagef(inputImage,sampler,(int2)(i-4,j+3));
    float4 pixel102 = read_imagef(inputImage,sampler,(int2)(i-4,j+2));
    float4 pixel103 = read_imagef(inputImage,sampler,(int2)(i-4,j+1));
    float4 pixel104 = read_imagef(inputImage,sampler,(int2)(i-4,j+0));
    float4 pixel105 = read_imagef(inputImage,sampler,(int2)(i-4,j-1));
    float4 pixel106 = read_imagef(inputImage,sampler,(int2)(i-4,j-2));
    float4 pixel107 = read_imagef(inputImage,sampler,(int2)(i-4,j-3));
    float4 pixel108 = read_imagef(inputImage,sampler,(int2)(i-4,j-4));
    float4 pixel109 = read_imagef(inputImage,sampler,(int2)(i-4,j-5));
    float4 pixel110 = read_imagef(inputImage,sampler,(int2)(i-5,j+5));
    float4 pixel111 = read_imagef(inputImage,sampler,(int2)(i-5,j+4));
    float4 pixel112 = read_imagef(inputImage,sampler,(int2)(i-5,j+3));
    float4 pixel113 = read_imagef(inputImage,sampler,(int2)(i-5,j+2));
    float4 pixel114 = read_imagef(inputImage,sampler,(int2)(i-5,j+1));
    float4 pixel115 = read_imagef(inputImage,sampler,(int2)(i-5,j+0));
    float4 pixel116 = read_imagef(inputImage,sampler,(int2)(i-5,j-1));
    float4 pixel117 = read_imagef(inputImage,sampler,(int2)(i-5,j-2));
    float4 pixel118 = read_imagef(inputImage,sampler,(int2)(i-5,j-3));
    float4 pixel119 = read_imagef(inputImage,sampler,(int2)(i-5,j-4));
    float4 pixel120 = read_imagef(inputImage,sampler,(int2)(i-5,j-5));
    pixel_new += (pixel0)*(float)8.0; accumWeights += 8;
    pixel_new += (pixel1)*(float)12.0; accumWeights += 12;
    pixel_new += (pixel2)*(float)18.0; accumWeights += 18;
    pixel_new += (pixel3)*(float)23.0; accumWeights += 23;
    pixel_new += (pixel4)*(float)27.0; accumWeights += 27;
    pixel_new += (pixel5)*(float)28.0; accumWeights += 28;
    pixel_new += (pixel6)*(float)27.0; accumWeights += 27;
    pixel_new += (pixel7)*(float)23.0; accumWeights += 23;
    pixel_new += (pixel8)*(float)18.0; accumWeights += 18;
    pixel_new += (pixel9)*(float)12.0; accumWeights += 12;
    pixel_new += (pixel10)*(float)8.0; accumWeights += 8;
    pixel_new += (pixel11)*(float)12.0; accumWeights += 12;
    pixel_new += (pixel12)*(float)20.0; accumWeights += 20;
    pixel_new += (pixel13)*(float)28.0; accumWeights += 28;
    pixel_new += (pixel14)*(float)36.0; accumWeights += 36;
    pixel_new += (pixel15)*(float)42.0; accumWeights += 42;
    pixel_new += (pixel16)*(float)44.0; accumWeights += 44;
    pixel_new += (pixel17)*(float)42.0; accumWeights += 42;
    pixel_new += (pixel18)*(float)36.0; accumWeights += 36;
    pixel_new += (pixel19)*(float)28.0; accumWeights += 28;
    pixel_new += (pixel20)*(float)20.0; accumWeights += 20;
    pixel_new += (pixel21)*(float)12.0; accumWeights += 12;
    pixel_new += (pixel22)*(float)18.0; accumWeights += 18;
    pixel_new += (pixel23)*(float)28.0; accumWeights += 28;
    pixel_new += (pixel24)*(float)40.0; accumWeights += 40;
    pixel_new += (pixel25)*(float)52.0; accumWeights += 52;
    pixel_new += (pixel26)*(float)60.0; accumWeights += 60;
    pixel_new += (pixel27)*(float)63.0; accumWeights += 63;
    pixel_new += (pixel28)*(float)60.0; accumWeights += 60;
    pixel_new += (pixel29)*(float)52.0; accumWeights += 52;
    pixel_new += (pixel30)*(float)40.0; accumWeights += 40;
    pixel_new += (pixel31)*(float)28.0; accumWeights += 28;
    pixel_new += (pixel32)*(float)18.0; accumWeights += 18;
    pixel_new += (pixel33)*(float)23.0; accumWeights += 23;
    pixel_new += (pixel34)*(float)36.0; accumWeights += 36;
    pixel_new += (pixel35)*(float)52.0; accumWeights += 52;
    pixel_new += (pixel36)*(float)67.0; accumWeights += 67;
    pixel_new += (pixel37)*(float)77.0; accumWeights += 77;
    pixel_new += (pixel38)*(float)81.0; accumWeights += 81;
    pixel_new += (pixel39)*(float)77.0; accumWeights += 77;
    pixel_new += (pixel40)*(float)67.0; accumWeights += 67;
    pixel_new += (pixel41)*(float)52.0; accumWeights += 52;
    pixel_new += (pixel42)*(float)36.0; accumWeights += 36;
    pixel_new += (pixel43)*(float)23.0; accumWeights += 23;
    pixel_new += (pixel44)*(float)27.0; accumWeights += 27;
    pixel_new += (pixel45)*(float)42.0; accumWeights += 42;
    pixel_new += (pixel46)*(float)60.0; accumWeights += 60;
    pixel_new += (pixel47)*(float)77.0; accumWeights += 77;
    pixel_new += (pixel48)*(float)90.0; accumWeights += 90;
    pixel_new += (pixel49)*(float)95.0; accumWeights += 95;
    pixel_new += (pixel50)*(float)90.0; accumWeights += 90;
    pixel_new += (pixel51)*(float)77.0; accumWeights += 77;
    pixel_new += (pixel52)*(float)60.0; accumWeights += 60;
    pixel_new += (pixel53)*(float)42.0; accumWeights += 42;
    pixel_new += (pixel54)*(float)27.0; accumWeights += 27;
    pixel_new += (pixel55)*(float)28.0; accumWeights += 28;
    pixel_new += (pixel56)*(float)44.0; accumWeights += 44;
    pixel_new += (pixel57)*(float)63.0; accumWeights += 63;
    pixel_new += (pixel58)*(float)81.0; accumWeights += 81;
    pixel_new += (pixel59)*(float)95.0; accumWeights += 95;
    pixel_new += (pixel60)*(float)100.0; accumWeights += 100;
    pixel_new += (pixel61)*(float)95.0; accumWeights += 95;
    pixel_new += (pixel62)*(float)81.0; accumWeights += 81;
    pixel_new += (pixel63)*(float)63.0; accumWeights += 63;
    pixel_new += (pixel64)*(float)44.0; accumWeights += 44;
    pixel_new += (pixel65)*(float)28.0; accumWeights += 28;
    pixel_new += (pixel66)*(float)27.0; accumWeights += 27;
    pixel_new += (pixel67)*(float)42.0; accumWeights += 42;
    pixel_new += (pixel68)*(float)60.0; accumWeights += 60;
    pixel_new += (pixel69)*(float)77.0; accumWeights += 77;
    pixel_new += (pixel70)*(float)90.0; accumWeights += 90;
    pixel_new += (pixel71)*(float)95.0; accumWeights += 95;
    pixel_new += (pixel72)*(float)90.0; accumWeights += 90;
    pixel_new += (pixel73)*(float)77.0; accumWeights += 77;
    pixel_new += (pixel74)*(float)60.0; accumWeights += 60;
    pixel_new += (pixel75)*(float)42.0; accumWeights += 42;
    pixel_new += (pixel76)*(float)27.0; accumWeights += 27;
    pixel_new += (pixel77)*(float)23.0; accumWeights += 23;
    pixel_new += (pixel78)*(float)36.0; accumWeights += 36;
    pixel_new += (pixel79)*(float)52.0; accumWeights += 52;
    pixel_new += (pixel80)*(float)67.0; accumWeights += 67;
    pixel_new += (pixel81)*(float)77.0; accumWeights += 77;
    pixel_new += (pixel82)*(float)81.0; accumWeights += 81;
    pixel_new += (pixel83)*(float)77.0; accumWeights += 77;
    pixel_new += (pixel84)*(float)67.0; accumWeights += 67;
    pixel_new += (pixel85)*(float)52.0; accumWeights += 52;
    pixel_new += (pixel86)*(float)36.0; accumWeights += 36;
    pixel_new += (pixel87)*(float)23.0; accumWeights += 23;
    pixel_new += (pixel88)*(float)18.0; accumWeights += 18;
    pixel_new += (pixel89)*(float)28.0; accumWeights += 28;
    pixel_new += (pixel90)*(float)40.0; accumWeights += 40;
    pixel_new += (pixel91)*(float)52.0; accumWeights += 52;
    pixel_new += (pixel92)*(float)60.0; accumWeights += 60;
    pixel_new += (pixel93)*(float)63.0; accumWeights += 63;
    pixel_new += (pixel94)*(float)60.0; accumWeights += 60;
    pixel_new += (pixel95)*(float)52.0; accumWeights += 52;
    pixel_new += (pixel96)*(float)40.0; accumWeights += 40;
    pixel_new += (pixel97)*(float)28.0; accumWeights += 28;
    pixel_new += (pixel98)*(float)18.0; accumWeights += 18;
    pixel_new += (pixel99)*(float)12.0; accumWeights += 12;
    pixel_new += (pixel100)*(float)20.0; accumWeights += 20;
    pixel_new += (pixel101)*(float)28.0; accumWeights += 28;
    pixel_new += (pixel102)*(float)36.0; accumWeights += 36;
    pixel_new += (pixel103)*(float)42.0; accumWeights += 42;
    pixel_new += (pixel104)*(float)44.0; accumWeights += 44;
    pixel_new += (pixel105)*(float)42.0; accumWeights += 42;
    pixel_new += (pixel106)*(float)36.0; accumWeights += 36;
    pixel_new += (pixel107)*(float)28.0; accumWeights += 28;
    pixel_new += (pixel108)*(float)20.0; accumWeights += 20;
    pixel_new += (pixel109)*(float)12.0; accumWeights += 12;
    pixel_new += (pixel110)*(float)8.0; accumWeights += 8;
    pixel_new += (pixel111)*(float)12.0; accumWeights += 12;
    pixel_new += (pixel112)*(float)18.0; accumWeights += 18;
    pixel_new += (pixel113)*(float)23.0; accumWeights += 23;
    pixel_new += (pixel114)*(float)27.0; accumWeights += 27;
    pixel_new += (pixel115)*(float)28.0; accumWeights += 28;
    pixel_new += (pixel116)*(float)27.0; accumWeights += 27;
    pixel_new += (pixel117)*(float)23.0; accumWeights += 23;
    pixel_new += (pixel118)*(float)18.0; accumWeights += 18;
    pixel_new += (pixel119)*(float)12.0; accumWeights += 12;
    pixel_new += (pixel120)*(float)8.0; accumWeights += 8;
    pixel_new = (accumWeights==0)?0:pixel_new/accumWeights; pixel_new.w = 255;
    pixel_new.w = 255;
    write_imagef(outputImage,(int2)(i,j), pixel_new);
};
//Secondary input is output of Pass1
//Primary input is output of Pass0
__kernel void specialKernel4(read_only image2d_t inputImage, write_only image2d_t outputImage, read_only image2d_t inputImage2)
{
    const sampler_t sampler=CLK_NORMALIZED_COORDS_FALSE|CLK_ADDRESS_CLAMP_TO_EDGE|CLK_FILTER_NEAREST;
    int i = get_global_id(0);
    int j = get_global_id(1);
    //if (i>=src[0]) return;
    //if (j>=src[1]) return;
    float accumWeights = 0;
    float4 pixel_orig=read_imagef(inputImage,sampler,(int2)(i,j));
    //long4 pixel_orig_long=convert_long4(pixel_orig);
    float4 pixel_new = (float4)(0, 0, 0, 255);
    float4 pixel0 = read_imagef(inputImage,sampler,(int2)(i-0,j+0));
    pixel_new += (pixel0)*(float)1.0; accumWeights += 1;
    float4 pixel_2ndary=read_imagef(inputImage2,sampler,(int2)(i,j));
    pixel_new = pixel_new - pixel_2ndary;
    pixel_new.w = 255;
    write_imagef(outputImage,(int2)(i,j), pixel_new);
};
//Secondary input is output of Pass2
//Primary input is output of Pass1
__kernel void specialKernel5(read_only image2d_t inputImage, write_only image2d_t outputImage, read_only image2d_t inputImage2)
{
    const sampler_t sampler=CLK_NORMALIZED_COORDS_FALSE|CLK_ADDRESS_CLAMP_TO_EDGE|CLK_FILTER_NEAREST;
    int i = get_global_id(0);
    int j = get_global_id(1);
    //if (i>=src[0]) return;
    //if (j>=src[1]) return;
    float accumWeights = 0;
    float4 pixel_orig=read_imagef(inputImage,sampler,(int2)(i,j));
    //long4 pixel_orig_long=convert_long4(pixel_orig);
    float4 pixel_new = (float4)(0, 0, 0, 255);
    float4 pixel0 = read_imagef(inputImage,sampler,(int2)(i-0,j+0));
    pixel_new += (pixel0)*(float)1.0; accumWeights += 1;
    float4 pixel_2ndary=read_imagef(inputImage2,sampler,(int2)(i,j));
    pixel_new = pixel_new - pixel_2ndary;
    pixel_new.w = 255;
    write_imagef(outputImage,(int2)(i,j), pixel_new);
};
//Secondary input is output of Pass3
//Primary input is output of Pass2
__kernel void specialKernel6(read_only image2d_t inputImage, write_only image2d_t outputImage, read_only image2d_t inputImage2)
{
    const sampler_t sampler=CLK_NORMALIZED_COORDS_FALSE|CLK_ADDRESS_CLAMP_TO_EDGE|CLK_FILTER_NEAREST;
    int i = get_global_id(0);
    int j = get_global_id(1);
    //if (i>=src[0]) return;
    //if (j>=src[1]) return;
    float accumWeights = 0;
    float4 pixel_orig=read_imagef(inputImage,sampler,(int2)(i,j));
    //long4 pixel_orig_long=convert_long4(pixel_orig);
    float4 pixel_new = (float4)(0, 0, 0, 255);
    float4 pixel0 = read_imagef(inputImage,sampler,(int2)(i-0,j+0));
    pixel_new += (pixel0)*(float)1.0; accumWeights += 1;
    float4 pixel_2ndary=read_imagef(inputImage2,sampler,(int2)(i,j));
    pixel_new = pixel_new - pixel_2ndary;
    pixel_new.w = 255;
    write_imagef(outputImage,(int2)(i,j), pixel_new);
};
//Secondary input is output of Pass5
//Primary input is output of Pass4
__kernel void specialKernel7(read_only image2d_t inputImage, write_only image2d_t outputImage, read_only image2d_t inputImage2)
{
    const sampler_t sampler=CLK_NORMALIZED_COORDS_FALSE|CLK_ADDRESS_CLAMP_TO_EDGE|CLK_FILTER_NEAREST;
    int i = get_global_id(0);
    int j = get_global_id(1);
    //if (i>=src[0]) return;
    //if (j>=src[1]) return;
    float accumWeights = 0;
    float4 pixel_orig=read_imagef(inputImage,sampler,(int2)(i,j));
    //long4 pixel_orig_long=convert_long4(pixel_orig);
    float4 pixel_new = (float4)(0, 0, 0, 255);
    float4 pixel0 = read_imagef(inputImage,sampler,(int2)(i-0,j+0));
    pixel_new += (pixel0)*(float)1.0; accumWeights += 1;
    float4 pixel_2ndary=read_imagef(inputImage2,sampler,(int2)(i,j));
    pixel_new += pixel_2ndary;
    pixel_new.w = 255;
    write_imagef(outputImage,(int2)(i,j), pixel_new);
};
//Secondary input is output of Pass7
//Primary input is output of Pass6
__kernel void specialKernel8(read_only image2d_t inputImage, write_only image2d_t outputImage, read_only image2d_t inputImage2)
{
    const sampler_t sampler=CLK_NORMALIZED_COORDS_FALSE|CLK_ADDRESS_CLAMP_TO_EDGE|CLK_FILTER_NEAREST;
    int i = get_global_id(0);
    int j = get_global_id(1);
    //if (i>=src[0]) return;
    //if (j>=src[1]) return;
    float accumWeights = 0;
    float4 pixel_orig=read_imagef(inputImage,sampler,(int2)(i,j));
    //long4 pixel_orig_long=convert_long4(pixel_orig);
    float4 pixel_new = (float4)(0, 0, 0, 255);
    float4 pixel0 = read_imagef(inputImage,sampler,(int2)(i-0,j+0));
    pixel_new += (pixel0)*(float)1.0; accumWeights += 1;
    float4 pixel_2ndary=read_imagef(inputImage2,sampler,(int2)(i,j));
    pixel_new += pixel_2ndary;
    pixel_new.w = 255;
    write_imagef(outputImage,(int2)(i,j), pixel_new);
};
//Secondary input is output of Pass8
//Primary input is output of Pass3
__kernel void specialKernel9(read_only image2d_t inputImage, write_only image2d_t outputImage, read_only image2d_t inputImage2)
{
    const sampler_t sampler=CLK_NORMALIZED_COORDS_FALSE|CLK_ADDRESS_CLAMP_TO_EDGE|CLK_FILTER_NEAREST;
    int i = get_global_id(0);
    int j = get_global_id(1);
    //if (i>=src[0]) return;
    //if (j>=src[1]) return;
    float accumWeights = 0;
    float4 pixel_orig=read_imagef(inputImage,sampler,(int2)(i,j));
    //long4 pixel_orig_long=convert_long4(pixel_orig);
    float4 pixel_new = (float4)(0, 0, 0, 255);
    float4 pixel0 = read_imagef(inputImage,sampler,(int2)(i-0,j+0));
    pixel_new += (pixel0)*(float)1.0; accumWeights += 1;
    float4 pixel_2ndary=read_imagef(inputImage2,sampler,(int2)(i,j));
    pixel_new += pixel_2ndary;
    pixel_new = fabs(pixel_new);
    if (pixel_new.x>255) pixel_new.x = 255;
    if (pixel_new.y>255) pixel_new.y = 255;
    if (pixel_new.z>255) pixel_new.z = 255;
    pixel_new.w = 255;
    write_imagef(outputImage,(int2)(i,j), pixel_new);
};


// buildOptions=
// RUN: %occ-cli %s --cl-options="-I%cwd -I%S " %cfg_path --cl-device=%cl_device 2>&1
