// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global int8 *source, __global int *dest) {
  if (get_global_id(0) != 0)
    return;
  // int8 src1 /*, src2*/;
  int3 tmp;
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[0].S1;
  vstore3(tmp, 0, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[0].SB;
  vstore3(tmp, 1, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[1].S3;
  vstore3(tmp, 2, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[1].sf;
  vstore3(tmp, 3, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[2].S1;
  vstore3(tmp, 4, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[2].s9;
  vstore3(tmp, 5, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[3].s3;
  vstore3(tmp, 6, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[3].S9;
  vstore3(tmp, 7, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[4].S6;
  vstore3(tmp, 8, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[4].s8;
  vstore3(tmp, 9, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[5].s0;
  vstore3(tmp, 10, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[5].sF;
  tmp.s2 = ((__global int16 *)source)[5].Se;
  vstore3(tmp, 11, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[6].S3;
  tmp.s1 = ((__global int16 *)source)[6].S1;
  vstore3(tmp, 12, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[6].SF;
  tmp.s1 = ((__global int16 *)source)[6].SA;
  vstore3(tmp, 13, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[7].S5;
  tmp.S2 = ((__global int16 *)source)[7].S4;
  vstore3(tmp, 14, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[7].sE;
  tmp.S1 = ((__global int16 *)source)[7].sb;
  vstore3(tmp, 15, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[8].s2;
  tmp.S1 = ((__global int16 *)source)[8].s1;
  vstore3(tmp, 16, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[8].sF;
  tmp.S1 = ((__global int16 *)source)[8].sE;
  vstore3(tmp, 17, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[9].S7;
  tmp.s0 = ((__global int16 *)source)[9].S4;
  vstore3(tmp, 18, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[9].sf;
  tmp.s1 = ((__global int16 *)source)[9].sE;
  vstore3(tmp, 19, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[10].s4;
  tmp.S0 = ((__global int16 *)source)[10].S4;
  vstore3(tmp, 20, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[10].Se;
  tmp.S2 = ((__global int16 *)source)[10].SC;
  vstore3(tmp, 21, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[11].s6;
  tmp.S2 = ((__global int16 *)source)[11].S4;
  vstore3(tmp, 22, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[11].sC;
  tmp.s0 = ((__global int16 *)source)[11].sa;
  vstore3(tmp, 23, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[12].s7;
  tmp.S0 = ((__global int16 *)source)[12].s3;
  vstore3(tmp, 24, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[12].S9;
  tmp.S0 = ((__global int16 *)source)[12].SA;
  vstore3(tmp, 25, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[13].S3;
  tmp.s2 = ((__global int16 *)source)[13].S7;
  vstore3(tmp, 26, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[13].sA;
  tmp.S1 = ((__global int16 *)source)[13].Sd;
  vstore3(tmp, 27, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[14].S4;
  tmp.s0 = ((__global int16 *)source)[14].s6;
  vstore3(tmp, 28, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[14].se;
  tmp.s0 = ((__global int16 *)source)[14].se;
  vstore3(tmp, 29, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[15].s1;
  tmp.S0 = ((__global int16 *)source)[15].s3;
  vstore3(tmp, 30, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[15].SB;
  tmp.s2 = ((__global int16 *)source)[15].sF;
  vstore3(tmp, 31, (__global int *)dest);
}
