// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global short8 *source, __global short *dest) {
  if (get_global_id(0) != 0)
    return;
  // short8 src1 /*, src2*/;
  short3 tmp;
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[0].S2;
  vstore3(tmp, 0, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[0].SA;
  vstore3(tmp, 1, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[1].s0;
  vstore3(tmp, 2, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s2 = ((__global short16 *)source)[1].Sc;
  vstore3(tmp, 3, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[2].S6;
  vstore3(tmp, 4, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[2].Sa;
  vstore3(tmp, 5, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[3].s3;
  vstore3(tmp, 6, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[3].sD;
  vstore3(tmp, 7, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s2 = ((__global short16 *)source)[4].S3;
  vstore3(tmp, 8, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[4].sf;
  vstore3(tmp, 9, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[5].S4;
  vstore3(tmp, 10, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[5].Sa;
  tmp.s1 = ((__global short16 *)source)[5].SE;
  vstore3(tmp, 11, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[6].S6;
  tmp.S1 = ((__global short16 *)source)[6].s1;
  vstore3(tmp, 12, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[6].S9;
  tmp.S2 = ((__global short16 *)source)[6].sd;
  vstore3(tmp, 13, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[7].s4;
  tmp.S1 = ((__global short16 *)source)[7].s3;
  vstore3(tmp, 14, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s2 = ((__global short16 *)source)[7].sa;
  tmp.S0 = ((__global short16 *)source)[7].sc;
  vstore3(tmp, 15, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[8].s2;
  tmp.S2 = ((__global short16 *)source)[8].S1;
  vstore3(tmp, 16, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[8].SC;
  tmp.S0 = ((__global short16 *)source)[8].sa;
  vstore3(tmp, 17, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[9].S7;
  tmp.S2 = ((__global short16 *)source)[9].S5;
  vstore3(tmp, 18, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[9].S9;
  tmp.s1 = ((__global short16 *)source)[9].SB;
  vstore3(tmp, 19, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[10].S0;
  tmp.s2 = ((__global short16 *)source)[10].s5;
  vstore3(tmp, 20, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[10].sA;
  tmp.s2 = ((__global short16 *)source)[10].SF;
  vstore3(tmp, 21, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[11].s3;
  tmp.S0 = ((__global short16 *)source)[11].s7;
  vstore3(tmp, 22, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s2 = ((__global short16 *)source)[11].s9;
  tmp.S0 = ((__global short16 *)source)[11].Se;
  vstore3(tmp, 23, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[12].S6;
  tmp.S0 = ((__global short16 *)source)[12].s1;
  vstore3(tmp, 24, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[12].s9;
  tmp.S1 = ((__global short16 *)source)[12].S8;
  vstore3(tmp, 25, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[13].s6;
  tmp.S2 = ((__global short16 *)source)[13].S0;
  vstore3(tmp, 26, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[13].SB;
  tmp.S0 = ((__global short16 *)source)[13].sE;
  vstore3(tmp, 27, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s2 = ((__global short16 *)source)[14].S0;
  tmp.S1 = ((__global short16 *)source)[14].S7;
  vstore3(tmp, 28, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[14].sF;
  tmp.s0 = ((__global short16 *)source)[14].sB;
  vstore3(tmp, 29, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[15].s7;
  tmp.S1 = ((__global short16 *)source)[15].S6;
  vstore3(tmp, 30, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[15].S8;
  tmp.s0 = ((__global short16 *)source)[15].Sc;
  vstore3(tmp, 31, (__global short *)dest);
}
