// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global int2 *source, __global int *dest) {
  if (get_global_id(0) != 0)
    return;
  // int2 src1 /*, src2*/;
  int3 tmp;
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[0].S1;
  vstore3(tmp, 0, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[0].S2;
  vstore3(tmp, 1, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[0].s4;
  vstore3(tmp, 2, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[0].s7;
  vstore3(tmp, 3, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[0].s9;
  vstore3(tmp, 4, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[0].sA;
  vstore3(tmp, 5, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[0].sc;
  vstore3(tmp, 6, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[0].se;
  vstore3(tmp, 7, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[1].S0;
  vstore3(tmp, 8, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[1].S3;
  vstore3(tmp, 9, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[1].s5;
  vstore3(tmp, 10, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[1].S6;
  vstore3(tmp, 11, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[1].s8;
  vstore3(tmp, 12, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[1].sb;
  vstore3(tmp, 13, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[1].Sc;
  vstore3(tmp, 14, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[1].sf;
  vstore3(tmp, 15, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[2].S1;
  tmp.S2 = ((__global int16 *)source)[2].s0;
  vstore3(tmp, 16, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[2].s2;
  tmp.s0 = ((__global int16 *)source)[2].s2;
  vstore3(tmp, 17, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[2].S5;
  tmp.S0 = ((__global int16 *)source)[2].s5;
  vstore3(tmp, 18, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[2].S7;
  tmp.S2 = ((__global int16 *)source)[2].S6;
  vstore3(tmp, 19, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[2].s9;
  tmp.S2 = ((__global int16 *)source)[2].s8;
  vstore3(tmp, 20, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[2].sb;
  tmp.S2 = ((__global int16 *)source)[2].SA;
  vstore3(tmp, 21, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[2].sD;
  tmp.s2 = ((__global int16 *)source)[2].SC;
  vstore3(tmp, 22, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[2].sf;
  tmp.S2 = ((__global int16 *)source)[2].SF;
  vstore3(tmp, 23, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[3].S0;
  tmp.s1 = ((__global int16 *)source)[3].S1;
  vstore3(tmp, 24, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[3].s2;
  tmp.s1 = ((__global int16 *)source)[3].S2;
  vstore3(tmp, 25, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[3].S4;
  tmp.s0 = ((__global int16 *)source)[3].s5;
  vstore3(tmp, 26, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[3].s6;
  tmp.S0 = ((__global int16 *)source)[3].s7;
  vstore3(tmp, 27, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[3].S9;
  tmp.s1 = ((__global int16 *)source)[3].S9;
  vstore3(tmp, 28, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[3].Sa;
  tmp.S1 = ((__global int16 *)source)[3].SA;
  vstore3(tmp, 29, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[3].sd;
  tmp.S0 = ((__global int16 *)source)[3].sc;
  vstore3(tmp, 30, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[3].sf;
  tmp.S2 = ((__global int16 *)source)[3].sF;
  vstore3(tmp, 31, (__global int *)dest);
}
