// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
double16 shuffle_fn(double16 source);
double16 shuffle_fn(double16 source) { return source; }

__kernel void sample_test(__global double16 *source, __global double4 *dest) {
  if (get_global_id(0) != 0)
    return;
  // double16 src1 /*, src2*/;
  double4 tmp;
  tmp = (double4)((double)0);
  tmp.S3 = shuffle_fn(source[0]).s8;
  dest[0] = tmp;
  tmp = (double4)((double)0);
  tmp.S2 = shuffle_fn(source[1]).s5;
  dest[1] = tmp;
  tmp = (double4)((double)0);
  tmp.S3 = shuffle_fn(source[2]).s0;
  dest[2] = tmp;
  tmp = (double4)((double)0);
  tmp.S3 = shuffle_fn(source[3]).S1;
  dest[3] = tmp;
  tmp = (double4)((double)0);
  tmp.S2 = shuffle_fn(source[4]).s4;
  dest[4] = tmp;
  tmp = (double4)((double)0);
  tmp.s0 = shuffle_fn(source[5]).SC;
  dest[5] = tmp;
  tmp = (double4)((double)0);
  tmp.S1 = shuffle_fn(source[6]).s3;
  dest[6] = tmp;
  tmp = (double4)((double)0);
  tmp.S2 = shuffle_fn(source[7]).S7;
  dest[7] = tmp;
  tmp = (double4)((double)0);
  tmp.S21 = shuffle_fn(source[8]).s66;
  dest[8] = tmp;
  tmp = (double4)((double)0);
  tmp.S10 = shuffle_fn(source[9]).S32;
  dest[9] = tmp;
  tmp = (double4)((double)0);
  tmp.S20 = shuffle_fn(source[10]).S5C;
  dest[10] = tmp;
  tmp = (double4)((double)0);
  tmp.S03 = shuffle_fn(source[11]).s1B;
  dest[11] = tmp;
  tmp = (double4)((double)0);
  tmp.s31 = shuffle_fn(source[12]).sE9;
  dest[12] = tmp;
  tmp = (double4)((double)0);
  tmp.S32 = shuffle_fn(source[13]).S4d;
  dest[13] = tmp;
  tmp = (double4)((double)0);
  tmp.s03 = shuffle_fn(source[14]).sC7;
  dest[14] = tmp;
  tmp = (double4)((double)0);
  tmp.s23 = shuffle_fn(source[15]).S7f;
  dest[15] = tmp;
  tmp = (double4)((double)0);
  tmp.S12 = shuffle_fn(source[16]).SE8;
  dest[16] = tmp;
  tmp = (double4)((double)0);
  tmp.S02 = shuffle_fn(source[17]).SfD;
  dest[17] = tmp;
  tmp = (double4)((double)0);
  tmp.s30 = shuffle_fn(source[18]).S62;
  dest[18] = tmp;
  tmp = (double4)((double)0);
  tmp.S31 = shuffle_fn(source[19]).S97;
  dest[19] = tmp;
  tmp = (double4)((double)0);
  tmp.S13 = shuffle_fn(source[20]).S4b;
  dest[20] = tmp;
  tmp = (double4)((double)0);
  tmp.s32 = shuffle_fn(source[21]).S64;
  dest[21] = tmp;
  tmp = (double4)((double)0);
  tmp.S21 = shuffle_fn(source[22]).SA1;
  dest[22] = tmp;
  tmp = (double4)((double)0);
  tmp.S21 = shuffle_fn(source[23]).S05;
  dest[23] = tmp;
  tmp = (double4)((double)0);
  tmp.S1302 = shuffle_fn(source[24]).S9a05;
  dest[24] = tmp;
  tmp = (double4)((double)0);
  tmp.s3201 = shuffle_fn(source[25]).S2a6C;
  dest[25] = tmp;
  tmp = (double4)((double)0);
  tmp.S0312 = shuffle_fn(source[26]).SAd34;
  dest[26] = tmp;
  tmp = (double4)((double)0);
  tmp.S3210 = shuffle_fn(source[27]).S6F7B;
  dest[27] = tmp;
  tmp = (double4)((double)0);
  tmp.S3210 = shuffle_fn(source[28]).S7A14;
  dest[28] = tmp;
  tmp = (double4)((double)0);
  tmp.s3210 = shuffle_fn(source[29]).s4C7F;
  dest[29] = tmp;
  tmp = (double4)((double)0);
  tmp.s2031 = shuffle_fn(source[30]).sEEcb;
  dest[30] = tmp;
  tmp = (double4)((double)0);
  tmp.s0123 = shuffle_fn(source[31]).s7f33;
  dest[31] = tmp;
}
