// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
double3 shuffle_fn(double3 source);
double3 shuffle_fn(double3 source) { return source; }

__kernel void sample_test(__global double *source, __global double8 *dest) {
  if (get_global_id(0) != 0)
    return;
  // double3 src1 /*, src2*/;
  double8 tmp;
  tmp = (double8)((double)0);
  tmp.S5 = shuffle_fn(vload3(0, source)).S0;
  dest[0] = tmp;
  tmp = (double8)((double)0);
  tmp.s6 = shuffle_fn(vload3(1, source)).S0;
  dest[1] = tmp;
  tmp = (double8)((double)0);
  tmp.s1 = shuffle_fn(vload3(2, source)).s1;
  dest[2] = tmp;
  tmp = (double8)((double)0);
  tmp.S0 = shuffle_fn(vload3(3, source)).s0;
  dest[3] = tmp;
  tmp = (double8)((double)0);
  tmp.S7 = shuffle_fn(vload3(4, source)).s2;
  dest[4] = tmp;
  tmp = (double8)((double)0);
  tmp.s2 = shuffle_fn(vload3(5, source)).S1;
  dest[5] = tmp;
  tmp = (double8)((double)0);
  tmp.S1 = shuffle_fn(vload3(6, source)).S0;
  dest[6] = tmp;
  tmp = (double8)((double)0);
  tmp.s7 = shuffle_fn(vload3(7, source)).s1;
  dest[7] = tmp;
  tmp = (double8)((double)0);
  tmp.s3 = shuffle_fn(vload3(8, source)).s0;
  dest[8] = tmp;
  tmp = (double8)((double)0);
  tmp.S0 = shuffle_fn(vload3(9, source)).s1;
  dest[9] = tmp;
  tmp = (double8)((double)0);
  tmp.S1 = shuffle_fn(vload3(10, source)).s0;
  dest[10] = tmp;
  tmp = (double8)((double)0);
  tmp.s03 = shuffle_fn(vload3(11, source)).S20;
  dest[11] = tmp;
  tmp = (double8)((double)0);
  tmp.S21 = shuffle_fn(vload3(12, source)).s00;
  dest[12] = tmp;
  tmp = (double8)((double)0);
  tmp.s31 = shuffle_fn(vload3(13, source)).S10;
  dest[13] = tmp;
  tmp = (double8)((double)0);
  tmp.s01 = shuffle_fn(vload3(14, source)).S22;
  dest[14] = tmp;
  tmp = (double8)((double)0);
  tmp.s61 = shuffle_fn(vload3(15, source)).s02;
  dest[15] = tmp;
  tmp = (double8)((double)0);
  tmp.S76 = shuffle_fn(vload3(16, source)).s20;
  dest[16] = tmp;
  tmp = (double8)((double)0);
  tmp.s64 = shuffle_fn(vload3(17, source)).S10;
  dest[17] = tmp;
  tmp = (double8)((double)0);
  tmp.s21 = shuffle_fn(vload3(18, source)).s22;
  dest[18] = tmp;
  tmp = (double8)((double)0);
  tmp.S46 = shuffle_fn(vload3(19, source)).S12;
  dest[19] = tmp;
  tmp = (double8)((double)0);
  tmp.s05 = shuffle_fn(vload3(20, source)).s22;
  dest[20] = tmp;
  tmp = (double8)((double)0);
  tmp.s25 = shuffle_fn(vload3(21, source)).S12;
  dest[21] = tmp;
  tmp = (double8)((double)0);
  tmp.s35 = shuffle_fn(vload3(22, source)).S21;
  dest[22] = tmp;
  tmp = (double8)((double)0);
  tmp.s15 = shuffle_fn(vload3(23, source)).S01;
  dest[23] = tmp;
  tmp = (double8)((double)0);
  tmp.S27 = shuffle_fn(vload3(24, source)).s21;
  dest[24] = tmp;
  tmp = (double8)((double)0);
  tmp.S26 = shuffle_fn(vload3(25, source)).S02;
  dest[25] = tmp;
  tmp = (double8)((double)0);
  tmp.s34 = shuffle_fn(vload3(26, source)).S22;
  dest[26] = tmp;
  tmp = (double8)((double)0);
  tmp.S10 = shuffle_fn(vload3(27, source)).S00;
  dest[27] = tmp;
  tmp = (double8)((double)0);
  tmp.S73 = shuffle_fn(vload3(28, source)).s02;
  dest[28] = tmp;
  tmp = (double8)((double)0);
  tmp.S74 = shuffle_fn(vload3(29, source)).s21;
  dest[29] = tmp;
  tmp = (double8)((double)0);
  tmp.s74 = shuffle_fn(vload3(30, source)).S20;
  dest[30] = tmp;
  tmp = (double8)((double)0);
  tmp.S73 = shuffle_fn(vload3(31, source)).s02;
  dest[31] = tmp;
}
