// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global ushort16 *source, __global ushort *dest) {
  if (get_global_id(0) != 0)
    return;
  // ushort16 src1 /*, src2*/;
  ushort3 tmp;
  tmp = (ushort)((ushort)0);
  tmp.S0 = ((__global ushort16 *)source)[0].S1;
  vstore3(tmp, 0, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[1].S0;
  vstore3(tmp, 1, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[2].Sb;
  vstore3(tmp, 2, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s0 = ((__global ushort16 *)source)[3].sd;
  vstore3(tmp, 3, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S0 = ((__global ushort16 *)source)[4].SA;
  vstore3(tmp, 4, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S0 = ((__global ushort16 *)source)[5].se;
  vstore3(tmp, 5, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[6].s5;
  vstore3(tmp, 6, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[7].S2;
  vstore3(tmp, 7, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[8].s8;
  vstore3(tmp, 8, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[9].S7;
  vstore3(tmp, 9, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S2 = ((__global ushort16 *)source)[10].S5;
  vstore3(tmp, 10, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[11].sc;
  tmp.s0 = ((__global ushort16 *)source)[11].sF;
  vstore3(tmp, 11, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S0 = ((__global ushort16 *)source)[12].Sd;
  tmp.s1 = ((__global ushort16 *)source)[12].s6;
  vstore3(tmp, 12, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[13].sE;
  tmp.S1 = ((__global ushort16 *)source)[13].S7;
  vstore3(tmp, 13, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S0 = ((__global ushort16 *)source)[14].s0;
  tmp.S1 = ((__global ushort16 *)source)[14].sd;
  vstore3(tmp, 14, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[15].S7;
  tmp.s2 = ((__global ushort16 *)source)[15].s2;
  vstore3(tmp, 15, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[16].sd;
  tmp.S0 = ((__global ushort16 *)source)[16].S3;
  vstore3(tmp, 16, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[17].S2;
  tmp.s0 = ((__global ushort16 *)source)[17].s2;
  vstore3(tmp, 17, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[18].s9;
  tmp.s1 = ((__global ushort16 *)source)[18].S5;
  vstore3(tmp, 18, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S2 = ((__global ushort16 *)source)[19].Sa;
  tmp.S1 = ((__global ushort16 *)source)[19].S4;
  vstore3(tmp, 19, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S2 = ((__global ushort16 *)source)[20].s7;
  tmp.S1 = ((__global ushort16 *)source)[20].S4;
  vstore3(tmp, 20, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[21].s5;
  tmp.S0 = ((__global ushort16 *)source)[21].sC;
  vstore3(tmp, 21, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[22].s8;
  tmp.s2 = ((__global ushort16 *)source)[22].sC;
  vstore3(tmp, 22, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S2 = ((__global ushort16 *)source)[23].S2;
  tmp.S1 = ((__global ushort16 *)source)[23].sb;
  vstore3(tmp, 23, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S2 = ((__global ushort16 *)source)[24].s6;
  tmp.s1 = ((__global ushort16 *)source)[24].S8;
  vstore3(tmp, 24, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[25].s1;
  tmp.S0 = ((__global ushort16 *)source)[25].S8;
  vstore3(tmp, 25, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[26].S7;
  tmp.s2 = ((__global ushort16 *)source)[26].S2;
  vstore3(tmp, 26, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[27].sd;
  tmp.s0 = ((__global ushort16 *)source)[27].SF;
  vstore3(tmp, 27, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s0 = ((__global ushort16 *)source)[28].S4;
  tmp.S2 = ((__global ushort16 *)source)[28].S4;
  vstore3(tmp, 28, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S0 = ((__global ushort16 *)source)[29].s1;
  tmp.s2 = ((__global ushort16 *)source)[29].S1;
  vstore3(tmp, 29, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[30].S5;
  tmp.S0 = ((__global ushort16 *)source)[30].s3;
  vstore3(tmp, 30, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s0 = ((__global ushort16 *)source)[31].s7;
  tmp.s1 = ((__global ushort16 *)source)[31].s3;
  vstore3(tmp, 31, (__global ushort *)dest);
}
