// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global uchar4 *source, __global uchar *dest) {
  if (get_global_id(0) != 0)
    return;
  // uchar4 src1 /*, src2*/;
  uchar3 tmp;
  tmp = (uchar)((uchar)0);
  tmp.S0 = ((__global uchar16 *)source)[0].S0;
  vstore3(tmp, 0, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s1 = ((__global uchar16 *)source)[0].s7;
  vstore3(tmp, 1, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s2 = ((__global uchar16 *)source)[0].sB;
  vstore3(tmp, 2, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S2 = ((__global uchar16 *)source)[0].sD;
  vstore3(tmp, 3, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S2 = ((__global uchar16 *)source)[1].s0;
  vstore3(tmp, 4, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s2 = ((__global uchar16 *)source)[1].S5;
  vstore3(tmp, 5, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S1 = ((__global uchar16 *)source)[1].SB;
  vstore3(tmp, 6, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s1 = ((__global uchar16 *)source)[1].sD;
  vstore3(tmp, 7, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s1 = ((__global uchar16 *)source)[2].s1;
  vstore3(tmp, 8, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S2 = ((__global uchar16 *)source)[2].s4;
  vstore3(tmp, 9, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S2 = ((__global uchar16 *)source)[2].SB;
  vstore3(tmp, 10, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S0 = ((__global uchar16 *)source)[2].Sd;
  tmp.s1 = ((__global uchar16 *)source)[2].Sc;
  vstore3(tmp, 11, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S0 = ((__global uchar16 *)source)[3].S1;
  tmp.S1 = ((__global uchar16 *)source)[3].s3;
  vstore3(tmp, 12, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s1 = ((__global uchar16 *)source)[3].S6;
  tmp.s0 = ((__global uchar16 *)source)[3].s7;
  vstore3(tmp, 13, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[3].S8;
  tmp.S2 = ((__global uchar16 *)source)[3].SB;
  vstore3(tmp, 14, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S0 = ((__global uchar16 *)source)[3].sD;
  tmp.S1 = ((__global uchar16 *)source)[3].sd;
  vstore3(tmp, 15, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S1 = ((__global uchar16 *)source)[4].s1;
  tmp.S0 = ((__global uchar16 *)source)[4].S0;
  vstore3(tmp, 16, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S2 = ((__global uchar16 *)source)[4].S6;
  tmp.s0 = ((__global uchar16 *)source)[4].S4;
  vstore3(tmp, 17, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S1 = ((__global uchar16 *)source)[4].s8;
  tmp.s0 = ((__global uchar16 *)source)[4].s8;
  vstore3(tmp, 18, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s2 = ((__global uchar16 *)source)[4].SC;
  tmp.S0 = ((__global uchar16 *)source)[4].SE;
  vstore3(tmp, 19, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s2 = ((__global uchar16 *)source)[5].s3;
  tmp.s0 = ((__global uchar16 *)source)[5].s2;
  vstore3(tmp, 20, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S2 = ((__global uchar16 *)source)[5].S5;
  tmp.s0 = ((__global uchar16 *)source)[5].S7;
  vstore3(tmp, 21, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S0 = ((__global uchar16 *)source)[5].Sb;
  tmp.s2 = ((__global uchar16 *)source)[5].SA;
  vstore3(tmp, 22, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S2 = ((__global uchar16 *)source)[5].se;
  tmp.s0 = ((__global uchar16 *)source)[5].SC;
  vstore3(tmp, 23, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[6].S2;
  tmp.s1 = ((__global uchar16 *)source)[6].s1;
  vstore3(tmp, 24, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s1 = ((__global uchar16 *)source)[6].S4;
  tmp.S2 = ((__global uchar16 *)source)[6].S4;
  vstore3(tmp, 25, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S1 = ((__global uchar16 *)source)[6].sa;
  tmp.S0 = ((__global uchar16 *)source)[6].S8;
  vstore3(tmp, 26, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[6].SF;
  tmp.s1 = ((__global uchar16 *)source)[6].sd;
  vstore3(tmp, 27, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[7].S0;
  tmp.s2 = ((__global uchar16 *)source)[7].S0;
  vstore3(tmp, 28, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[7].S5;
  tmp.S1 = ((__global uchar16 *)source)[7].s4;
  vstore3(tmp, 29, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S1 = ((__global uchar16 *)source)[7].sA;
  tmp.s0 = ((__global uchar16 *)source)[7].s8;
  vstore3(tmp, 30, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S2 = ((__global uchar16 *)source)[7].se;
  tmp.S1 = ((__global uchar16 *)source)[7].SC;
  vstore3(tmp, 31, (__global uchar *)dest);
}
