// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global ulong16 *source, __global ulong *dest) {
  if (get_global_id(0) != 0)
    return;
  // ulong16 src1 /*, src2*/;
  ulong3 tmp;
  tmp = (ulong)((ulong)0);
  tmp.S2 = ((__global ulong16 *)source)[0].sD;
  vstore3(tmp, 0, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s2 = ((__global ulong16 *)source)[1].Sc;
  vstore3(tmp, 1, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s1 = ((__global ulong16 *)source)[2].S0;
  vstore3(tmp, 2, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s1 = ((__global ulong16 *)source)[3].Sb;
  vstore3(tmp, 3, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S2 = ((__global ulong16 *)source)[4].SB;
  vstore3(tmp, 4, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s1 = ((__global ulong16 *)source)[5].s5;
  vstore3(tmp, 5, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[6].sF;
  vstore3(tmp, 6, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[7].s2;
  vstore3(tmp, 7, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S0 = ((__global ulong16 *)source)[8].Sa;
  vstore3(tmp, 8, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S2 = ((__global ulong16 *)source)[9].S4;
  vstore3(tmp, 9, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[10].Sd;
  vstore3(tmp, 10, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s2 = ((__global ulong16 *)source)[11].sB;
  tmp.s1 = ((__global ulong16 *)source)[11].S3;
  vstore3(tmp, 11, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[12].S4;
  tmp.s1 = ((__global ulong16 *)source)[12].S8;
  vstore3(tmp, 12, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[13].Sc;
  tmp.S1 = ((__global ulong16 *)source)[13].s4;
  vstore3(tmp, 13, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[14].S2;
  tmp.s2 = ((__global ulong16 *)source)[14].S0;
  vstore3(tmp, 14, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s1 = ((__global ulong16 *)source)[15].s9;
  tmp.s0 = ((__global ulong16 *)source)[15].sb;
  vstore3(tmp, 15, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[16].sF;
  tmp.S1 = ((__global ulong16 *)source)[16].sE;
  vstore3(tmp, 16, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S2 = ((__global ulong16 *)source)[17].Sa;
  tmp.S1 = ((__global ulong16 *)source)[17].s7;
  vstore3(tmp, 17, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S0 = ((__global ulong16 *)source)[18].S6;
  tmp.s2 = ((__global ulong16 *)source)[18].sb;
  vstore3(tmp, 18, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S0 = ((__global ulong16 *)source)[19].Sc;
  tmp.S2 = ((__global ulong16 *)source)[19].s8;
  vstore3(tmp, 19, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s2 = ((__global ulong16 *)source)[20].s7;
  tmp.S0 = ((__global ulong16 *)source)[20].s8;
  vstore3(tmp, 20, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s2 = ((__global ulong16 *)source)[21].s8;
  tmp.s0 = ((__global ulong16 *)source)[21].sA;
  vstore3(tmp, 21, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s2 = ((__global ulong16 *)source)[22].s6;
  tmp.s0 = ((__global ulong16 *)source)[22].SA;
  vstore3(tmp, 22, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s2 = ((__global ulong16 *)source)[23].s3;
  tmp.s0 = ((__global ulong16 *)source)[23].sA;
  vstore3(tmp, 23, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s2 = ((__global ulong16 *)source)[24].s7;
  tmp.s0 = ((__global ulong16 *)source)[24].S2;
  vstore3(tmp, 24, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[25].s9;
  tmp.S1 = ((__global ulong16 *)source)[25].s6;
  vstore3(tmp, 25, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[26].SD;
  tmp.s1 = ((__global ulong16 *)source)[26].SB;
  vstore3(tmp, 26, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S2 = ((__global ulong16 *)source)[27].s3;
  tmp.S0 = ((__global ulong16 *)source)[27].SE;
  vstore3(tmp, 27, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S2 = ((__global ulong16 *)source)[28].sA;
  tmp.S1 = ((__global ulong16 *)source)[28].s8;
  vstore3(tmp, 28, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[29].SE;
  tmp.s1 = ((__global ulong16 *)source)[29].S7;
  vstore3(tmp, 29, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s1 = ((__global ulong16 *)source)[30].S0;
  tmp.S2 = ((__global ulong16 *)source)[30].S4;
  vstore3(tmp, 30, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S1 = ((__global ulong16 *)source)[31].se;
  tmp.s0 = ((__global ulong16 *)source)[31].s1;
  vstore3(tmp, 31, (__global ulong *)dest);
}
