// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global long *source, __global long *dest) {
  if (get_global_id(0) != 0)
    return;
  // long3 src1 /*, src2*/;
  long3 tmp;
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[0].S2;
  vstore3(tmp, 0, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[0].s3;
  vstore3(tmp, 1, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[0].S7;
  vstore3(tmp, 2, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[0].Sa;
  vstore3(tmp, 3, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[0].Sc;
  vstore3(tmp, 4, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[1].S0;
  vstore3(tmp, 5, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[1].s3;
  vstore3(tmp, 6, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[1].s6;
  vstore3(tmp, 7, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[1].S8;
  vstore3(tmp, 8, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[1].Sd;
  vstore3(tmp, 9, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[2].S0;
  vstore3(tmp, 10, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[2].s2;
  tmp.S0 = ((__global long16 *)source)[2].S2;
  vstore3(tmp, 11, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[2].s4;
  tmp.S0 = ((__global long16 *)source)[2].S4;
  vstore3(tmp, 12, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[2].s7;
  tmp.S1 = ((__global long16 *)source)[2].S9;
  vstore3(tmp, 13, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[2].sc;
  tmp.s1 = ((__global long16 *)source)[2].SB;
  vstore3(tmp, 14, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[2].SD;
  tmp.S0 = ((__global long16 *)source)[2].sE;
  vstore3(tmp, 15, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[3].s1;
  tmp.s1 = ((__global long16 *)source)[3].s2;
  vstore3(tmp, 16, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[3].S5;
  tmp.s0 = ((__global long16 *)source)[3].S3;
  vstore3(tmp, 17, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[3].S7;
  tmp.S2 = ((__global long16 *)source)[3].s8;
  vstore3(tmp, 18, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[3].sa;
  tmp.S1 = ((__global long16 *)source)[3].s9;
  vstore3(tmp, 19, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[3].sd;
  tmp.S1 = ((__global long16 *)source)[3].sc;
  vstore3(tmp, 20, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[4].S0;
  tmp.s0 = ((__global long16 *)source)[3].sf;
  vstore3(tmp, 21, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[4].S2;
  tmp.S0 = ((__global long16 *)source)[4].s4;
  vstore3(tmp, 22, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[4].S5;
  tmp.S0 = ((__global long16 *)source)[4].s7;
  vstore3(tmp, 23, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[4].s8;
  tmp.s0 = ((__global long16 *)source)[4].sA;
  vstore3(tmp, 24, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[4].SB;
  tmp.S1 = ((__global long16 *)source)[4].sC;
  vstore3(tmp, 25, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[4].sE;
  tmp.s1 = ((__global long16 *)source)[5].S0;
  vstore3(tmp, 26, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[5].s1;
  tmp.s2 = ((__global long16 *)source)[5].s1;
  vstore3(tmp, 27, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[5].S4;
  tmp.S2 = ((__global long16 *)source)[5].s4;
  vstore3(tmp, 28, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[5].s8;
  tmp.S2 = ((__global long16 *)source)[5].s7;
  vstore3(tmp, 29, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[5].sC;
  tmp.S0 = ((__global long16 *)source)[5].sC;
  vstore3(tmp, 30, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[5].Sd;
  tmp.S0 = ((__global long16 *)source)[5].Se;
  vstore3(tmp, 31, (__global long *)dest);
}
