// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global long16 *source, __global long *dest) {
  if (get_global_id(0) != 0)
    return;
  // long16 src1 /*, src2*/;
  long3 tmp;
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[0].Sf;
  vstore3(tmp, 0, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[1].Sc;
  vstore3(tmp, 1, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[2].S3;
  vstore3(tmp, 2, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[3].SE;
  vstore3(tmp, 3, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[4].Sa;
  vstore3(tmp, 4, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[5].S8;
  vstore3(tmp, 5, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[6].Se;
  vstore3(tmp, 6, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[7].S9;
  vstore3(tmp, 7, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[8].sB;
  vstore3(tmp, 8, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[9].sf;
  vstore3(tmp, 9, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[10].S5;
  vstore3(tmp, 10, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[11].Sa;
  tmp.S2 = ((__global long16 *)source)[11].s0;
  vstore3(tmp, 11, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[12].s8;
  tmp.S2 = ((__global long16 *)source)[12].Sa;
  vstore3(tmp, 12, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[13].Se;
  tmp.s1 = ((__global long16 *)source)[13].SB;
  vstore3(tmp, 13, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[14].s3;
  tmp.S2 = ((__global long16 *)source)[14].S7;
  vstore3(tmp, 14, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[15].S9;
  tmp.s1 = ((__global long16 *)source)[15].s9;
  vstore3(tmp, 15, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[16].se;
  tmp.S0 = ((__global long16 *)source)[16].S9;
  vstore3(tmp, 16, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[17].Sc;
  tmp.s2 = ((__global long16 *)source)[17].s9;
  vstore3(tmp, 17, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[18].S5;
  tmp.s0 = ((__global long16 *)source)[18].S1;
  vstore3(tmp, 18, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[19].s9;
  tmp.s0 = ((__global long16 *)source)[19].s2;
  vstore3(tmp, 19, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[20].s7;
  tmp.S1 = ((__global long16 *)source)[20].SE;
  vstore3(tmp, 20, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[21].S4;
  tmp.S2 = ((__global long16 *)source)[21].Sf;
  vstore3(tmp, 21, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[22].S5;
  tmp.S0 = ((__global long16 *)source)[22].s4;
  vstore3(tmp, 22, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[23].s8;
  tmp.s0 = ((__global long16 *)source)[23].s0;
  vstore3(tmp, 23, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[24].S6;
  tmp.S2 = ((__global long16 *)source)[24].S3;
  vstore3(tmp, 24, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[25].S7;
  tmp.S0 = ((__global long16 *)source)[25].s7;
  vstore3(tmp, 25, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[26].S3;
  tmp.s1 = ((__global long16 *)source)[26].S8;
  vstore3(tmp, 26, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[27].sB;
  tmp.s2 = ((__global long16 *)source)[27].S4;
  vstore3(tmp, 27, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[28].s1;
  tmp.s2 = ((__global long16 *)source)[28].S9;
  vstore3(tmp, 28, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[29].Sd;
  tmp.s1 = ((__global long16 *)source)[29].s2;
  vstore3(tmp, 29, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[30].S2;
  tmp.s1 = ((__global long16 *)source)[30].se;
  vstore3(tmp, 30, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[31].Se;
  tmp.S1 = ((__global long16 *)source)[31].SA;
  vstore3(tmp, 31, (__global long *)dest);
}
