// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
double2 shuffle_fn(double2 source);
double2 shuffle_fn(double2 source) { return source; }

__kernel void sample_test(__global double2 *source, __global double8 *dest) {
  if (get_global_id(0) != 0)
    return;
  // double2 src1 /*, src2*/;
  double8 tmp;
  tmp = (double8)((double)0);
  tmp.s7 = shuffle_fn(source[0]).s1;
  dest[0] = tmp;
  tmp = (double8)((double)0);
  tmp.s3 = shuffle_fn(source[1]).S1;
  dest[1] = tmp;
  tmp = (double8)((double)0);
  tmp.S7 = shuffle_fn(source[2]).s0;
  dest[2] = tmp;
  tmp = (double8)((double)0);
  tmp.S2 = shuffle_fn(source[3]).s1;
  dest[3] = tmp;
  tmp = (double8)((double)0);
  tmp.s0 = shuffle_fn(source[4]).S1;
  dest[4] = tmp;
  tmp = (double8)((double)0);
  tmp.s3 = shuffle_fn(source[5]).s0;
  dest[5] = tmp;
  tmp = (double8)((double)0);
  tmp.s7 = shuffle_fn(source[6]).S1;
  dest[6] = tmp;
  tmp = (double8)((double)0);
  tmp.s5 = shuffle_fn(source[7]).S0;
  dest[7] = tmp;
  tmp = (double8)((double)0);
  tmp.S7 = shuffle_fn(source[8]).s0;
  dest[8] = tmp;
  tmp = (double8)((double)0);
  tmp.s5 = shuffle_fn(source[9]).s0;
  dest[9] = tmp;
  tmp = (double8)((double)0);
  tmp.S3 = shuffle_fn(source[10]).S0;
  dest[10] = tmp;
  tmp = (double8)((double)0);
  tmp.s7 = shuffle_fn(source[11]).s1;
  dest[11] = tmp;
  tmp = (double8)((double)0);
  tmp.s6 = shuffle_fn(source[12]).S1;
  dest[12] = tmp;
  tmp = (double8)((double)0);
  tmp.S6 = shuffle_fn(source[13]).S0;
  dest[13] = tmp;
  tmp = (double8)((double)0);
  tmp.S3 = shuffle_fn(source[14]).S1;
  dest[14] = tmp;
  tmp = (double8)((double)0);
  tmp.S2 = shuffle_fn(source[15]).s0;
  dest[15] = tmp;
  tmp = (double8)((double)0);
  tmp.S74 = shuffle_fn(source[16]).S01;
  dest[16] = tmp;
  tmp = (double8)((double)0);
  tmp.S01 = shuffle_fn(source[17]).S01;
  dest[17] = tmp;
  tmp = (double8)((double)0);
  tmp.S12 = shuffle_fn(source[18]).S10;
  dest[18] = tmp;
  tmp = (double8)((double)0);
  tmp.S67 = shuffle_fn(source[19]).s11;
  dest[19] = tmp;
  tmp = (double8)((double)0);
  tmp.S40 = shuffle_fn(source[20]).S11;
  dest[20] = tmp;
  tmp = (double8)((double)0);
  tmp.s71 = shuffle_fn(source[21]).S01;
  dest[21] = tmp;
  tmp = (double8)((double)0);
  tmp.S07 = shuffle_fn(source[22]).s11;
  dest[22] = tmp;
  tmp = (double8)((double)0);
  tmp.S12 = shuffle_fn(source[23]).s10;
  dest[23] = tmp;
  tmp = (double8)((double)0);
  tmp.S72 = shuffle_fn(source[24]).s00;
  dest[24] = tmp;
  tmp = (double8)((double)0);
  tmp.s75 = shuffle_fn(source[25]).s10;
  dest[25] = tmp;
  tmp = (double8)((double)0);
  tmp.S16 = shuffle_fn(source[26]).S11;
  dest[26] = tmp;
  tmp = (double8)((double)0);
  tmp.s52 = shuffle_fn(source[27]).s01;
  dest[27] = tmp;
  tmp = (double8)((double)0);
  tmp.S40 = shuffle_fn(source[28]).s10;
  dest[28] = tmp;
  tmp = (double8)((double)0);
  tmp.S46 = shuffle_fn(source[29]).s10;
  dest[29] = tmp;
  tmp = (double8)((double)0);
  tmp.s25 = shuffle_fn(source[30]).s01;
  dest[30] = tmp;
  tmp = (double8)((double)0);
  tmp.s30 = shuffle_fn(source[31]).s10;
  dest[31] = tmp;
}
