// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global int2 *source, __global int *dest) {
  if (get_global_id(0) != 0)
    return;
  // int2 src1 /*, src2*/;
  int3 tmp;
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[0].S0;
  vstore3(tmp, 0, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[0].s3;
  vstore3(tmp, 1, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[0].s4;
  vstore3(tmp, 2, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[0].s7;
  vstore3(tmp, 3, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[0].S9;
  vstore3(tmp, 4, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[0].SA;
  vstore3(tmp, 5, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[0].Sd;
  vstore3(tmp, 6, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[0].SE;
  vstore3(tmp, 7, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[1].s0;
  vstore3(tmp, 8, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[1].S2;
  vstore3(tmp, 9, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[1].S5;
  vstore3(tmp, 10, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[1].s7;
  vstore3(tmp, 11, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[1].s8;
  vstore3(tmp, 12, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[1].sA;
  vstore3(tmp, 13, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[1].Sd;
  vstore3(tmp, 14, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[1].SE;
  vstore3(tmp, 15, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[2].S0;
  tmp.S2 = ((__global int16 *)source)[2].S1;
  vstore3(tmp, 16, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[2].s3;
  tmp.S1 = ((__global int16 *)source)[2].s2;
  vstore3(tmp, 17, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[2].S5;
  tmp.S0 = ((__global int16 *)source)[2].S4;
  vstore3(tmp, 18, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[2].S6;
  tmp.S0 = ((__global int16 *)source)[2].s7;
  vstore3(tmp, 19, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[2].S9;
  tmp.s0 = ((__global int16 *)source)[2].s8;
  vstore3(tmp, 20, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[2].Sa;
  tmp.s0 = ((__global int16 *)source)[2].SB;
  vstore3(tmp, 21, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[2].sc;
  tmp.S2 = ((__global int16 *)source)[2].SC;
  vstore3(tmp, 22, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[2].sf;
  tmp.S2 = ((__global int16 *)source)[2].se;
  vstore3(tmp, 23, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[3].s0;
  tmp.s1 = ((__global int16 *)source)[3].S0;
  vstore3(tmp, 24, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[3].S3;
  tmp.S1 = ((__global int16 *)source)[3].S3;
  vstore3(tmp, 25, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[3].S4;
  tmp.s1 = ((__global int16 *)source)[3].S5;
  vstore3(tmp, 26, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[3].S7;
  tmp.s1 = ((__global int16 *)source)[3].s7;
  vstore3(tmp, 27, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[3].s9;
  tmp.s2 = ((__global int16 *)source)[3].s9;
  vstore3(tmp, 28, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[3].sb;
  tmp.s2 = ((__global int16 *)source)[3].sB;
  vstore3(tmp, 29, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[3].sD;
  tmp.S2 = ((__global int16 *)source)[3].sC;
  vstore3(tmp, 30, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[3].sf;
  tmp.S2 = ((__global int16 *)source)[3].sE;
  vstore3(tmp, 31, (__global int *)dest);
}
