// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global float4 *source, __global float *dest) {
  if (get_global_id(0) != 0)
    return;
  // float4 src1 /*, src2*/;
  float3 tmp;
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[0].S1;
  vstore3(tmp, 0, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[0].s4;
  vstore3(tmp, 1, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[0].s9;
  vstore3(tmp, 2, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[0].Se;
  vstore3(tmp, 3, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[1].S0;
  vstore3(tmp, 4, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[1].S7;
  vstore3(tmp, 5, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[1].S8;
  vstore3(tmp, 6, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[1].Se;
  vstore3(tmp, 7, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[2].S3;
  vstore3(tmp, 8, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[2].s7;
  vstore3(tmp, 9, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[2].Sa;
  vstore3(tmp, 10, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[2].se;
  tmp.S1 = ((__global float16 *)source)[2].Sc;
  vstore3(tmp, 11, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[3].S1;
  tmp.s2 = ((__global float16 *)source)[3].s2;
  vstore3(tmp, 12, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[3].s6;
  tmp.s0 = ((__global float16 *)source)[3].s5;
  vstore3(tmp, 13, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[3].Sa;
  tmp.S0 = ((__global float16 *)source)[3].S8;
  vstore3(tmp, 14, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[3].Sf;
  tmp.S1 = ((__global float16 *)source)[3].sd;
  vstore3(tmp, 15, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[4].S1;
  tmp.S1 = ((__global float16 *)source)[4].S3;
  vstore3(tmp, 16, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[4].s7;
  tmp.s1 = ((__global float16 *)source)[4].s4;
  vstore3(tmp, 17, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[4].sa;
  tmp.S0 = ((__global float16 *)source)[4].s9;
  vstore3(tmp, 18, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[4].sc;
  tmp.s2 = ((__global float16 *)source)[4].Sc;
  vstore3(tmp, 19, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[5].s1;
  tmp.s1 = ((__global float16 *)source)[5].s0;
  vstore3(tmp, 20, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[5].s7;
  tmp.s1 = ((__global float16 *)source)[5].s7;
  vstore3(tmp, 21, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[5].S9;
  tmp.S1 = ((__global float16 *)source)[5].sB;
  vstore3(tmp, 22, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[5].Se;
  tmp.s1 = ((__global float16 *)source)[5].sE;
  vstore3(tmp, 23, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[6].S1;
  tmp.S0 = ((__global float16 *)source)[6].s2;
  vstore3(tmp, 24, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[6].S7;
  tmp.S0 = ((__global float16 *)source)[6].s6;
  vstore3(tmp, 25, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[6].s9;
  tmp.S0 = ((__global float16 *)source)[6].Sb;
  vstore3(tmp, 26, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[6].SD;
  tmp.S0 = ((__global float16 *)source)[6].Sf;
  vstore3(tmp, 27, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[7].s0;
  tmp.S1 = ((__global float16 *)source)[7].S0;
  vstore3(tmp, 28, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[7].s7;
  tmp.s1 = ((__global float16 *)source)[7].s4;
  vstore3(tmp, 29, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[7].SA;
  tmp.s1 = ((__global float16 *)source)[7].S9;
  vstore3(tmp, 30, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[7].sF;
  tmp.s0 = ((__global float16 *)source)[7].SF;
  vstore3(tmp, 31, (__global float *)dest);
}
