// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
double2 shuffle_fn(double2 source);
double2 shuffle_fn(double2 source) { return source; }

__kernel void sample_test(__global double2 *source, __global double16 *dest) {
  if (get_global_id(0) != 0)
    return;
  // double2 src1 /*, src2*/;
  double16 tmp;
  tmp = (double16)((double)0);
  tmp.Sc = shuffle_fn(source[0]).S1;
  dest[0] = tmp;
  tmp = (double16)((double)0);
  tmp.SD = shuffle_fn(source[1]).s0;
  dest[1] = tmp;
  tmp = (double16)((double)0);
  tmp.s1 = shuffle_fn(source[2]).S1;
  dest[2] = tmp;
  tmp = (double16)((double)0);
  tmp.SD = shuffle_fn(source[3]).s0;
  dest[3] = tmp;
  tmp = (double16)((double)0);
  tmp.sa = shuffle_fn(source[4]).s0;
  dest[4] = tmp;
  tmp = (double16)((double)0);
  tmp.S0 = shuffle_fn(source[5]).S0;
  dest[5] = tmp;
  tmp = (double16)((double)0);
  tmp.S7 = shuffle_fn(source[6]).s1;
  dest[6] = tmp;
  tmp = (double16)((double)0);
  tmp.S6 = shuffle_fn(source[7]).s0;
  dest[7] = tmp;
  tmp = (double16)((double)0);
  tmp.s3 = shuffle_fn(source[8]).S0;
  dest[8] = tmp;
  tmp = (double16)((double)0);
  tmp.s7 = shuffle_fn(source[9]).S1;
  dest[9] = tmp;
  tmp = (double16)((double)0);
  tmp.S4 = shuffle_fn(source[10]).S0;
  dest[10] = tmp;
  tmp = (double16)((double)0);
  tmp.S2 = shuffle_fn(source[11]).s0;
  dest[11] = tmp;
  tmp = (double16)((double)0);
  tmp.s8 = shuffle_fn(source[12]).S1;
  dest[12] = tmp;
  tmp = (double16)((double)0);
  tmp.S2 = shuffle_fn(source[13]).s1;
  dest[13] = tmp;
  tmp = (double16)((double)0);
  tmp.sF = shuffle_fn(source[14]).s0;
  dest[14] = tmp;
  tmp = (double16)((double)0);
  tmp.S6 = shuffle_fn(source[15]).S1;
  dest[15] = tmp;
  tmp = (double16)((double)0);
  tmp.s09 = shuffle_fn(source[16]).s01;
  dest[16] = tmp;
  tmp = (double16)((double)0);
  tmp.sB1 = shuffle_fn(source[17]).S10;
  dest[17] = tmp;
  tmp = (double16)((double)0);
  tmp.s8D = shuffle_fn(source[18]).S01;
  dest[18] = tmp;
  tmp = (double16)((double)0);
  tmp.S85 = shuffle_fn(source[19]).s11;
  dest[19] = tmp;
  tmp = (double16)((double)0);
  tmp.SE4 = shuffle_fn(source[20]).S01;
  dest[20] = tmp;
  tmp = (double16)((double)0);
  tmp.S50 = shuffle_fn(source[21]).S01;
  dest[21] = tmp;
  tmp = (double16)((double)0);
  tmp.S16 = shuffle_fn(source[22]).S01;
  dest[22] = tmp;
  tmp = (double16)((double)0);
  tmp.sC9 = shuffle_fn(source[23]).S00;
  dest[23] = tmp;
  tmp = (double16)((double)0);
  tmp.S41 = shuffle_fn(source[24]).s01;
  dest[24] = tmp;
  tmp = (double16)((double)0);
  tmp.s0D = shuffle_fn(source[25]).S10;
  dest[25] = tmp;
  tmp = (double16)((double)0);
  tmp.S3f = shuffle_fn(source[26]).s11;
  dest[26] = tmp;
  tmp = (double16)((double)0);
  tmp.SBA = shuffle_fn(source[27]).S11;
  dest[27] = tmp;
  tmp = (double16)((double)0);
  tmp.S2f = shuffle_fn(source[28]).s00;
  dest[28] = tmp;
  tmp = (double16)((double)0);
  tmp.S91 = shuffle_fn(source[29]).s10;
  dest[29] = tmp;
  tmp = (double16)((double)0);
  tmp.Se6 = shuffle_fn(source[30]).S01;
  dest[30] = tmp;
  tmp = (double16)((double)0);
  tmp.SDB = shuffle_fn(source[31]).s11;
  dest[31] = tmp;
}
