// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
double16 shuffle_fn(double16 source);
double16 shuffle_fn(double16 source) { return source; }

__kernel void sample_test(__global double16 *source, __global double2 *dest) {
  if (get_global_id(0) != 0)
    return;
  // double16 src1 /*, src2*/;
  double2 tmp;
  tmp = (double2)((double)0);
  tmp.s0 = shuffle_fn(source[0]).sE;
  dest[0] = tmp;
  tmp = (double2)((double)0);
  tmp.s1 = shuffle_fn(source[1]).s1;
  dest[1] = tmp;
  tmp = (double2)((double)0);
  tmp.S1 = shuffle_fn(source[2]).S4;
  dest[2] = tmp;
  tmp = (double2)((double)0);
  tmp.s0 = shuffle_fn(source[3]).S0;
  dest[3] = tmp;
  tmp = (double2)((double)0);
  tmp.s1 = shuffle_fn(source[4]).s7;
  dest[4] = tmp;
  tmp = (double2)((double)0);
  tmp.s0 = shuffle_fn(source[5]).s0;
  dest[5] = tmp;
  tmp = (double2)((double)0);
  tmp.s1 = shuffle_fn(source[6]).Sf;
  dest[6] = tmp;
  tmp = (double2)((double)0);
  tmp.S0 = shuffle_fn(source[7]).SA;
  dest[7] = tmp;
  tmp = (double2)((double)0);
  tmp.S1 = shuffle_fn(source[8]).Sa;
  dest[8] = tmp;
  tmp = (double2)((double)0);
  tmp.s1 = shuffle_fn(source[9]).S9;
  dest[9] = tmp;
  tmp = (double2)((double)0);
  tmp.s0 = shuffle_fn(source[10]).s6;
  dest[10] = tmp;
  tmp = (double2)((double)0);
  tmp.S0 = shuffle_fn(source[11]).se;
  dest[11] = tmp;
  tmp = (double2)((double)0);
  tmp.S1 = shuffle_fn(source[12]).s6;
  dest[12] = tmp;
  tmp = (double2)((double)0);
  tmp.s1 = shuffle_fn(source[13]).s9;
  dest[13] = tmp;
  tmp = (double2)((double)0);
  tmp.S0 = shuffle_fn(source[14]).s1;
  dest[14] = tmp;
  tmp = (double2)((double)0);
  tmp.S0 = shuffle_fn(source[15]).sa;
  dest[15] = tmp;
  tmp = (double2)((double)0);
  tmp.s01 = shuffle_fn(source[16]).sf8;
  dest[16] = tmp;
  tmp = (double2)((double)0);
  tmp.S10 = shuffle_fn(source[17]).SE6;
  dest[17] = tmp;
  tmp = (double2)((double)0);
  tmp.S01 = shuffle_fn(source[18]).S62;
  dest[18] = tmp;
  tmp = (double2)((double)0);
  tmp.s01 = shuffle_fn(source[19]).S79;
  dest[19] = tmp;
  tmp = (double2)((double)0);
  tmp.S10 = shuffle_fn(source[20]).sC6;
  dest[20] = tmp;
  tmp = (double2)((double)0);
  tmp.S01 = shuffle_fn(source[21]).sfc;
  dest[21] = tmp;
  tmp = (double2)((double)0);
  tmp.S01 = shuffle_fn(source[22]).S5a;
  dest[22] = tmp;
  tmp = (double2)((double)0);
  tmp.S10 = shuffle_fn(source[23]).S97;
  dest[23] = tmp;
  tmp = (double2)((double)0);
  tmp.s10 = shuffle_fn(source[24]).S1B;
  dest[24] = tmp;
  tmp = (double2)((double)0);
  tmp.s01 = shuffle_fn(source[25]).s2f;
  dest[25] = tmp;
  tmp = (double2)((double)0);
  tmp.S10 = shuffle_fn(source[26]).S31;
  dest[26] = tmp;
  tmp = (double2)((double)0);
  tmp.s01 = shuffle_fn(source[27]).Sa4;
  dest[27] = tmp;
  tmp = (double2)((double)0);
  tmp.s01 = shuffle_fn(source[28]).S07;
  dest[28] = tmp;
  tmp = (double2)((double)0);
  tmp.S01 = shuffle_fn(source[29]).s55;
  dest[29] = tmp;
  tmp = (double2)((double)0);
  tmp.S01 = shuffle_fn(source[30]).S4C;
  dest[30] = tmp;
  tmp = (double2)((double)0);
  tmp.s01 = shuffle_fn(source[31]).sA4;
  dest[31] = tmp;
}
