// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global float *source, __global float *dest) {
  if (get_global_id(0) != 0)
    return;
  // float3 src1 /*, src2*/;
  float3 tmp;
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[0].s1;
  vstore3(tmp, 0, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[0].S5;
  vstore3(tmp, 1, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[0].s6;
  vstore3(tmp, 2, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[0].SA;
  vstore3(tmp, 3, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[0].SE;
  vstore3(tmp, 4, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[0].Sf;
  vstore3(tmp, 5, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[1].s4;
  vstore3(tmp, 6, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[1].s5;
  vstore3(tmp, 7, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[1].sA;
  vstore3(tmp, 8, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[1].sC;
  vstore3(tmp, 9, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[1].sf;
  vstore3(tmp, 10, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[2].s1;
  tmp.S1 = ((__global float16 *)source)[2].s3;
  vstore3(tmp, 11, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[2].s6;
  tmp.S1 = ((__global float16 *)source)[2].s4;
  vstore3(tmp, 12, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[2].s9;
  tmp.s2 = ((__global float16 *)source)[2].S7;
  vstore3(tmp, 13, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[2].sa;
  tmp.s0 = ((__global float16 *)source)[2].Sc;
  vstore3(tmp, 14, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[2].SD;
  tmp.S1 = ((__global float16 *)source)[2].sE;
  vstore3(tmp, 15, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[3].S2;
  tmp.s1 = ((__global float16 *)source)[3].s0;
  vstore3(tmp, 16, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[3].S4;
  tmp.s1 = ((__global float16 *)source)[3].s4;
  vstore3(tmp, 17, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[3].S7;
  tmp.s0 = ((__global float16 *)source)[3].S6;
  vstore3(tmp, 18, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[3].SA;
  tmp.S0 = ((__global float16 *)source)[3].s9;
  vstore3(tmp, 19, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[3].Sc;
  tmp.s1 = ((__global float16 *)source)[3].sd;
  vstore3(tmp, 20, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[4].S1;
  tmp.s1 = ((__global float16 *)source)[4].S1;
  vstore3(tmp, 21, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[4].s2;
  tmp.S1 = ((__global float16 *)source)[4].S4;
  vstore3(tmp, 22, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[4].S7;
  tmp.s0 = ((__global float16 *)source)[4].S6;
  vstore3(tmp, 23, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[4].S9;
  tmp.S0 = ((__global float16 *)source)[4].s9;
  vstore3(tmp, 24, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[4].sD;
  tmp.S0 = ((__global float16 *)source)[4].SD;
  vstore3(tmp, 25, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[5].s0;
  tmp.S1 = ((__global float16 *)source)[4].se;
  vstore3(tmp, 26, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[5].s1;
  tmp.s0 = ((__global float16 *)source)[5].S2;
  vstore3(tmp, 27, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[5].S4;
  tmp.s0 = ((__global float16 *)source)[5].S4;
  vstore3(tmp, 28, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[5].S9;
  tmp.S1 = ((__global float16 *)source)[5].S7;
  vstore3(tmp, 29, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[5].sc;
  tmp.S1 = ((__global float16 *)source)[5].sb;
  vstore3(tmp, 30, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[5].Sf;
  tmp.S2 = ((__global float16 *)source)[5].sF;
  vstore3(tmp, 31, (__global float *)dest);
}
