// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
double3 shuffle_fn(double3 source);
double3 shuffle_fn(double3 source) { return source; }

__kernel void sample_test(__global double *source, __global double16 *dest) {
  if (get_global_id(0) != 0)
    return;
  // double3 src1 /*, src2*/;
  double16 tmp;
  tmp = (double16)((double)0);
  tmp.s4 = shuffle_fn(vload3(0, source)).S1;
  dest[0] = tmp;
  tmp = (double16)((double)0);
  tmp.SA = shuffle_fn(vload3(1, source)).S0;
  dest[1] = tmp;
  tmp = (double16)((double)0);
  tmp.sF = shuffle_fn(vload3(2, source)).s0;
  dest[2] = tmp;
  tmp = (double16)((double)0);
  tmp.S8 = shuffle_fn(vload3(3, source)).S0;
  dest[3] = tmp;
  tmp = (double16)((double)0);
  tmp.S6 = shuffle_fn(vload3(4, source)).s1;
  dest[4] = tmp;
  tmp = (double16)((double)0);
  tmp.s9 = shuffle_fn(vload3(5, source)).s1;
  dest[5] = tmp;
  tmp = (double16)((double)0);
  tmp.sC = shuffle_fn(vload3(6, source)).s1;
  dest[6] = tmp;
  tmp = (double16)((double)0);
  tmp.SD = shuffle_fn(vload3(7, source)).s0;
  dest[7] = tmp;
  tmp = (double16)((double)0);
  tmp.sB = shuffle_fn(vload3(8, source)).S1;
  dest[8] = tmp;
  tmp = (double16)((double)0);
  tmp.s6 = shuffle_fn(vload3(9, source)).s1;
  dest[9] = tmp;
  tmp = (double16)((double)0);
  tmp.sc = shuffle_fn(vload3(10, source)).s2;
  dest[10] = tmp;
  tmp = (double16)((double)0);
  tmp.s14 = shuffle_fn(vload3(11, source)).s11;
  dest[11] = tmp;
  tmp = (double16)((double)0);
  tmp.s7C = shuffle_fn(vload3(12, source)).s21;
  dest[12] = tmp;
  tmp = (double16)((double)0);
  tmp.s54 = shuffle_fn(vload3(13, source)).S02;
  dest[13] = tmp;
  tmp = (double16)((double)0);
  tmp.s76 = shuffle_fn(vload3(14, source)).S01;
  dest[14] = tmp;
  tmp = (double16)((double)0);
  tmp.sbA = shuffle_fn(vload3(15, source)).s01;
  dest[15] = tmp;
  tmp = (double16)((double)0);
  tmp.SF8 = shuffle_fn(vload3(16, source)).s12;
  dest[16] = tmp;
  tmp = (double16)((double)0);
  tmp.s90 = shuffle_fn(vload3(17, source)).S21;
  dest[17] = tmp;
  tmp = (double16)((double)0);
  tmp.S86 = shuffle_fn(vload3(18, source)).S02;
  dest[18] = tmp;
  tmp = (double16)((double)0);
  tmp.SB4 = shuffle_fn(vload3(19, source)).s00;
  dest[19] = tmp;
  tmp = (double16)((double)0);
  tmp.S91 = shuffle_fn(vload3(20, source)).S00;
  dest[20] = tmp;
  tmp = (double16)((double)0);
  tmp.SA0 = shuffle_fn(vload3(21, source)).S01;
  dest[21] = tmp;
  tmp = (double16)((double)0);
  tmp.S7A = shuffle_fn(vload3(22, source)).S20;
  dest[22] = tmp;
  tmp = (double16)((double)0);
  tmp.S39 = shuffle_fn(vload3(23, source)).s21;
  dest[23] = tmp;
  tmp = (double16)((double)0);
  tmp.SB3 = shuffle_fn(vload3(24, source)).s01;
  dest[24] = tmp;
  tmp = (double16)((double)0);
  tmp.S83 = shuffle_fn(vload3(25, source)).s02;
  dest[25] = tmp;
  tmp = (double16)((double)0);
  tmp.S70 = shuffle_fn(vload3(26, source)).S10;
  dest[26] = tmp;
  tmp = (double16)((double)0);
  tmp.SDf = shuffle_fn(vload3(27, source)).s22;
  dest[27] = tmp;
  tmp = (double16)((double)0);
  tmp.sa6 = shuffle_fn(vload3(28, source)).S02;
  dest[28] = tmp;
  tmp = (double16)((double)0);
  tmp.s5B = shuffle_fn(vload3(29, source)).s22;
  dest[29] = tmp;
  tmp = (double16)((double)0);
  tmp.S02 = shuffle_fn(vload3(30, source)).S10;
  dest[30] = tmp;
  tmp = (double16)((double)0);
  tmp.s79 = shuffle_fn(vload3(31, source)).s21;
  dest[31] = tmp;
}
