// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global int16 *source, __global int *dest) {
  if (get_global_id(0) != 0)
    return;
  // int16 src1 /*, src2*/;
  int3 tmp;
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[0].sb;
  vstore3(tmp, 0, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[1].S4;
  vstore3(tmp, 1, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[2].S9;
  vstore3(tmp, 2, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[3].s1;
  vstore3(tmp, 3, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[4].s7;
  vstore3(tmp, 4, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[5].S2;
  vstore3(tmp, 5, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[6].sd;
  vstore3(tmp, 6, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[7].S1;
  vstore3(tmp, 7, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[8].sE;
  vstore3(tmp, 8, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[9].sB;
  vstore3(tmp, 9, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[10].s9;
  vstore3(tmp, 10, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[11].S1;
  tmp.S2 = ((__global int16 *)source)[11].Sb;
  vstore3(tmp, 11, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[12].S0;
  tmp.S0 = ((__global int16 *)source)[12].Se;
  vstore3(tmp, 12, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[13].sA;
  tmp.S0 = ((__global int16 *)source)[13].S1;
  vstore3(tmp, 13, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[14].s7;
  tmp.S0 = ((__global int16 *)source)[14].s2;
  vstore3(tmp, 14, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[15].SF;
  tmp.S1 = ((__global int16 *)source)[15].sE;
  vstore3(tmp, 15, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[16].s8;
  tmp.S2 = ((__global int16 *)source)[16].SF;
  vstore3(tmp, 16, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[17].s0;
  tmp.S2 = ((__global int16 *)source)[17].s5;
  vstore3(tmp, 17, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[18].s1;
  tmp.S1 = ((__global int16 *)source)[18].S5;
  vstore3(tmp, 18, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[19].S9;
  tmp.S0 = ((__global int16 *)source)[19].S6;
  vstore3(tmp, 19, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[20].S7;
  tmp.S2 = ((__global int16 *)source)[20].sd;
  vstore3(tmp, 20, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[21].s6;
  tmp.S1 = ((__global int16 *)source)[21].S2;
  vstore3(tmp, 21, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[22].s9;
  tmp.s2 = ((__global int16 *)source)[22].sc;
  vstore3(tmp, 22, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[23].sd;
  tmp.S1 = ((__global int16 *)source)[23].s0;
  vstore3(tmp, 23, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[24].S4;
  tmp.s0 = ((__global int16 *)source)[24].s1;
  vstore3(tmp, 24, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[25].s3;
  tmp.s0 = ((__global int16 *)source)[25].sA;
  vstore3(tmp, 25, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[26].S4;
  tmp.S2 = ((__global int16 *)source)[26].S3;
  vstore3(tmp, 26, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[27].s8;
  tmp.s2 = ((__global int16 *)source)[27].S3;
  vstore3(tmp, 27, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[28].S7;
  tmp.s2 = ((__global int16 *)source)[28].s3;
  vstore3(tmp, 28, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[29].s7;
  tmp.S0 = ((__global int16 *)source)[29].s9;
  vstore3(tmp, 29, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[30].s2;
  tmp.S1 = ((__global int16 *)source)[30].s5;
  vstore3(tmp, 30, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[31].s0;
  tmp.S2 = ((__global int16 *)source)[31].se;
  vstore3(tmp, 31, (__global int *)dest);
}
