// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global float8 *source, __global float *dest) {
  if (get_global_id(0) != 0)
    return;
  // float8 src1 /*, src2*/;
  float3 tmp;
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[0].S6;
  vstore3(tmp, 0, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[0].sd;
  vstore3(tmp, 1, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[1].S4;
  vstore3(tmp, 2, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[1].SB;
  vstore3(tmp, 3, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[2].S5;
  vstore3(tmp, 4, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[2].s8;
  vstore3(tmp, 5, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[3].S4;
  vstore3(tmp, 6, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[3].Se;
  vstore3(tmp, 7, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[4].s2;
  vstore3(tmp, 8, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[4].S8;
  vstore3(tmp, 9, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[5].s5;
  vstore3(tmp, 10, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[5].SC;
  tmp.s2 = ((__global float16 *)source)[5].s8;
  vstore3(tmp, 11, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[6].s0;
  tmp.S0 = ((__global float16 *)source)[6].S2;
  vstore3(tmp, 12, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[6].sF;
  tmp.S1 = ((__global float16 *)source)[6].Se;
  vstore3(tmp, 13, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[7].s0;
  tmp.s1 = ((__global float16 *)source)[7].s4;
  vstore3(tmp, 14, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[7].sb;
  tmp.s0 = ((__global float16 *)source)[7].S8;
  vstore3(tmp, 15, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[8].S6;
  tmp.s0 = ((__global float16 *)source)[8].s0;
  vstore3(tmp, 16, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[8].Sa;
  tmp.S2 = ((__global float16 *)source)[8].s9;
  vstore3(tmp, 17, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[9].S3;
  tmp.s0 = ((__global float16 *)source)[9].s7;
  vstore3(tmp, 18, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[9].S8;
  tmp.s1 = ((__global float16 *)source)[9].sB;
  vstore3(tmp, 19, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[10].s6;
  tmp.S1 = ((__global float16 *)source)[10].S3;
  vstore3(tmp, 20, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[10].sE;
  tmp.s0 = ((__global float16 *)source)[10].sf;
  vstore3(tmp, 21, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[11].S0;
  tmp.s0 = ((__global float16 *)source)[11].s1;
  vstore3(tmp, 22, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[11].sA;
  tmp.s0 = ((__global float16 *)source)[11].S9;
  vstore3(tmp, 23, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[12].S6;
  tmp.S0 = ((__global float16 *)source)[12].S5;
  vstore3(tmp, 24, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[12].sB;
  tmp.s0 = ((__global float16 *)source)[12].sc;
  vstore3(tmp, 25, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[13].s3;
  tmp.S1 = ((__global float16 *)source)[13].s3;
  vstore3(tmp, 26, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[13].se;
  tmp.S0 = ((__global float16 *)source)[13].s9;
  vstore3(tmp, 27, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[14].s3;
  tmp.S2 = ((__global float16 *)source)[14].s1;
  vstore3(tmp, 28, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[14].Sf;
  tmp.s2 = ((__global float16 *)source)[14].sd;
  vstore3(tmp, 29, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[15].s1;
  tmp.s1 = ((__global float16 *)source)[15].s5;
  vstore3(tmp, 30, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[15].S9;
  tmp.s2 = ((__global float16 *)source)[15].SD;
  vstore3(tmp, 31, (__global float *)dest);
}
