// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global short4 *source, __global short *dest) {
  if (get_global_id(0) != 0)
    return;
  // short4 src1 /*, src2*/;
  short3 tmp;
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[0].S1;
  vstore3(tmp, 0, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[0].s5;
  vstore3(tmp, 1, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[0].sB;
  vstore3(tmp, 2, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[0].se;
  vstore3(tmp, 3, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[1].S3;
  vstore3(tmp, 4, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s2 = ((__global short16 *)source)[1].s6;
  vstore3(tmp, 5, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[1].S9;
  vstore3(tmp, 6, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[1].SE;
  vstore3(tmp, 7, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[2].s3;
  vstore3(tmp, 8, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[2].s4;
  vstore3(tmp, 9, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[2].s8;
  vstore3(tmp, 10, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[2].SC;
  tmp.S1 = ((__global short16 *)source)[2].sc;
  vstore3(tmp, 11, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[3].S2;
  tmp.S0 = ((__global short16 *)source)[3].s3;
  vstore3(tmp, 12, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[3].s4;
  tmp.S2 = ((__global short16 *)source)[3].S5;
  vstore3(tmp, 13, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[3].s9;
  tmp.S1 = ((__global short16 *)source)[3].SA;
  vstore3(tmp, 14, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[3].Sd;
  tmp.s2 = ((__global short16 *)source)[3].sf;
  vstore3(tmp, 15, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[4].S1;
  tmp.s1 = ((__global short16 *)source)[4].s0;
  vstore3(tmp, 16, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[4].s4;
  tmp.S0 = ((__global short16 *)source)[4].S5;
  vstore3(tmp, 17, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[4].sa;
  tmp.s2 = ((__global short16 *)source)[4].S9;
  vstore3(tmp, 18, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[4].SC;
  tmp.s2 = ((__global short16 *)source)[4].sC;
  vstore3(tmp, 19, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[5].S2;
  tmp.S2 = ((__global short16 *)source)[5].s3;
  vstore3(tmp, 20, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s2 = ((__global short16 *)source)[5].s5;
  tmp.s1 = ((__global short16 *)source)[5].S4;
  vstore3(tmp, 21, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[5].Sa;
  tmp.S2 = ((__global short16 *)source)[5].SB;
  vstore3(tmp, 22, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[5].sc;
  tmp.s2 = ((__global short16 *)source)[5].Se;
  vstore3(tmp, 23, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s2 = ((__global short16 *)source)[6].s1;
  tmp.S0 = ((__global short16 *)source)[6].S1;
  vstore3(tmp, 24, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[6].S4;
  tmp.s2 = ((__global short16 *)source)[6].s5;
  vstore3(tmp, 25, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[6].Sb;
  tmp.s1 = ((__global short16 *)source)[6].S9;
  vstore3(tmp, 26, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[6].sD;
  tmp.S0 = ((__global short16 *)source)[6].Sd;
  vstore3(tmp, 27, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[7].s1;
  tmp.s2 = ((__global short16 *)source)[7].S2;
  vstore3(tmp, 28, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[7].S4;
  tmp.S2 = ((__global short16 *)source)[7].S6;
  vstore3(tmp, 29, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[7].s9;
  tmp.s1 = ((__global short16 *)source)[7].sa;
  vstore3(tmp, 30, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[7].sF;
  tmp.s1 = ((__global short16 *)source)[7].sc;
  vstore3(tmp, 31, (__global short *)dest);
}
