// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global float8 *source, __global float *dest) {
  if (get_global_id(0) != 0)
    return;
  // float8 src1 /*, src2*/;
  float3 tmp;
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[0].S4;
  vstore3(tmp, 0, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[0].s8;
  vstore3(tmp, 1, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[1].s7;
  vstore3(tmp, 2, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[1].se;
  vstore3(tmp, 3, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[2].s5;
  vstore3(tmp, 4, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[2].S9;
  vstore3(tmp, 5, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[3].S5;
  vstore3(tmp, 6, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[3].S8;
  vstore3(tmp, 7, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[4].s0;
  vstore3(tmp, 8, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[4].SE;
  vstore3(tmp, 9, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[5].s4;
  vstore3(tmp, 10, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[5].Se;
  tmp.S1 = ((__global float16 *)source)[5].S8;
  vstore3(tmp, 11, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[6].s5;
  tmp.S2 = ((__global float16 *)source)[6].S2;
  vstore3(tmp, 12, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[6].Sc;
  tmp.s2 = ((__global float16 *)source)[6].sE;
  vstore3(tmp, 13, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[7].S4;
  tmp.s1 = ((__global float16 *)source)[7].s1;
  vstore3(tmp, 14, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[7].sA;
  tmp.S2 = ((__global float16 *)source)[7].sA;
  vstore3(tmp, 15, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[8].S7;
  tmp.s2 = ((__global float16 *)source)[8].s1;
  vstore3(tmp, 16, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[8].sa;
  tmp.S0 = ((__global float16 *)source)[8].sc;
  vstore3(tmp, 17, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[9].s0;
  tmp.S2 = ((__global float16 *)source)[9].S7;
  vstore3(tmp, 18, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[9].SB;
  tmp.s0 = ((__global float16 *)source)[9].sD;
  vstore3(tmp, 19, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[10].S0;
  tmp.S1 = ((__global float16 *)source)[10].s0;
  vstore3(tmp, 20, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[10].S8;
  tmp.S2 = ((__global float16 *)source)[10].sA;
  vstore3(tmp, 21, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[11].s4;
  tmp.S1 = ((__global float16 *)source)[11].s3;
  vstore3(tmp, 22, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[11].sF;
  tmp.s0 = ((__global float16 *)source)[11].s9;
  vstore3(tmp, 23, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[12].S5;
  tmp.S1 = ((__global float16 *)source)[12].s7;
  vstore3(tmp, 24, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[12].sD;
  tmp.s1 = ((__global float16 *)source)[12].SA;
  vstore3(tmp, 25, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[13].s4;
  tmp.S2 = ((__global float16 *)source)[13].s7;
  vstore3(tmp, 26, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[13].sF;
  tmp.S2 = ((__global float16 *)source)[13].sd;
  vstore3(tmp, 27, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[14].s6;
  tmp.S1 = ((__global float16 *)source)[14].s5;
  vstore3(tmp, 28, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[14].sb;
  tmp.s0 = ((__global float16 *)source)[14].s8;
  vstore3(tmp, 29, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[15].s4;
  tmp.s0 = ((__global float16 *)source)[15].s4;
  vstore3(tmp, 30, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[15].SD;
  tmp.S2 = ((__global float16 *)source)[15].s9;
  vstore3(tmp, 31, (__global float *)dest);
}
