// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global short16 *source, __global short *dest) {
  if (get_global_id(0) != 0)
    return;
  // short16 src1 /*, src2*/;
  short3 tmp;
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[0].s8;
  vstore3(tmp, 0, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[1].s8;
  vstore3(tmp, 1, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[2].S3;
  vstore3(tmp, 2, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[3].Sf;
  vstore3(tmp, 3, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[4].S5;
  vstore3(tmp, 4, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[5].S1;
  vstore3(tmp, 5, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[6].Sc;
  vstore3(tmp, 6, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[7].s7;
  vstore3(tmp, 7, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s2 = ((__global short16 *)source)[8].sf;
  vstore3(tmp, 8, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[9].S3;
  vstore3(tmp, 9, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s2 = ((__global short16 *)source)[10].S5;
  vstore3(tmp, 10, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[11].Sa;
  tmp.S1 = ((__global short16 *)source)[11].Sc;
  vstore3(tmp, 11, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[12].SF;
  tmp.s2 = ((__global short16 *)source)[12].sa;
  vstore3(tmp, 12, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[13].sC;
  tmp.S0 = ((__global short16 *)source)[13].SB;
  vstore3(tmp, 13, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[14].s7;
  tmp.S2 = ((__global short16 *)source)[14].S2;
  vstore3(tmp, 14, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[15].Se;
  tmp.S0 = ((__global short16 *)source)[15].SF;
  vstore3(tmp, 15, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[16].sf;
  tmp.S0 = ((__global short16 *)source)[16].S7;
  vstore3(tmp, 16, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[17].sa;
  tmp.s2 = ((__global short16 *)source)[17].SF;
  vstore3(tmp, 17, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[18].sC;
  tmp.S2 = ((__global short16 *)source)[18].S5;
  vstore3(tmp, 18, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[19].S8;
  tmp.s1 = ((__global short16 *)source)[19].sd;
  vstore3(tmp, 19, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s2 = ((__global short16 *)source)[20].S3;
  tmp.S1 = ((__global short16 *)source)[20].s7;
  vstore3(tmp, 20, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s2 = ((__global short16 *)source)[21].SB;
  tmp.S1 = ((__global short16 *)source)[21].Sd;
  vstore3(tmp, 21, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[22].S8;
  tmp.s2 = ((__global short16 *)source)[22].s2;
  vstore3(tmp, 22, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[23].sD;
  tmp.s2 = ((__global short16 *)source)[23].S9;
  vstore3(tmp, 23, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s2 = ((__global short16 *)source)[24].S0;
  tmp.s0 = ((__global short16 *)source)[24].s6;
  vstore3(tmp, 24, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[25].s8;
  tmp.s0 = ((__global short16 *)source)[25].sA;
  vstore3(tmp, 25, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[26].S6;
  tmp.s2 = ((__global short16 *)source)[26].Sf;
  vstore3(tmp, 26, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[27].s0;
  tmp.s0 = ((__global short16 *)source)[27].SA;
  vstore3(tmp, 27, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[28].SB;
  tmp.s2 = ((__global short16 *)source)[28].s8;
  vstore3(tmp, 28, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[29].S3;
  tmp.s2 = ((__global short16 *)source)[29].Sb;
  vstore3(tmp, 29, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[30].s0;
  tmp.s1 = ((__global short16 *)source)[30].S9;
  vstore3(tmp, 30, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[31].sF;
  tmp.S0 = ((__global short16 *)source)[31].SD;
  vstore3(tmp, 31, (__global short *)dest);
}
