// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
double16 shuffle_fn(double16 source);
double16 shuffle_fn(double16 source) { return source; }

__kernel void sample_test(__global double16 *source, __global double *dest) {
  if (get_global_id(0) != 0)
    return;
  // double16 src1 /*, src2*/;
  double3 tmp;
  tmp = (double)((double)0);
  tmp.s2 = shuffle_fn(source[0]).s3;
  vstore3(tmp, 0, dest);
  tmp = (double)((double)0);
  tmp.S1 = shuffle_fn(source[1]).s3;
  vstore3(tmp, 1, dest);
  tmp = (double)((double)0);
  tmp.S0 = shuffle_fn(source[2]).s5;
  vstore3(tmp, 2, dest);
  tmp = (double)((double)0);
  tmp.S2 = shuffle_fn(source[3]).s3;
  vstore3(tmp, 3, dest);
  tmp = (double)((double)0);
  tmp.s0 = shuffle_fn(source[4]).SC;
  vstore3(tmp, 4, dest);
  tmp = (double)((double)0);
  tmp.S1 = shuffle_fn(source[5]).s4;
  vstore3(tmp, 5, dest);
  tmp = (double)((double)0);
  tmp.S0 = shuffle_fn(source[6]).s4;
  vstore3(tmp, 6, dest);
  tmp = (double)((double)0);
  tmp.S1 = shuffle_fn(source[7]).S6;
  vstore3(tmp, 7, dest);
  tmp = (double)((double)0);
  tmp.S1 = shuffle_fn(source[8]).sf;
  vstore3(tmp, 8, dest);
  tmp = (double)((double)0);
  tmp.s1 = shuffle_fn(source[9]).s2;
  vstore3(tmp, 9, dest);
  tmp = (double)((double)0);
  tmp.S0 = shuffle_fn(source[10]).s4;
  vstore3(tmp, 10, dest);
  tmp = (double)((double)0);
  tmp.s12 = shuffle_fn(source[11]).S76;
  vstore3(tmp, 11, dest);
  tmp = (double)((double)0);
  tmp.S12 = shuffle_fn(source[12]).SF1;
  vstore3(tmp, 12, dest);
  tmp = (double)((double)0);
  tmp.S20 = shuffle_fn(source[13]).SeB;
  vstore3(tmp, 13, dest);
  tmp = (double)((double)0);
  tmp.s20 = shuffle_fn(source[14]).SAE;
  vstore3(tmp, 14, dest);
  tmp = (double)((double)0);
  tmp.s20 = shuffle_fn(source[15]).sD6;
  vstore3(tmp, 15, dest);
  tmp = (double)((double)0);
  tmp.S02 = shuffle_fn(source[16]).SbE;
  vstore3(tmp, 16, dest);
  tmp = (double)((double)0);
  tmp.S01 = shuffle_fn(source[17]).s92;
  vstore3(tmp, 17, dest);
  tmp = (double)((double)0);
  tmp.s12 = shuffle_fn(source[18]).sED;
  vstore3(tmp, 18, dest);
  tmp = (double)((double)0);
  tmp.s12 = shuffle_fn(source[19]).S8B;
  vstore3(tmp, 19, dest);
  tmp = (double)((double)0);
  tmp.s01 = shuffle_fn(source[20]).seE;
  vstore3(tmp, 20, dest);
  tmp = (double)((double)0);
  tmp.S20 = shuffle_fn(source[21]).s5E;
  vstore3(tmp, 21, dest);
  tmp = (double)((double)0);
  tmp.s01 = shuffle_fn(source[22]).S7f;
  vstore3(tmp, 22, dest);
  tmp = (double)((double)0);
  tmp.S01 = shuffle_fn(source[23]).sC5;
  vstore3(tmp, 23, dest);
  tmp = (double)((double)0);
  tmp.s01 = shuffle_fn(source[24]).S9F;
  vstore3(tmp, 24, dest);
  tmp = (double)((double)0);
  tmp.S21 = shuffle_fn(source[25]).s55;
  vstore3(tmp, 25, dest);
  tmp = (double)((double)0);
  tmp.S21 = shuffle_fn(source[26]).sf0;
  vstore3(tmp, 26, dest);
  tmp = (double)((double)0);
  tmp.S01 = shuffle_fn(source[27]).S1e;
  vstore3(tmp, 27, dest);
  tmp = (double)((double)0);
  tmp.s21 = shuffle_fn(source[28]).S98;
  vstore3(tmp, 28, dest);
  tmp = (double)((double)0);
  tmp.s02 = shuffle_fn(source[29]).sEE;
  vstore3(tmp, 29, dest);
  tmp = (double)((double)0);
  tmp.s20 = shuffle_fn(source[30]).S6A;
  vstore3(tmp, 30, dest);
  tmp = (double)((double)0);
  tmp.s20 = shuffle_fn(source[31]).sF4;
  vstore3(tmp, 31, dest);
}
