// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
__kernel void sample_test(__global double4 *source, __global double *dest) {
  if (get_global_id(0) != 0)
    return;
  // double4 src1 /*, src2*/;
  double3 tmp;
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[0].s0;
  vstore3(tmp, 0, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[0].s7;
  vstore3(tmp, 1, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S2 = ((__global double16 *)source)[0].S8;
  vstore3(tmp, 2, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[0].SD;
  vstore3(tmp, 3, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[1].s2;
  vstore3(tmp, 4, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[1].s7;
  vstore3(tmp, 5, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[1].sA;
  vstore3(tmp, 6, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[1].se;
  vstore3(tmp, 7, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S2 = ((__global double16 *)source)[2].s1;
  vstore3(tmp, 8, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[2].s5;
  vstore3(tmp, 9, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s2 = ((__global double16 *)source)[2].s8;
  vstore3(tmp, 10, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[2].Sd;
  tmp.S2 = ((__global double16 *)source)[2].sC;
  vstore3(tmp, 11, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[3].s0;
  tmp.S0 = ((__global double16 *)source)[3].S1;
  vstore3(tmp, 12, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[3].s6;
  tmp.s2 = ((__global double16 *)source)[3].s4;
  vstore3(tmp, 13, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s2 = ((__global double16 *)source)[3].sA;
  tmp.s0 = ((__global double16 *)source)[3].S9;
  vstore3(tmp, 14, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S0 = ((__global double16 *)source)[3].Se;
  tmp.S1 = ((__global double16 *)source)[3].sC;
  vstore3(tmp, 15, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s2 = ((__global double16 *)source)[4].s0;
  tmp.S1 = ((__global double16 *)source)[4].S3;
  vstore3(tmp, 16, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s2 = ((__global double16 *)source)[4].S4;
  tmp.S1 = ((__global double16 *)source)[4].S4;
  vstore3(tmp, 17, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[4].s9;
  tmp.S2 = ((__global double16 *)source)[4].SB;
  vstore3(tmp, 18, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[4].sF;
  tmp.S2 = ((__global double16 *)source)[4].SE;
  vstore3(tmp, 19, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[5].S3;
  tmp.s0 = ((__global double16 *)source)[5].S1;
  vstore3(tmp, 20, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[5].s4;
  tmp.s2 = ((__global double16 *)source)[5].s6;
  vstore3(tmp, 21, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[5].Sb;
  tmp.S2 = ((__global double16 *)source)[5].S8;
  vstore3(tmp, 22, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s2 = ((__global double16 *)source)[5].SD;
  tmp.S0 = ((__global double16 *)source)[5].sF;
  vstore3(tmp, 23, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S2 = ((__global double16 *)source)[6].S3;
  tmp.s1 = ((__global double16 *)source)[6].s1;
  vstore3(tmp, 24, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[6].S7;
  tmp.S0 = ((__global double16 *)source)[6].S6;
  vstore3(tmp, 25, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S2 = ((__global double16 *)source)[6].s9;
  tmp.s0 = ((__global double16 *)source)[6].SA;
  vstore3(tmp, 26, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[6].SF;
  tmp.S2 = ((__global double16 *)source)[6].SF;
  vstore3(tmp, 27, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s2 = ((__global double16 *)source)[7].s1;
  tmp.s0 = ((__global double16 *)source)[7].S2;
  vstore3(tmp, 28, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S0 = ((__global double16 *)source)[7].S7;
  tmp.s2 = ((__global double16 *)source)[7].S4;
  vstore3(tmp, 29, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[7].s9;
  tmp.s2 = ((__global double16 *)source)[7].sB;
  vstore3(tmp, 30, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[7].SC;
  tmp.s1 = ((__global double16 *)source)[7].SE;
  vstore3(tmp, 31, (__global double *)dest);
}
