// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global float16 *source, __global float *dest) {
  if (get_global_id(0) != 0)
    return;
  // float16 src1 /*, src2*/;
  float3 tmp;
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[0].s0;
  vstore3(tmp, 0, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[1].se;
  vstore3(tmp, 1, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[2].Se;
  vstore3(tmp, 2, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[3].Sf;
  vstore3(tmp, 3, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[4].Sf;
  vstore3(tmp, 4, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[5].S4;
  vstore3(tmp, 5, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[6].s4;
  vstore3(tmp, 6, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[7].s4;
  vstore3(tmp, 7, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[8].SC;
  vstore3(tmp, 8, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[9].s6;
  vstore3(tmp, 9, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[10].s6;
  vstore3(tmp, 10, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[11].SF;
  tmp.S0 = ((__global float16 *)source)[11].s4;
  vstore3(tmp, 11, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[12].s2;
  tmp.S0 = ((__global float16 *)source)[12].sA;
  vstore3(tmp, 12, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[13].SF;
  tmp.s0 = ((__global float16 *)source)[13].SA;
  vstore3(tmp, 13, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[14].s4;
  tmp.S1 = ((__global float16 *)source)[14].s4;
  vstore3(tmp, 14, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[15].s1;
  tmp.S2 = ((__global float16 *)source)[15].S6;
  vstore3(tmp, 15, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[16].S0;
  tmp.s1 = ((__global float16 *)source)[16].s0;
  vstore3(tmp, 16, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[17].sD;
  tmp.S1 = ((__global float16 *)source)[17].SC;
  vstore3(tmp, 17, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[18].s9;
  tmp.s0 = ((__global float16 *)source)[18].S7;
  vstore3(tmp, 18, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[19].SB;
  tmp.s1 = ((__global float16 *)source)[19].S5;
  vstore3(tmp, 19, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[20].S6;
  tmp.s1 = ((__global float16 *)source)[20].sd;
  vstore3(tmp, 20, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[21].s4;
  tmp.s1 = ((__global float16 *)source)[21].S8;
  vstore3(tmp, 21, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[22].S0;
  tmp.S1 = ((__global float16 *)source)[22].sa;
  vstore3(tmp, 22, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[23].SD;
  tmp.s0 = ((__global float16 *)source)[23].S5;
  vstore3(tmp, 23, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[24].s7;
  tmp.s2 = ((__global float16 *)source)[24].s9;
  vstore3(tmp, 24, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[25].sE;
  tmp.s1 = ((__global float16 *)source)[25].SF;
  vstore3(tmp, 25, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[26].SC;
  tmp.S1 = ((__global float16 *)source)[26].S7;
  vstore3(tmp, 26, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[27].S6;
  tmp.S0 = ((__global float16 *)source)[27].S4;
  vstore3(tmp, 27, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[28].sd;
  tmp.S0 = ((__global float16 *)source)[28].S3;
  vstore3(tmp, 28, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[29].S2;
  tmp.S2 = ((__global float16 *)source)[29].S8;
  vstore3(tmp, 29, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[30].S1;
  tmp.s0 = ((__global float16 *)source)[30].Sb;
  vstore3(tmp, 30, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[31].s1;
  tmp.s2 = ((__global float16 *)source)[31].S6;
  vstore3(tmp, 31, (__global float *)dest);
}
