// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global float2 *source, __global float *dest) {
  if (get_global_id(0) != 0)
    return;
  // float2 src1 /*, src2*/;
  float3 tmp;
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[0].S1;
  vstore3(tmp, 0, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[0].s3;
  vstore3(tmp, 1, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[0].S4;
  vstore3(tmp, 2, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[0].s6;
  vstore3(tmp, 3, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[0].S9;
  vstore3(tmp, 4, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[0].sb;
  vstore3(tmp, 5, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[0].sD;
  vstore3(tmp, 6, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[0].sE;
  vstore3(tmp, 7, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[1].s0;
  vstore3(tmp, 8, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[1].s2;
  vstore3(tmp, 9, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[1].S4;
  vstore3(tmp, 10, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[1].s6;
  vstore3(tmp, 11, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[1].S9;
  vstore3(tmp, 12, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[1].sA;
  vstore3(tmp, 13, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[1].Sd;
  vstore3(tmp, 14, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[1].sF;
  vstore3(tmp, 15, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[2].s1;
  tmp.s1 = ((__global float16 *)source)[2].S1;
  vstore3(tmp, 16, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[2].s2;
  tmp.s2 = ((__global float16 *)source)[2].s2;
  vstore3(tmp, 17, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[2].S4;
  tmp.S2 = ((__global float16 *)source)[2].s5;
  vstore3(tmp, 18, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[2].S7;
  tmp.s1 = ((__global float16 *)source)[2].S6;
  vstore3(tmp, 19, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[2].s8;
  tmp.s0 = ((__global float16 *)source)[2].S9;
  vstore3(tmp, 20, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[2].SA;
  tmp.s1 = ((__global float16 *)source)[2].sA;
  vstore3(tmp, 21, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[2].sd;
  tmp.s1 = ((__global float16 *)source)[2].sC;
  vstore3(tmp, 22, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[2].SF;
  tmp.S2 = ((__global float16 *)source)[2].sE;
  vstore3(tmp, 23, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[3].S0;
  tmp.s1 = ((__global float16 *)source)[3].s0;
  vstore3(tmp, 24, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[3].s3;
  tmp.s2 = ((__global float16 *)source)[3].s3;
  vstore3(tmp, 25, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[3].s5;
  tmp.S0 = ((__global float16 *)source)[3].S5;
  vstore3(tmp, 26, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[3].S6;
  tmp.S0 = ((__global float16 *)source)[3].S7;
  vstore3(tmp, 27, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[3].s9;
  tmp.s1 = ((__global float16 *)source)[3].s8;
  vstore3(tmp, 28, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[3].Sb;
  tmp.s1 = ((__global float16 *)source)[3].sb;
  vstore3(tmp, 29, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[3].sD;
  tmp.S1 = ((__global float16 *)source)[3].sd;
  vstore3(tmp, 30, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[3].Se;
  tmp.s1 = ((__global float16 *)source)[3].SF;
  vstore3(tmp, 31, (__global float *)dest);
}
