// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global char8 *source, __global char *dest) {
  if (get_global_id(0) != 0)
    return;
  // char8 src1 /*, src2*/;
  char3 tmp;
  tmp = (char)((char)0);
  tmp.S1 = ((__global char16 *)source)[0].s1;
  vstore3(tmp, 0, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[0].S9;
  vstore3(tmp, 1, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S0 = ((__global char16 *)source)[1].s3;
  vstore3(tmp, 2, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s0 = ((__global char16 *)source)[1].sD;
  vstore3(tmp, 3, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S1 = ((__global char16 *)source)[2].s5;
  vstore3(tmp, 4, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[2].sf;
  vstore3(tmp, 5, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[3].S2;
  vstore3(tmp, 6, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S1 = ((__global char16 *)source)[3].SD;
  vstore3(tmp, 7, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s1 = ((__global char16 *)source)[4].s2;
  vstore3(tmp, 8, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[4].Sf;
  vstore3(tmp, 9, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S1 = ((__global char16 *)source)[5].s0;
  vstore3(tmp, 10, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s0 = ((__global char16 *)source)[5].SA;
  tmp.s1 = ((__global char16 *)source)[5].S8;
  vstore3(tmp, 11, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S2 = ((__global char16 *)source)[6].S6;
  tmp.S0 = ((__global char16 *)source)[6].s6;
  vstore3(tmp, 12, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[6].sa;
  tmp.s0 = ((__global char16 *)source)[6].Sa;
  vstore3(tmp, 13, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S2 = ((__global char16 *)source)[7].s2;
  tmp.s0 = ((__global char16 *)source)[7].S5;
  vstore3(tmp, 14, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S0 = ((__global char16 *)source)[7].sB;
  tmp.s2 = ((__global char16 *)source)[7].sb;
  vstore3(tmp, 15, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s1 = ((__global char16 *)source)[8].s7;
  tmp.S2 = ((__global char16 *)source)[8].s0;
  vstore3(tmp, 16, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S2 = ((__global char16 *)source)[8].SC;
  tmp.S1 = ((__global char16 *)source)[8].sf;
  vstore3(tmp, 17, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[9].S7;
  tmp.s1 = ((__global char16 *)source)[9].s6;
  vstore3(tmp, 18, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s0 = ((__global char16 *)source)[9].se;
  tmp.S2 = ((__global char16 *)source)[9].sD;
  vstore3(tmp, 19, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s0 = ((__global char16 *)source)[10].S3;
  tmp.S1 = ((__global char16 *)source)[10].S0;
  vstore3(tmp, 20, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[10].s8;
  tmp.s1 = ((__global char16 *)source)[10].S9;
  vstore3(tmp, 21, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S1 = ((__global char16 *)source)[11].S7;
  tmp.s2 = ((__global char16 *)source)[11].S5;
  vstore3(tmp, 22, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s1 = ((__global char16 *)source)[11].sF;
  tmp.S0 = ((__global char16 *)source)[11].sA;
  vstore3(tmp, 23, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[12].S5;
  tmp.s1 = ((__global char16 *)source)[12].s1;
  vstore3(tmp, 24, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[12].s8;
  tmp.s1 = ((__global char16 *)source)[12].sD;
  vstore3(tmp, 25, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S2 = ((__global char16 *)source)[13].S6;
  tmp.S1 = ((__global char16 *)source)[13].s6;
  vstore3(tmp, 26, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s1 = ((__global char16 *)source)[13].s8;
  tmp.s2 = ((__global char16 *)source)[13].sE;
  vstore3(tmp, 27, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S0 = ((__global char16 *)source)[14].s0;
  tmp.s1 = ((__global char16 *)source)[14].S0;
  vstore3(tmp, 28, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[14].SE;
  tmp.S0 = ((__global char16 *)source)[14].sE;
  vstore3(tmp, 29, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S1 = ((__global char16 *)source)[15].S1;
  tmp.s0 = ((__global char16 *)source)[15].s7;
  vstore3(tmp, 30, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S2 = ((__global char16 *)source)[15].sE;
  tmp.s1 = ((__global char16 *)source)[15].SC;
  vstore3(tmp, 31, (__global char *)dest);
}
