// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
double4 shuffle_fn(double4 source);
double4 shuffle_fn(double4 source) { return source; }

__kernel void sample_test(__global double4 *source, __global double *dest) {
  if (get_global_id(0) != 0)
    return;
  // double4 src1 /*, src2*/;
  double tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[0]).S1;
  dest[0] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[1]).S1;
  dest[1] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[2]).S3;
  dest[2] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[3]).s3;
  dest[3] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[4]).s1;
  dest[4] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[5]).s0;
  dest[5] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[6]).s3;
  dest[6] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[7]).S0;
  dest[7] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[8]).s1;
  dest[8] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[9]).s3;
  dest[9] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[10]).S2;
  dest[10] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[11]).S3;
  dest[11] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[12]).s1;
  dest[12] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[13]).s0;
  dest[13] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[14]).S0;
  dest[14] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[15]).S0;
  dest[15] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[16]).s0;
  dest[16] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[17]).S1;
  dest[17] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[18]).s2;
  dest[18] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[19]).s1;
  dest[19] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[20]).s0;
  dest[20] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[21]).S2;
  dest[21] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[22]).s0;
  dest[22] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[23]).S3;
  dest[23] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[24]).s0;
  dest[24] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[25]).s0;
  dest[25] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[26]).s2;
  dest[26] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[27]).s1;
  dest[27] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[28]).s1;
  dest[28] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[29]).S2;
  dest[29] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[30]).s2;
  dest[30] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[31]).S1;
  dest[31] = tmp;
}
