// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global long16 *source, __global long *dest) {
  if (get_global_id(0) != 0)
    return;
  // long16 src1 /*, src2*/;
  long3 tmp;
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[0].s2;
  vstore3(tmp, 0, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[1].s5;
  vstore3(tmp, 1, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[2].s4;
  vstore3(tmp, 2, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[3].sE;
  vstore3(tmp, 3, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[4].sc;
  vstore3(tmp, 4, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[5].s1;
  vstore3(tmp, 5, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[6].s5;
  vstore3(tmp, 6, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[7].s9;
  vstore3(tmp, 7, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[8].S6;
  vstore3(tmp, 8, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[9].sc;
  vstore3(tmp, 9, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[10].s8;
  vstore3(tmp, 10, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[11].Se;
  tmp.S0 = ((__global long16 *)source)[11].sf;
  vstore3(tmp, 11, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[12].S0;
  tmp.S0 = ((__global long16 *)source)[12].s0;
  vstore3(tmp, 12, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[13].s5;
  tmp.S1 = ((__global long16 *)source)[13].sF;
  vstore3(tmp, 13, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[14].s0;
  tmp.S0 = ((__global long16 *)source)[14].s7;
  vstore3(tmp, 14, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[15].S9;
  tmp.S2 = ((__global long16 *)source)[15].S0;
  vstore3(tmp, 15, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[16].sb;
  tmp.S1 = ((__global long16 *)source)[16].S1;
  vstore3(tmp, 16, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[17].S2;
  tmp.S1 = ((__global long16 *)source)[17].S4;
  vstore3(tmp, 17, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[18].sc;
  tmp.S2 = ((__global long16 *)source)[18].s1;
  vstore3(tmp, 18, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[19].s1;
  tmp.s2 = ((__global long16 *)source)[19].sd;
  vstore3(tmp, 19, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[20].se;
  tmp.S0 = ((__global long16 *)source)[20].SE;
  vstore3(tmp, 20, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[21].s3;
  tmp.S2 = ((__global long16 *)source)[21].s4;
  vstore3(tmp, 21, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[22].SD;
  tmp.S1 = ((__global long16 *)source)[22].sE;
  vstore3(tmp, 22, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[23].s1;
  tmp.s0 = ((__global long16 *)source)[23].SD;
  vstore3(tmp, 23, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[24].s4;
  tmp.s1 = ((__global long16 *)source)[24].sC;
  vstore3(tmp, 24, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[25].s9;
  tmp.S0 = ((__global long16 *)source)[25].s1;
  vstore3(tmp, 25, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[26].sf;
  tmp.s2 = ((__global long16 *)source)[26].S2;
  vstore3(tmp, 26, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[27].s7;
  tmp.s0 = ((__global long16 *)source)[27].S8;
  vstore3(tmp, 27, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[28].sd;
  tmp.S2 = ((__global long16 *)source)[28].S0;
  vstore3(tmp, 28, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[29].S2;
  tmp.S0 = ((__global long16 *)source)[29].s4;
  vstore3(tmp, 29, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[30].sc;
  tmp.s2 = ((__global long16 *)source)[30].Sc;
  vstore3(tmp, 30, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[31].s7;
  tmp.S2 = ((__global long16 *)source)[31].s0;
  vstore3(tmp, 31, (__global long *)dest);
}
