// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global uchar4 *source, __global uchar *dest) {
  if (get_global_id(0) != 0)
    return;
  // uchar4 src1 /*, src2*/;
  uchar3 tmp;
  tmp = (uchar)((uchar)0);
  tmp.S1 = ((__global uchar16 *)source)[0].S1;
  vstore3(tmp, 0, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S0 = ((__global uchar16 *)source)[0].S5;
  vstore3(tmp, 1, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S0 = ((__global uchar16 *)source)[0].sB;
  vstore3(tmp, 2, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s2 = ((__global uchar16 *)source)[0].sC;
  vstore3(tmp, 3, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S2 = ((__global uchar16 *)source)[1].s2;
  vstore3(tmp, 4, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S2 = ((__global uchar16 *)source)[1].s6;
  vstore3(tmp, 5, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S2 = ((__global uchar16 *)source)[1].S8;
  vstore3(tmp, 6, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S0 = ((__global uchar16 *)source)[1].SE;
  vstore3(tmp, 7, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s1 = ((__global uchar16 *)source)[2].s1;
  vstore3(tmp, 8, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S1 = ((__global uchar16 *)source)[2].s4;
  vstore3(tmp, 9, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[2].s9;
  vstore3(tmp, 10, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S1 = ((__global uchar16 *)source)[2].se;
  tmp.S0 = ((__global uchar16 *)source)[2].sc;
  vstore3(tmp, 11, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S0 = ((__global uchar16 *)source)[3].s0;
  tmp.s1 = ((__global uchar16 *)source)[3].S3;
  vstore3(tmp, 12, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S0 = ((__global uchar16 *)source)[3].S4;
  tmp.S1 = ((__global uchar16 *)source)[3].s4;
  vstore3(tmp, 13, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s2 = ((__global uchar16 *)source)[3].sa;
  tmp.s0 = ((__global uchar16 *)source)[3].s9;
  vstore3(tmp, 14, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S1 = ((__global uchar16 *)source)[3].Sd;
  tmp.s0 = ((__global uchar16 *)source)[3].SF;
  vstore3(tmp, 15, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S2 = ((__global uchar16 *)source)[4].s1;
  tmp.s1 = ((__global uchar16 *)source)[4].S3;
  vstore3(tmp, 16, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s2 = ((__global uchar16 *)source)[4].S5;
  tmp.s0 = ((__global uchar16 *)source)[4].s4;
  vstore3(tmp, 17, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S2 = ((__global uchar16 *)source)[4].sB;
  tmp.s1 = ((__global uchar16 *)source)[4].S9;
  vstore3(tmp, 18, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S1 = ((__global uchar16 *)source)[4].SC;
  tmp.S2 = ((__global uchar16 *)source)[4].se;
  vstore3(tmp, 19, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S0 = ((__global uchar16 *)source)[5].s3;
  tmp.S1 = ((__global uchar16 *)source)[5].s0;
  vstore3(tmp, 20, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S2 = ((__global uchar16 *)source)[5].S4;
  tmp.s0 = ((__global uchar16 *)source)[5].s7;
  vstore3(tmp, 21, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S1 = ((__global uchar16 *)source)[5].S9;
  tmp.S2 = ((__global uchar16 *)source)[5].Sb;
  vstore3(tmp, 22, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S1 = ((__global uchar16 *)source)[5].Sc;
  tmp.S0 = ((__global uchar16 *)source)[5].SF;
  vstore3(tmp, 23, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[6].s3;
  tmp.s2 = ((__global uchar16 *)source)[6].s2;
  vstore3(tmp, 24, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S2 = ((__global uchar16 *)source)[6].S7;
  tmp.S0 = ((__global uchar16 *)source)[6].s6;
  vstore3(tmp, 25, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S2 = ((__global uchar16 *)source)[6].s9;
  tmp.S1 = ((__global uchar16 *)source)[6].Sa;
  vstore3(tmp, 26, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[6].sE;
  tmp.S2 = ((__global uchar16 *)source)[6].SE;
  vstore3(tmp, 27, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[7].s2;
  tmp.s2 = ((__global uchar16 *)source)[7].s3;
  vstore3(tmp, 28, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S2 = ((__global uchar16 *)source)[7].s4;
  tmp.s1 = ((__global uchar16 *)source)[7].s5;
  vstore3(tmp, 29, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S1 = ((__global uchar16 *)source)[7].Sb;
  tmp.S0 = ((__global uchar16 *)source)[7].SA;
  vstore3(tmp, 30, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S2 = ((__global uchar16 *)source)[7].SE;
  tmp.s0 = ((__global uchar16 *)source)[7].sc;
  vstore3(tmp, 31, (__global uchar *)dest);
}
