// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global ulong *source, __global ulong *dest) {
  if (get_global_id(0) != 0)
    return;
  // ulong3 src1 /*, src2*/;
  ulong3 tmp;
  tmp = (ulong)((ulong)0);
  tmp.S2 = ((__global ulong16 *)source)[0].s0;
  vstore3(tmp, 0, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[0].s3;
  vstore3(tmp, 1, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S1 = ((__global ulong16 *)source)[0].S8;
  vstore3(tmp, 2, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S0 = ((__global ulong16 *)source)[0].Sa;
  vstore3(tmp, 3, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[0].sd;
  vstore3(tmp, 4, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S0 = ((__global ulong16 *)source)[0].sF;
  vstore3(tmp, 5, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S0 = ((__global ulong16 *)source)[1].S2;
  vstore3(tmp, 6, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[1].S6;
  vstore3(tmp, 7, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S2 = ((__global ulong16 *)source)[1].S9;
  vstore3(tmp, 8, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S0 = ((__global ulong16 *)source)[1].SC;
  vstore3(tmp, 9, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s2 = ((__global ulong16 *)source)[2].s0;
  vstore3(tmp, 10, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[2].S2;
  tmp.S1 = ((__global ulong16 *)source)[2].S3;
  vstore3(tmp, 11, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s1 = ((__global ulong16 *)source)[2].s4;
  tmp.S2 = ((__global ulong16 *)source)[2].S4;
  vstore3(tmp, 12, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[2].S9;
  tmp.s2 = ((__global ulong16 *)source)[2].s7;
  vstore3(tmp, 13, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s2 = ((__global ulong16 *)source)[2].sa;
  tmp.S0 = ((__global ulong16 *)source)[2].SA;
  vstore3(tmp, 14, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S2 = ((__global ulong16 *)source)[2].Sd;
  tmp.S0 = ((__global ulong16 *)source)[2].sd;
  vstore3(tmp, 15, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S0 = ((__global ulong16 *)source)[3].S1;
  tmp.s1 = ((__global ulong16 *)source)[3].s2;
  vstore3(tmp, 16, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s2 = ((__global ulong16 *)source)[3].S4;
  tmp.S0 = ((__global ulong16 *)source)[3].S5;
  vstore3(tmp, 17, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[3].S7;
  tmp.s1 = ((__global ulong16 *)source)[3].S6;
  vstore3(tmp, 18, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[3].Sa;
  tmp.s1 = ((__global ulong16 *)source)[3].S9;
  vstore3(tmp, 19, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[3].se;
  tmp.s2 = ((__global ulong16 *)source)[3].sC;
  vstore3(tmp, 20, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[3].SF;
  tmp.s2 = ((__global ulong16 *)source)[4].s0;
  vstore3(tmp, 21, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S1 = ((__global ulong16 *)source)[4].s4;
  tmp.S2 = ((__global ulong16 *)source)[4].s4;
  vstore3(tmp, 22, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s2 = ((__global ulong16 *)source)[4].s6;
  tmp.S1 = ((__global ulong16 *)source)[4].s5;
  vstore3(tmp, 23, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S2 = ((__global ulong16 *)source)[4].s8;
  tmp.s0 = ((__global ulong16 *)source)[4].S9;
  vstore3(tmp, 24, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S2 = ((__global ulong16 *)source)[4].SB;
  tmp.S0 = ((__global ulong16 *)source)[4].sC;
  vstore3(tmp, 25, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S0 = ((__global ulong16 *)source)[4].Se;
  tmp.s2 = ((__global ulong16 *)source)[5].s0;
  vstore3(tmp, 26, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S0 = ((__global ulong16 *)source)[5].S2;
  tmp.S1 = ((__global ulong16 *)source)[5].S3;
  vstore3(tmp, 27, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S2 = ((__global ulong16 *)source)[5].S5;
  tmp.s0 = ((__global ulong16 *)source)[5].S5;
  vstore3(tmp, 28, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[5].S7;
  tmp.S2 = ((__global ulong16 *)source)[5].s8;
  vstore3(tmp, 29, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S2 = ((__global ulong16 *)source)[5].Sc;
  tmp.S0 = ((__global ulong16 *)source)[5].sb;
  vstore3(tmp, 30, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S2 = ((__global ulong16 *)source)[5].sf;
  tmp.S0 = ((__global ulong16 *)source)[5].sD;
  vstore3(tmp, 31, (__global ulong *)dest);
}
