// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
double2 shuffle_fn(double2 source);
double2 shuffle_fn(double2 source) { return source; }

__kernel void sample_test(__global double2 *source, __global double2 *dest) {
  if (get_global_id(0) != 0)
    return;
  // double2 src1 /*, src2*/;
  double2 tmp;
  tmp = (double2)((double)0);
  tmp.S1 = shuffle_fn(source[0]).s1;
  dest[0] = tmp;
  tmp = (double2)((double)0);
  tmp.S0 = shuffle_fn(source[1]).s1;
  dest[1] = tmp;
  tmp = (double2)((double)0);
  tmp.s0 = shuffle_fn(source[2]).s0;
  dest[2] = tmp;
  tmp = (double2)((double)0);
  tmp.s1 = shuffle_fn(source[3]).S0;
  dest[3] = tmp;
  tmp = (double2)((double)0);
  tmp.s0 = shuffle_fn(source[4]).S0;
  dest[4] = tmp;
  tmp = (double2)((double)0);
  tmp.S0 = shuffle_fn(source[5]).s0;
  dest[5] = tmp;
  tmp = (double2)((double)0);
  tmp.S1 = shuffle_fn(source[6]).S1;
  dest[6] = tmp;
  tmp = (double2)((double)0);
  tmp.S1 = shuffle_fn(source[7]).s1;
  dest[7] = tmp;
  tmp = (double2)((double)0);
  tmp.s0 = shuffle_fn(source[8]).S1;
  dest[8] = tmp;
  tmp = (double2)((double)0);
  tmp.S1 = shuffle_fn(source[9]).S1;
  dest[9] = tmp;
  tmp = (double2)((double)0);
  tmp.s1 = shuffle_fn(source[10]).S1;
  dest[10] = tmp;
  tmp = (double2)((double)0);
  tmp.s0 = shuffle_fn(source[11]).s0;
  dest[11] = tmp;
  tmp = (double2)((double)0);
  tmp.S0 = shuffle_fn(source[12]).s1;
  dest[12] = tmp;
  tmp = (double2)((double)0);
  tmp.s1 = shuffle_fn(source[13]).S0;
  dest[13] = tmp;
  tmp = (double2)((double)0);
  tmp.S0 = shuffle_fn(source[14]).S1;
  dest[14] = tmp;
  tmp = (double2)((double)0);
  tmp.s0 = shuffle_fn(source[15]).s0;
  dest[15] = tmp;
  tmp = (double2)((double)0);
  tmp.s10 = shuffle_fn(source[16]).S10;
  dest[16] = tmp;
  tmp = (double2)((double)0);
  tmp.s01 = shuffle_fn(source[17]).s00;
  dest[17] = tmp;
  tmp = (double2)((double)0);
  tmp.s10 = shuffle_fn(source[18]).s10;
  dest[18] = tmp;
  tmp = (double2)((double)0);
  tmp.s10 = shuffle_fn(source[19]).s10;
  dest[19] = tmp;
  tmp = (double2)((double)0);
  tmp.s01 = shuffle_fn(source[20]).s11;
  dest[20] = tmp;
  tmp = (double2)((double)0);
  tmp.s01 = shuffle_fn(source[21]).S10;
  dest[21] = tmp;
  tmp = (double2)((double)0);
  tmp.S01 = shuffle_fn(source[22]).S10;
  dest[22] = tmp;
  tmp = (double2)((double)0);
  tmp.S01 = shuffle_fn(source[23]).s01;
  dest[23] = tmp;
  tmp = (double2)((double)0);
  tmp.s01 = shuffle_fn(source[24]).S10;
  dest[24] = tmp;
  tmp = (double2)((double)0);
  tmp.S10 = shuffle_fn(source[25]).S01;
  dest[25] = tmp;
  tmp = (double2)((double)0);
  tmp.S10 = shuffle_fn(source[26]).S00;
  dest[26] = tmp;
  tmp = (double2)((double)0);
  tmp.s01 = shuffle_fn(source[27]).s00;
  dest[27] = tmp;
  tmp = (double2)((double)0);
  tmp.s01 = shuffle_fn(source[28]).S10;
  dest[28] = tmp;
  tmp = (double2)((double)0);
  tmp.s01 = shuffle_fn(source[29]).S10;
  dest[29] = tmp;
  tmp = (double2)((double)0);
  tmp.S01 = shuffle_fn(source[30]).S01;
  dest[30] = tmp;
  tmp = (double2)((double)0);
  tmp.s01 = shuffle_fn(source[31]).S00;
  dest[31] = tmp;
}
