// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global float *source, __global float *dest) {
  if (get_global_id(0) != 0)
    return;
  // float3 src1 /*, src2*/;
  float3 tmp;
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[0].S0;
  vstore3(tmp, 0, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[0].S5;
  vstore3(tmp, 1, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[0].S8;
  vstore3(tmp, 2, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[0].S9;
  vstore3(tmp, 3, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[0].sD;
  vstore3(tmp, 4, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[0].sF;
  vstore3(tmp, 5, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[1].s2;
  vstore3(tmp, 6, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[1].s7;
  vstore3(tmp, 7, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[1].s9;
  vstore3(tmp, 8, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[1].sC;
  vstore3(tmp, 9, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[1].sf;
  vstore3(tmp, 10, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[2].S3;
  tmp.s0 = ((__global float16 *)source)[2].s1;
  vstore3(tmp, 11, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[2].S4;
  tmp.S0 = ((__global float16 *)source)[2].S6;
  vstore3(tmp, 12, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[2].S7;
  tmp.s1 = ((__global float16 *)source)[2].S9;
  vstore3(tmp, 13, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[2].sB;
  tmp.S1 = ((__global float16 *)source)[2].SB;
  vstore3(tmp, 14, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[2].Sf;
  tmp.S2 = ((__global float16 *)source)[2].SD;
  vstore3(tmp, 15, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[3].s2;
  tmp.S2 = ((__global float16 *)source)[3].s1;
  vstore3(tmp, 16, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[3].s3;
  tmp.S0 = ((__global float16 *)source)[3].s5;
  vstore3(tmp, 17, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[3].s6;
  tmp.s2 = ((__global float16 *)source)[3].s7;
  vstore3(tmp, 18, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[3].sA;
  tmp.S1 = ((__global float16 *)source)[3].Sb;
  vstore3(tmp, 19, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[3].Sc;
  tmp.S2 = ((__global float16 *)source)[3].Sc;
  vstore3(tmp, 20, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[3].sf;
  tmp.S0 = ((__global float16 *)source)[4].s1;
  vstore3(tmp, 21, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[4].s3;
  tmp.s1 = ((__global float16 *)source)[4].s4;
  vstore3(tmp, 22, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[4].S5;
  tmp.s2 = ((__global float16 *)source)[4].s7;
  vstore3(tmp, 23, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[4].s9;
  tmp.S2 = ((__global float16 *)source)[4].sa;
  vstore3(tmp, 24, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[4].sB;
  tmp.s0 = ((__global float16 *)source)[4].SB;
  vstore3(tmp, 25, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[4].SE;
  tmp.s1 = ((__global float16 *)source)[4].Se;
  vstore3(tmp, 26, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[5].s2;
  tmp.S2 = ((__global float16 *)source)[5].S2;
  vstore3(tmp, 27, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[5].s4;
  tmp.S2 = ((__global float16 *)source)[5].S4;
  vstore3(tmp, 28, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[5].S9;
  tmp.s0 = ((__global float16 *)source)[5].s8;
  vstore3(tmp, 29, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[5].sA;
  tmp.S2 = ((__global float16 *)source)[5].Sa;
  vstore3(tmp, 30, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[5].Sd;
  tmp.s1 = ((__global float16 *)source)[5].SE;
  vstore3(tmp, 31, (__global float *)dest);
}
