// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global uint4 *source, __global uint *dest) {
  if (get_global_id(0) != 0)
    return;
  // uint4 src1 /*, src2*/;
  uint3 tmp;
  tmp = (uint)((uint)0);
  tmp.s0 = ((__global uint16 *)source)[0].S0;
  vstore3(tmp, 0, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[0].S7;
  vstore3(tmp, 1, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s0 = ((__global uint16 *)source)[0].sB;
  vstore3(tmp, 2, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s1 = ((__global uint16 *)source)[0].sc;
  vstore3(tmp, 3, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[1].S3;
  vstore3(tmp, 4, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[1].s6;
  vstore3(tmp, 5, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S1 = ((__global uint16 *)source)[1].sb;
  vstore3(tmp, 6, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[1].Sd;
  vstore3(tmp, 7, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[2].S0;
  vstore3(tmp, 8, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s0 = ((__global uint16 *)source)[2].s5;
  vstore3(tmp, 9, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[2].sa;
  vstore3(tmp, 10, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S2 = ((__global uint16 *)source)[2].sD;
  tmp.s0 = ((__global uint16 *)source)[2].SF;
  vstore3(tmp, 11, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[3].S0;
  tmp.s0 = ((__global uint16 *)source)[3].s1;
  vstore3(tmp, 12, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S1 = ((__global uint16 *)source)[3].s6;
  tmp.s0 = ((__global uint16 *)source)[3].S7;
  vstore3(tmp, 13, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[3].s8;
  tmp.S1 = ((__global uint16 *)source)[3].Sa;
  vstore3(tmp, 14, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[3].Sd;
  tmp.s0 = ((__global uint16 *)source)[3].Sd;
  vstore3(tmp, 15, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s0 = ((__global uint16 *)source)[4].S3;
  tmp.S2 = ((__global uint16 *)source)[4].S2;
  vstore3(tmp, 16, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[4].s6;
  tmp.s1 = ((__global uint16 *)source)[4].S5;
  vstore3(tmp, 17, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s1 = ((__global uint16 *)source)[4].s9;
  tmp.s0 = ((__global uint16 *)source)[4].s9;
  vstore3(tmp, 18, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[4].sF;
  tmp.S2 = ((__global uint16 *)source)[4].sd;
  vstore3(tmp, 19, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s1 = ((__global uint16 *)source)[5].S1;
  tmp.S2 = ((__global uint16 *)source)[5].S2;
  vstore3(tmp, 20, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[5].s4;
  tmp.S0 = ((__global uint16 *)source)[5].s7;
  vstore3(tmp, 21, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s1 = ((__global uint16 *)source)[5].s9;
  tmp.s0 = ((__global uint16 *)source)[5].s8;
  vstore3(tmp, 22, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s0 = ((__global uint16 *)source)[5].sf;
  tmp.S2 = ((__global uint16 *)source)[5].Se;
  vstore3(tmp, 23, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s1 = ((__global uint16 *)source)[6].S2;
  tmp.s2 = ((__global uint16 *)source)[6].s0;
  vstore3(tmp, 24, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S1 = ((__global uint16 *)source)[6].S4;
  tmp.s2 = ((__global uint16 *)source)[6].S6;
  vstore3(tmp, 25, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[6].Sa;
  tmp.S1 = ((__global uint16 *)source)[6].S9;
  vstore3(tmp, 26, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S2 = ((__global uint16 *)source)[6].sD;
  tmp.S1 = ((__global uint16 *)source)[6].sD;
  vstore3(tmp, 27, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S1 = ((__global uint16 *)source)[7].S0;
  tmp.s2 = ((__global uint16 *)source)[7].s3;
  vstore3(tmp, 28, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[7].S4;
  tmp.S1 = ((__global uint16 *)source)[7].S4;
  vstore3(tmp, 29, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[7].S9;
  tmp.s1 = ((__global uint16 *)source)[7].S9;
  vstore3(tmp, 30, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[7].Sf;
  tmp.S1 = ((__global uint16 *)source)[7].Sf;
  vstore3(tmp, 31, (__global uint *)dest);
}
