// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
__kernel void sample_test(__global double4 *source, __global double *dest) {
  if (get_global_id(0) != 0)
    return;
  // double4 src1 /*, src2*/;
  double3 tmp;
  tmp = (double)((double)0);
  tmp.S0 = ((__global double16 *)source)[0].s1;
  vstore3(tmp, 0, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S0 = ((__global double16 *)source)[0].s5;
  vstore3(tmp, 1, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[0].S9;
  vstore3(tmp, 2, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[0].Sf;
  vstore3(tmp, 3, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[1].s3;
  vstore3(tmp, 4, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[1].S7;
  vstore3(tmp, 5, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S0 = ((__global double16 *)source)[1].s9;
  vstore3(tmp, 6, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[1].sc;
  vstore3(tmp, 7, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[2].s3;
  vstore3(tmp, 8, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[2].s5;
  vstore3(tmp, 9, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[2].sB;
  vstore3(tmp, 10, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S0 = ((__global double16 *)source)[2].Sd;
  tmp.S2 = ((__global double16 *)source)[2].Sf;
  vstore3(tmp, 11, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[3].S0;
  tmp.S2 = ((__global double16 *)source)[3].s2;
  vstore3(tmp, 12, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[3].S6;
  tmp.S2 = ((__global double16 *)source)[3].S7;
  vstore3(tmp, 13, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[3].s9;
  tmp.S1 = ((__global double16 *)source)[3].Sb;
  vstore3(tmp, 14, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S2 = ((__global double16 *)source)[3].SD;
  tmp.S1 = ((__global double16 *)source)[3].se;
  vstore3(tmp, 15, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[4].s1;
  tmp.s2 = ((__global double16 *)source)[4].s3;
  vstore3(tmp, 16, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s2 = ((__global double16 *)source)[4].S6;
  tmp.S0 = ((__global double16 *)source)[4].S6;
  vstore3(tmp, 17, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S0 = ((__global double16 *)source)[4].SA;
  tmp.s2 = ((__global double16 *)source)[4].sB;
  vstore3(tmp, 18, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S0 = ((__global double16 *)source)[4].sc;
  tmp.S1 = ((__global double16 *)source)[4].sF;
  vstore3(tmp, 19, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s2 = ((__global double16 *)source)[5].S0;
  tmp.s1 = ((__global double16 *)source)[5].s2;
  vstore3(tmp, 20, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[5].s6;
  tmp.S2 = ((__global double16 *)source)[5].s5;
  vstore3(tmp, 21, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[5].sa;
  tmp.s1 = ((__global double16 *)source)[5].SB;
  vstore3(tmp, 22, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[5].SD;
  tmp.s2 = ((__global double16 *)source)[5].sC;
  vstore3(tmp, 23, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s2 = ((__global double16 *)source)[6].S3;
  tmp.s0 = ((__global double16 *)source)[6].s3;
  vstore3(tmp, 24, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[6].s7;
  tmp.S2 = ((__global double16 *)source)[6].S4;
  vstore3(tmp, 25, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[6].S8;
  tmp.s0 = ((__global double16 *)source)[6].s8;
  vstore3(tmp, 26, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[6].sf;
  tmp.s2 = ((__global double16 *)source)[6].sf;
  vstore3(tmp, 27, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[7].S2;
  tmp.S1 = ((__global double16 *)source)[7].s2;
  vstore3(tmp, 28, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[7].s7;
  tmp.S0 = ((__global double16 *)source)[7].s6;
  vstore3(tmp, 29, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[7].sb;
  tmp.S0 = ((__global double16 *)source)[7].S9;
  vstore3(tmp, 30, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S2 = ((__global double16 *)source)[7].sf;
  tmp.s1 = ((__global double16 *)source)[7].Sc;
  vstore3(tmp, 31, (__global double *)dest);
}
