// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
double2 shuffle_fn(double2 source);
double2 shuffle_fn(double2 source) { return source; }

__kernel void sample_test(__global double2 *source, __global double *dest) {
  if (get_global_id(0) != 0)
    return;
  // double2 src1 /*, src2*/;
  double tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[0]).S0;
  dest[0] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[1]).s1;
  dest[1] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[2]).S1;
  dest[2] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[3]).S1;
  dest[3] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[4]).s1;
  dest[4] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[5]).s1;
  dest[5] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[6]).s1;
  dest[6] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[7]).s1;
  dest[7] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[8]).s0;
  dest[8] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[9]).S1;
  dest[9] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[10]).s0;
  dest[10] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[11]).S1;
  dest[11] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[12]).S0;
  dest[12] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[13]).s1;
  dest[13] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[14]).S0;
  dest[14] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[15]).S1;
  dest[15] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[16]).s0;
  dest[16] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[17]).s1;
  dest[17] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[18]).S1;
  dest[18] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[19]).S0;
  dest[19] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[20]).s0;
  dest[20] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[21]).S1;
  dest[21] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[22]).S0;
  dest[22] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[23]).s1;
  dest[23] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[24]).s1;
  dest[24] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[25]).S1;
  dest[25] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[26]).s0;
  dest[26] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[27]).S0;
  dest[27] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[28]).S1;
  dest[28] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[29]).S0;
  dest[29] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[30]).s1;
  dest[30] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[31]).s0;
  dest[31] = tmp;
}
