// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global uchar *source, __global uchar *dest) {
  if (get_global_id(0) != 0)
    return;
  // uchar3 src1 /*, src2*/;
  uchar3 tmp;
  tmp = (uchar)((uchar)0);
  tmp.S0 = ((__global uchar16 *)source)[0].s2;
  vstore3(tmp, 0, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S2 = ((__global uchar16 *)source)[0].S3;
  vstore3(tmp, 1, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s2 = ((__global uchar16 *)source)[0].s8;
  vstore3(tmp, 2, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S2 = ((__global uchar16 *)source)[0].s9;
  vstore3(tmp, 3, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S2 = ((__global uchar16 *)source)[0].sE;
  vstore3(tmp, 4, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S0 = ((__global uchar16 *)source)[1].S0;
  vstore3(tmp, 5, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[1].s3;
  vstore3(tmp, 6, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S1 = ((__global uchar16 *)source)[1].S5;
  vstore3(tmp, 7, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S0 = ((__global uchar16 *)source)[1].S9;
  vstore3(tmp, 8, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S0 = ((__global uchar16 *)source)[1].sB;
  vstore3(tmp, 9, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s1 = ((__global uchar16 *)source)[1].sE;
  vstore3(tmp, 10, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S0 = ((__global uchar16 *)source)[2].S1;
  tmp.s2 = ((__global uchar16 *)source)[2].s3;
  vstore3(tmp, 11, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S0 = ((__global uchar16 *)source)[2].s6;
  tmp.s2 = ((__global uchar16 *)source)[2].s4;
  vstore3(tmp, 12, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[2].S8;
  tmp.S1 = ((__global uchar16 *)source)[2].s9;
  vstore3(tmp, 13, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s2 = ((__global uchar16 *)source)[2].SB;
  tmp.s1 = ((__global uchar16 *)source)[2].sB;
  vstore3(tmp, 14, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[2].se;
  tmp.S1 = ((__global uchar16 *)source)[2].sf;
  vstore3(tmp, 15, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S1 = ((__global uchar16 *)source)[3].s0;
  tmp.S0 = ((__global uchar16 *)source)[3].S1;
  vstore3(tmp, 16, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[3].s4;
  tmp.S1 = ((__global uchar16 *)source)[3].S3;
  vstore3(tmp, 17, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s1 = ((__global uchar16 *)source)[3].s8;
  tmp.s0 = ((__global uchar16 *)source)[3].s6;
  vstore3(tmp, 18, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S2 = ((__global uchar16 *)source)[3].sa;
  tmp.s1 = ((__global uchar16 *)source)[3].Sb;
  vstore3(tmp, 19, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[3].Sc;
  tmp.S1 = ((__global uchar16 *)source)[3].Sd;
  vstore3(tmp, 20, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s1 = ((__global uchar16 *)source)[4].s0;
  tmp.s2 = ((__global uchar16 *)source)[4].s1;
  vstore3(tmp, 21, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s2 = ((__global uchar16 *)source)[4].S2;
  tmp.S1 = ((__global uchar16 *)source)[4].S4;
  vstore3(tmp, 22, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[4].S5;
  tmp.S2 = ((__global uchar16 *)source)[4].s5;
  vstore3(tmp, 23, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[4].s9;
  tmp.S2 = ((__global uchar16 *)source)[4].s8;
  vstore3(tmp, 24, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S0 = ((__global uchar16 *)source)[4].sb;
  tmp.S1 = ((__global uchar16 *)source)[4].SD;
  vstore3(tmp, 25, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s2 = ((__global uchar16 *)source)[4].sF;
  tmp.s1 = ((__global uchar16 *)source)[5].s0;
  vstore3(tmp, 26, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[5].s3;
  tmp.s2 = ((__global uchar16 *)source)[5].S3;
  vstore3(tmp, 27, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S1 = ((__global uchar16 *)source)[5].S6;
  tmp.s0 = ((__global uchar16 *)source)[5].S6;
  vstore3(tmp, 28, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s1 = ((__global uchar16 *)source)[5].S7;
  tmp.S2 = ((__global uchar16 *)source)[5].S9;
  vstore3(tmp, 29, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[5].sB;
  tmp.S1 = ((__global uchar16 *)source)[5].sA;
  vstore3(tmp, 30, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[5].sE;
  tmp.s1 = ((__global uchar16 *)source)[5].SF;
  vstore3(tmp, 31, (__global uchar *)dest);
}
