// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global long4 *source, __global long *dest) {
  if (get_global_id(0) != 0)
    return;
  // long4 src1 /*, src2*/;
  long3 tmp;
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[0].s0;
  vstore3(tmp, 0, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[0].S5;
  vstore3(tmp, 1, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[0].s8;
  vstore3(tmp, 2, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[0].Se;
  vstore3(tmp, 3, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[1].S0;
  vstore3(tmp, 4, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[1].s4;
  vstore3(tmp, 5, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[1].sa;
  vstore3(tmp, 6, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[1].sf;
  vstore3(tmp, 7, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[2].s2;
  vstore3(tmp, 8, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[2].S4;
  vstore3(tmp, 9, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[2].S9;
  vstore3(tmp, 10, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[2].SE;
  tmp.S1 = ((__global long16 *)source)[2].sE;
  vstore3(tmp, 11, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[3].s2;
  tmp.S2 = ((__global long16 *)source)[3].S2;
  vstore3(tmp, 12, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[3].s5;
  tmp.S1 = ((__global long16 *)source)[3].s5;
  vstore3(tmp, 13, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[3].sB;
  tmp.s1 = ((__global long16 *)source)[3].S8;
  vstore3(tmp, 14, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[3].sD;
  tmp.s1 = ((__global long16 *)source)[3].Se;
  vstore3(tmp, 15, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[4].s3;
  tmp.s0 = ((__global long16 *)source)[4].s3;
  vstore3(tmp, 16, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[4].S4;
  tmp.S2 = ((__global long16 *)source)[4].S7;
  vstore3(tmp, 17, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[4].S9;
  tmp.S0 = ((__global long16 *)source)[4].SA;
  vstore3(tmp, 18, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[4].Sc;
  tmp.s2 = ((__global long16 *)source)[4].SF;
  vstore3(tmp, 19, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[5].S1;
  tmp.S1 = ((__global long16 *)source)[5].s0;
  vstore3(tmp, 20, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[5].S7;
  tmp.S2 = ((__global long16 *)source)[5].S5;
  vstore3(tmp, 21, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[5].S8;
  tmp.S1 = ((__global long16 *)source)[5].S9;
  vstore3(tmp, 22, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[5].sf;
  tmp.s2 = ((__global long16 *)source)[5].SF;
  vstore3(tmp, 23, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[6].S2;
  tmp.S2 = ((__global long16 *)source)[6].s3;
  vstore3(tmp, 24, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[6].s4;
  tmp.s2 = ((__global long16 *)source)[6].S6;
  vstore3(tmp, 25, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[6].s9;
  tmp.s0 = ((__global long16 *)source)[6].Sa;
  vstore3(tmp, 26, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[6].Se;
  tmp.s2 = ((__global long16 *)source)[6].sE;
  vstore3(tmp, 27, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[7].S3;
  tmp.s0 = ((__global long16 *)source)[7].S3;
  vstore3(tmp, 28, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[7].s4;
  tmp.s2 = ((__global long16 *)source)[7].S7;
  vstore3(tmp, 29, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[7].Sb;
  tmp.S0 = ((__global long16 *)source)[7].S8;
  vstore3(tmp, 30, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[7].SE;
  tmp.S0 = ((__global long16 *)source)[7].SD;
  vstore3(tmp, 31, (__global long *)dest);
}
