// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global char2 *source, __global char *dest) {
  if (get_global_id(0) != 0)
    return;
  // char2 src1 /*, src2*/;
  char3 tmp;
  tmp = (char)((char)0);
  tmp.s1 = ((__global char16 *)source)[0].s0;
  vstore3(tmp, 0, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S0 = ((__global char16 *)source)[0].S2;
  vstore3(tmp, 1, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S1 = ((__global char16 *)source)[0].S5;
  vstore3(tmp, 2, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[0].S7;
  vstore3(tmp, 3, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S0 = ((__global char16 *)source)[0].S8;
  vstore3(tmp, 4, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S2 = ((__global char16 *)source)[0].sA;
  vstore3(tmp, 5, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s1 = ((__global char16 *)source)[0].Sc;
  vstore3(tmp, 6, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s0 = ((__global char16 *)source)[0].Sf;
  vstore3(tmp, 7, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s0 = ((__global char16 *)source)[1].s0;
  vstore3(tmp, 8, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s1 = ((__global char16 *)source)[1].s3;
  vstore3(tmp, 9, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S1 = ((__global char16 *)source)[1].s4;
  vstore3(tmp, 10, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S2 = ((__global char16 *)source)[1].s7;
  vstore3(tmp, 11, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[1].S9;
  vstore3(tmp, 12, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s0 = ((__global char16 *)source)[1].SA;
  vstore3(tmp, 13, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S2 = ((__global char16 *)source)[1].Sd;
  vstore3(tmp, 14, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S0 = ((__global char16 *)source)[1].Se;
  vstore3(tmp, 15, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S1 = ((__global char16 *)source)[2].s1;
  tmp.S2 = ((__global char16 *)source)[2].S1;
  vstore3(tmp, 16, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s0 = ((__global char16 *)source)[2].s2;
  tmp.s1 = ((__global char16 *)source)[2].S2;
  vstore3(tmp, 17, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s0 = ((__global char16 *)source)[2].s4;
  tmp.s2 = ((__global char16 *)source)[2].S4;
  vstore3(tmp, 18, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s0 = ((__global char16 *)source)[2].s6;
  tmp.s1 = ((__global char16 *)source)[2].S6;
  vstore3(tmp, 19, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s1 = ((__global char16 *)source)[2].s8;
  tmp.S0 = ((__global char16 *)source)[2].S9;
  vstore3(tmp, 20, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[2].sB;
  tmp.s1 = ((__global char16 *)source)[2].SA;
  vstore3(tmp, 21, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S0 = ((__global char16 *)source)[2].sd;
  tmp.S2 = ((__global char16 *)source)[2].SD;
  vstore3(tmp, 22, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S2 = ((__global char16 *)source)[2].SE;
  tmp.S1 = ((__global char16 *)source)[2].sF;
  vstore3(tmp, 23, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[3].s1;
  tmp.s1 = ((__global char16 *)source)[3].s0;
  vstore3(tmp, 24, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S0 = ((__global char16 *)source)[3].s2;
  tmp.s1 = ((__global char16 *)source)[3].s2;
  vstore3(tmp, 25, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s0 = ((__global char16 *)source)[3].s5;
  tmp.S2 = ((__global char16 *)source)[3].s4;
  vstore3(tmp, 26, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[3].s7;
  tmp.s1 = ((__global char16 *)source)[3].S6;
  vstore3(tmp, 27, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s0 = ((__global char16 *)source)[3].S8;
  tmp.S1 = ((__global char16 *)source)[3].s8;
  vstore3(tmp, 28, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S2 = ((__global char16 *)source)[3].SB;
  tmp.S0 = ((__global char16 *)source)[3].SA;
  vstore3(tmp, 29, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s1 = ((__global char16 *)source)[3].SD;
  tmp.s0 = ((__global char16 *)source)[3].Sd;
  vstore3(tmp, 30, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s0 = ((__global char16 *)source)[3].Sf;
  tmp.s2 = ((__global char16 *)source)[3].se;
  vstore3(tmp, 31, (__global char *)dest);
}
