// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global uint8 *source, __global uint *dest) {
  if (get_global_id(0) != 0)
    return;
  // uint8 src1 /*, src2*/;
  uint3 tmp;
  tmp = (uint)((uint)0);
  tmp.S1 = ((__global uint16 *)source)[0].s1;
  vstore3(tmp, 0, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S2 = ((__global uint16 *)source)[0].S9;
  vstore3(tmp, 1, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s0 = ((__global uint16 *)source)[1].s5;
  vstore3(tmp, 2, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S1 = ((__global uint16 *)source)[1].Sc;
  vstore3(tmp, 3, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s1 = ((__global uint16 *)source)[2].s0;
  vstore3(tmp, 4, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s0 = ((__global uint16 *)source)[2].S8;
  vstore3(tmp, 5, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S1 = ((__global uint16 *)source)[3].S3;
  vstore3(tmp, 6, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[3].s9;
  vstore3(tmp, 7, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s1 = ((__global uint16 *)source)[4].S1;
  vstore3(tmp, 8, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[4].Sb;
  vstore3(tmp, 9, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S2 = ((__global uint16 *)source)[5].s3;
  vstore3(tmp, 10, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s1 = ((__global uint16 *)source)[5].sD;
  tmp.s2 = ((__global uint16 *)source)[5].sa;
  vstore3(tmp, 11, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s1 = ((__global uint16 *)source)[6].S6;
  tmp.s2 = ((__global uint16 *)source)[6].S4;
  vstore3(tmp, 12, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[6].s8;
  tmp.S0 = ((__global uint16 *)source)[6].sf;
  vstore3(tmp, 13, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S2 = ((__global uint16 *)source)[7].s0;
  tmp.S0 = ((__global uint16 *)source)[7].s4;
  vstore3(tmp, 14, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s0 = ((__global uint16 *)source)[7].sE;
  tmp.s2 = ((__global uint16 *)source)[7].sE;
  vstore3(tmp, 15, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s1 = ((__global uint16 *)source)[8].s7;
  tmp.s2 = ((__global uint16 *)source)[8].s5;
  vstore3(tmp, 16, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S1 = ((__global uint16 *)source)[8].s9;
  tmp.s2 = ((__global uint16 *)source)[8].se;
  vstore3(tmp, 17, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s1 = ((__global uint16 *)source)[9].S2;
  tmp.s2 = ((__global uint16 *)source)[9].s5;
  vstore3(tmp, 18, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s1 = ((__global uint16 *)source)[9].Sf;
  tmp.S0 = ((__global uint16 *)source)[9].s9;
  vstore3(tmp, 19, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S1 = ((__global uint16 *)source)[10].S4;
  tmp.s0 = ((__global uint16 *)source)[10].s1;
  vstore3(tmp, 20, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S1 = ((__global uint16 *)source)[10].S9;
  tmp.S2 = ((__global uint16 *)source)[10].S8;
  vstore3(tmp, 21, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[11].S6;
  tmp.s2 = ((__global uint16 *)source)[11].s6;
  vstore3(tmp, 22, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S1 = ((__global uint16 *)source)[11].sB;
  tmp.s2 = ((__global uint16 *)source)[11].S8;
  vstore3(tmp, 23, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s0 = ((__global uint16 *)source)[12].s7;
  tmp.s2 = ((__global uint16 *)source)[12].s4;
  vstore3(tmp, 24, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S1 = ((__global uint16 *)source)[12].sa;
  tmp.S2 = ((__global uint16 *)source)[12].SD;
  vstore3(tmp, 25, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S1 = ((__global uint16 *)source)[13].s7;
  tmp.S2 = ((__global uint16 *)source)[13].S5;
  vstore3(tmp, 26, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S1 = ((__global uint16 *)source)[13].S8;
  tmp.s0 = ((__global uint16 *)source)[13].Sf;
  vstore3(tmp, 27, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s1 = ((__global uint16 *)source)[14].S6;
  tmp.s2 = ((__global uint16 *)source)[14].S2;
  vstore3(tmp, 28, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s0 = ((__global uint16 *)source)[14].Se;
  tmp.S1 = ((__global uint16 *)source)[14].sF;
  vstore3(tmp, 29, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s0 = ((__global uint16 *)source)[15].S5;
  tmp.S1 = ((__global uint16 *)source)[15].s3;
  vstore3(tmp, 30, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[15].sa;
  tmp.s1 = ((__global uint16 *)source)[15].Sa;
  vstore3(tmp, 31, (__global uint *)dest);
}
