// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
__kernel void sample_test(__global double2 *source, __global double *dest) {
  if (get_global_id(0) != 0)
    return;
  // double2 src1 /*, src2*/;
  double3 tmp;
  tmp = (double)((double)0);
  tmp.S0 = ((__global double16 *)source)[0].S1;
  vstore3(tmp, 0, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s2 = ((__global double16 *)source)[0].s2;
  vstore3(tmp, 1, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[0].s5;
  vstore3(tmp, 2, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S2 = ((__global double16 *)source)[0].s7;
  vstore3(tmp, 3, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S2 = ((__global double16 *)source)[0].s9;
  vstore3(tmp, 4, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S0 = ((__global double16 *)source)[0].sb;
  vstore3(tmp, 5, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S2 = ((__global double16 *)source)[0].SC;
  vstore3(tmp, 6, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[0].se;
  vstore3(tmp, 7, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S0 = ((__global double16 *)source)[1].S1;
  vstore3(tmp, 8, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[1].s3;
  vstore3(tmp, 9, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s2 = ((__global double16 *)source)[1].s4;
  vstore3(tmp, 10, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S2 = ((__global double16 *)source)[1].s6;
  vstore3(tmp, 11, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S2 = ((__global double16 *)source)[1].s9;
  vstore3(tmp, 12, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S0 = ((__global double16 *)source)[1].sA;
  vstore3(tmp, 13, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[1].Sd;
  vstore3(tmp, 14, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[1].se;
  vstore3(tmp, 15, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S2 = ((__global double16 *)source)[2].S1;
  tmp.S1 = ((__global double16 *)source)[2].S1;
  vstore3(tmp, 16, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[2].S3;
  tmp.S1 = ((__global double16 *)source)[2].s3;
  vstore3(tmp, 17, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S2 = ((__global double16 *)source)[2].S5;
  tmp.S1 = ((__global double16 *)source)[2].s4;
  vstore3(tmp, 18, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S0 = ((__global double16 *)source)[2].s6;
  tmp.S1 = ((__global double16 *)source)[2].S6;
  vstore3(tmp, 19, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[2].S9;
  tmp.s0 = ((__global double16 *)source)[2].S8;
  vstore3(tmp, 20, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S0 = ((__global double16 *)source)[2].SB;
  tmp.s2 = ((__global double16 *)source)[2].sb;
  vstore3(tmp, 21, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[2].sD;
  tmp.S2 = ((__global double16 *)source)[2].sD;
  vstore3(tmp, 22, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[2].se;
  tmp.S2 = ((__global double16 *)source)[2].sf;
  vstore3(tmp, 23, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s2 = ((__global double16 *)source)[3].s0;
  tmp.s1 = ((__global double16 *)source)[3].S1;
  vstore3(tmp, 24, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s2 = ((__global double16 *)source)[3].S3;
  tmp.S0 = ((__global double16 *)source)[3].S2;
  vstore3(tmp, 25, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[3].S4;
  tmp.s0 = ((__global double16 *)source)[3].s5;
  vstore3(tmp, 26, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S0 = ((__global double16 *)source)[3].S6;
  tmp.S2 = ((__global double16 *)source)[3].S7;
  vstore3(tmp, 27, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s2 = ((__global double16 *)source)[3].s8;
  tmp.S1 = ((__global double16 *)source)[3].S8;
  vstore3(tmp, 28, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[3].Sb;
  tmp.S0 = ((__global double16 *)source)[3].Sa;
  vstore3(tmp, 29, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[3].sd;
  tmp.S1 = ((__global double16 *)source)[3].sC;
  vstore3(tmp, 30, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[3].SE;
  tmp.s2 = ((__global double16 *)source)[3].SE;
  vstore3(tmp, 31, (__global double *)dest);
}
