// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
double3 shuffle_fn(double3 source);
double3 shuffle_fn(double3 source) { return source; }

__kernel void sample_test(__global double *source, __global double4 *dest) {
  if (get_global_id(0) != 0)
    return;
  // double3 src1 /*, src2*/;
  double4 tmp;
  tmp = (double4)((double)0);
  tmp.S2 = shuffle_fn(vload3(0, source)).S0;
  dest[0] = tmp;
  tmp = (double4)((double)0);
  tmp.S3 = shuffle_fn(vload3(1, source)).S0;
  dest[1] = tmp;
  tmp = (double4)((double)0);
  tmp.S3 = shuffle_fn(vload3(2, source)).s0;
  dest[2] = tmp;
  tmp = (double4)((double)0);
  tmp.s0 = shuffle_fn(vload3(3, source)).s2;
  dest[3] = tmp;
  tmp = (double4)((double)0);
  tmp.s3 = shuffle_fn(vload3(4, source)).S1;
  dest[4] = tmp;
  tmp = (double4)((double)0);
  tmp.S0 = shuffle_fn(vload3(5, source)).s1;
  dest[5] = tmp;
  tmp = (double4)((double)0);
  tmp.S3 = shuffle_fn(vload3(6, source)).S0;
  dest[6] = tmp;
  tmp = (double4)((double)0);
  tmp.S0 = shuffle_fn(vload3(7, source)).S0;
  dest[7] = tmp;
  tmp = (double4)((double)0);
  tmp.S0 = shuffle_fn(vload3(8, source)).S0;
  dest[8] = tmp;
  tmp = (double4)((double)0);
  tmp.s3 = shuffle_fn(vload3(9, source)).S2;
  dest[9] = tmp;
  tmp = (double4)((double)0);
  tmp.S0 = shuffle_fn(vload3(10, source)).s2;
  dest[10] = tmp;
  tmp = (double4)((double)0);
  tmp.s02 = shuffle_fn(vload3(11, source)).S10;
  dest[11] = tmp;
  tmp = (double4)((double)0);
  tmp.s20 = shuffle_fn(vload3(12, source)).s00;
  dest[12] = tmp;
  tmp = (double4)((double)0);
  tmp.S13 = shuffle_fn(vload3(13, source)).S21;
  dest[13] = tmp;
  tmp = (double4)((double)0);
  tmp.s30 = shuffle_fn(vload3(14, source)).S22;
  dest[14] = tmp;
  tmp = (double4)((double)0);
  tmp.S20 = shuffle_fn(vload3(15, source)).s02;
  dest[15] = tmp;
  tmp = (double4)((double)0);
  tmp.S30 = shuffle_fn(vload3(16, source)).s21;
  dest[16] = tmp;
  tmp = (double4)((double)0);
  tmp.S31 = shuffle_fn(vload3(17, source)).S21;
  dest[17] = tmp;
  tmp = (double4)((double)0);
  tmp.S03 = shuffle_fn(vload3(18, source)).s11;
  dest[18] = tmp;
  tmp = (double4)((double)0);
  tmp.s10 = shuffle_fn(vload3(19, source)).S21;
  dest[19] = tmp;
  tmp = (double4)((double)0);
  tmp.s21 = shuffle_fn(vload3(20, source)).S10;
  dest[20] = tmp;
  tmp = (double4)((double)0);
  tmp.S02 = shuffle_fn(vload3(21, source)).S01;
  dest[21] = tmp;
  tmp = (double4)((double)0);
  tmp.S32 = shuffle_fn(vload3(22, source)).S21;
  dest[22] = tmp;
  tmp = (double4)((double)0);
  tmp.S20 = shuffle_fn(vload3(23, source)).s20;
  dest[23] = tmp;
  tmp = (double4)((double)0);
  tmp.S32 = shuffle_fn(vload3(24, source)).s20;
  dest[24] = tmp;
  tmp = (double4)((double)0);
  tmp.s21 = shuffle_fn(vload3(25, source)).s00;
  dest[25] = tmp;
  tmp = (double4)((double)0);
  tmp.S31 = shuffle_fn(vload3(26, source)).S21;
  dest[26] = tmp;
  tmp = (double4)((double)0);
  tmp.s23 = shuffle_fn(vload3(27, source)).s12;
  dest[27] = tmp;
  tmp = (double4)((double)0);
  tmp.S21 = shuffle_fn(vload3(28, source)).s22;
  dest[28] = tmp;
  tmp = (double4)((double)0);
  tmp.S12 = shuffle_fn(vload3(29, source)).S01;
  dest[29] = tmp;
  tmp = (double4)((double)0);
  tmp.S12 = shuffle_fn(vload3(30, source)).S02;
  dest[30] = tmp;
  tmp = (double4)((double)0);
  tmp.s03 = shuffle_fn(vload3(31, source)).s22;
  dest[31] = tmp;
}
