// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global long2 *source, __global long *dest) {
  if (get_global_id(0) != 0)
    return;
  // long2 src1 /*, src2*/;
  long3 tmp;
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[0].s1;
  vstore3(tmp, 0, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[0].S3;
  vstore3(tmp, 1, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[0].s5;
  vstore3(tmp, 2, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[0].S7;
  vstore3(tmp, 3, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[0].s8;
  vstore3(tmp, 4, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[0].SB;
  vstore3(tmp, 5, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[0].Sc;
  vstore3(tmp, 6, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[0].sF;
  vstore3(tmp, 7, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[1].S0;
  vstore3(tmp, 8, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[1].S3;
  vstore3(tmp, 9, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[1].S4;
  vstore3(tmp, 10, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[1].S6;
  vstore3(tmp, 11, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[1].S9;
  vstore3(tmp, 12, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[1].sb;
  vstore3(tmp, 13, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[1].Sd;
  vstore3(tmp, 14, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[1].sF;
  vstore3(tmp, 15, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[2].S0;
  tmp.S2 = ((__global long16 *)source)[2].S0;
  vstore3(tmp, 16, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[2].S2;
  tmp.s1 = ((__global long16 *)source)[2].S3;
  vstore3(tmp, 17, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[2].s4;
  tmp.S2 = ((__global long16 *)source)[2].s5;
  vstore3(tmp, 18, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[2].s7;
  tmp.S2 = ((__global long16 *)source)[2].s6;
  vstore3(tmp, 19, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[2].s9;
  tmp.s1 = ((__global long16 *)source)[2].s8;
  vstore3(tmp, 20, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[2].SA;
  tmp.s0 = ((__global long16 *)source)[2].sb;
  vstore3(tmp, 21, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[2].Sc;
  tmp.S2 = ((__global long16 *)source)[2].SC;
  vstore3(tmp, 22, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[2].Sf;
  tmp.s0 = ((__global long16 *)source)[2].sf;
  vstore3(tmp, 23, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[3].s1;
  tmp.S1 = ((__global long16 *)source)[3].s0;
  vstore3(tmp, 24, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[3].S3;
  tmp.S0 = ((__global long16 *)source)[3].S3;
  vstore3(tmp, 25, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[3].s5;
  tmp.S2 = ((__global long16 *)source)[3].s5;
  vstore3(tmp, 26, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[3].S6;
  tmp.s0 = ((__global long16 *)source)[3].S7;
  vstore3(tmp, 27, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[3].s9;
  tmp.s2 = ((__global long16 *)source)[3].s8;
  vstore3(tmp, 28, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[3].sB;
  tmp.S2 = ((__global long16 *)source)[3].sa;
  vstore3(tmp, 29, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[3].sD;
  tmp.S2 = ((__global long16 *)source)[3].sD;
  vstore3(tmp, 30, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[3].sE;
  tmp.s1 = ((__global long16 *)source)[3].Se;
  vstore3(tmp, 31, (__global long *)dest);
}
