// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
double16 shuffle_fn(double16 source);
double16 shuffle_fn(double16 source) { return source; }

__kernel void sample_test(__global double16 *source, __global double *dest) {
  if (get_global_id(0) != 0)
    return;
  // double16 src1 /*, src2*/;
  double tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[0]).sa;
  dest[0] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[1]).S8;
  dest[1] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[2]).s3;
  dest[2] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[3]).sb;
  dest[3] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[4]).S0;
  dest[4] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[5]).S4;
  dest[5] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[6]).sc;
  dest[6] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[7]).s1;
  dest[7] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[8]).Sc;
  dest[8] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[9]).S9;
  dest[9] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[10]).sC;
  dest[10] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[11]).SA;
  dest[11] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[12]).Sb;
  dest[12] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[13]).S0;
  dest[13] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[14]).SF;
  dest[14] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[15]).se;
  dest[15] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[16]).s3;
  dest[16] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[17]).s5;
  dest[17] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[18]).S2;
  dest[18] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[19]).s0;
  dest[19] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[20]).S8;
  dest[20] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[21]).sF;
  dest[21] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[22]).S0;
  dest[22] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[23]).Sb;
  dest[23] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[24]).s5;
  dest[24] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[25]).s0;
  dest[25] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[26]).SC;
  dest[26] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[27]).s0;
  dest[27] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[28]).s5;
  dest[28] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[29]).S5;
  dest[29] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[30]).sA;
  dest[30] = tmp;
  tmp = (double)((double)0);
  tmp = shuffle_fn(source[31]).S5;
  dest[31] = tmp;
}
