// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global int16 *source, __global int *dest) {
  if (get_global_id(0) != 0)
    return;
  // int16 src1 /*, src2*/;
  int3 tmp;
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[0].s1;
  vstore3(tmp, 0, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[1].s2;
  vstore3(tmp, 1, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[2].S6;
  vstore3(tmp, 2, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[3].s8;
  vstore3(tmp, 3, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[4].s1;
  vstore3(tmp, 4, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[5].sc;
  vstore3(tmp, 5, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[6].S6;
  vstore3(tmp, 6, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[7].SA;
  vstore3(tmp, 7, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[8].S1;
  vstore3(tmp, 8, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[9].se;
  vstore3(tmp, 9, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[10].s0;
  vstore3(tmp, 10, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[11].sD;
  tmp.s2 = ((__global int16 *)source)[11].s0;
  vstore3(tmp, 11, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[12].sC;
  tmp.S0 = ((__global int16 *)source)[12].s3;
  vstore3(tmp, 12, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[13].s6;
  tmp.s1 = ((__global int16 *)source)[13].s2;
  vstore3(tmp, 13, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[14].sb;
  tmp.S0 = ((__global int16 *)source)[14].s7;
  vstore3(tmp, 14, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[15].Sc;
  tmp.S1 = ((__global int16 *)source)[15].Sb;
  vstore3(tmp, 15, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[16].S3;
  tmp.S0 = ((__global int16 *)source)[16].s9;
  vstore3(tmp, 16, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[17].S7;
  tmp.S2 = ((__global int16 *)source)[17].s2;
  vstore3(tmp, 17, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[18].S3;
  tmp.S2 = ((__global int16 *)source)[18].sA;
  vstore3(tmp, 18, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[19].s0;
  tmp.S0 = ((__global int16 *)source)[19].S0;
  vstore3(tmp, 19, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[20].SA;
  tmp.s0 = ((__global int16 *)source)[20].SA;
  vstore3(tmp, 20, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[21].Sc;
  tmp.s1 = ((__global int16 *)source)[21].Sb;
  vstore3(tmp, 21, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[22].sB;
  tmp.S1 = ((__global int16 *)source)[22].S3;
  vstore3(tmp, 22, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[23].Sa;
  tmp.S0 = ((__global int16 *)source)[23].s3;
  vstore3(tmp, 23, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[24].sf;
  tmp.S1 = ((__global int16 *)source)[24].Sa;
  vstore3(tmp, 24, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[25].SF;
  tmp.s1 = ((__global int16 *)source)[25].S5;
  vstore3(tmp, 25, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[26].S9;
  tmp.s2 = ((__global int16 *)source)[26].s4;
  vstore3(tmp, 26, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[27].SD;
  tmp.S0 = ((__global int16 *)source)[27].Sc;
  vstore3(tmp, 27, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[28].s4;
  tmp.s2 = ((__global int16 *)source)[28].se;
  vstore3(tmp, 28, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[29].s9;
  tmp.s2 = ((__global int16 *)source)[29].sC;
  vstore3(tmp, 29, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[30].s0;
  tmp.S0 = ((__global int16 *)source)[30].S3;
  vstore3(tmp, 30, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[31].sd;
  tmp.S2 = ((__global int16 *)source)[31].S7;
  vstore3(tmp, 31, (__global int *)dest);
}
