// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global short8 *source, __global short *dest) {
  if (get_global_id(0) != 0)
    return;
  // short8 src1 /*, src2*/;
  short3 tmp;
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[0].s7;
  vstore3(tmp, 0, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[0].sf;
  vstore3(tmp, 1, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[1].s0;
  vstore3(tmp, 2, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[1].S9;
  vstore3(tmp, 3, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[2].s3;
  vstore3(tmp, 4, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[2].SA;
  vstore3(tmp, 5, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[3].S3;
  vstore3(tmp, 6, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s2 = ((__global short16 *)source)[3].SA;
  vstore3(tmp, 7, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[4].s7;
  vstore3(tmp, 8, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[4].sF;
  vstore3(tmp, 9, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[5].S0;
  vstore3(tmp, 10, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[5].s8;
  tmp.s1 = ((__global short16 *)source)[5].sf;
  vstore3(tmp, 11, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[6].S7;
  tmp.S2 = ((__global short16 *)source)[6].S0;
  vstore3(tmp, 12, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[6].sD;
  tmp.s0 = ((__global short16 *)source)[6].Sd;
  vstore3(tmp, 13, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[7].s3;
  tmp.s0 = ((__global short16 *)source)[7].S7;
  vstore3(tmp, 14, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[7].s8;
  tmp.S2 = ((__global short16 *)source)[7].S9;
  vstore3(tmp, 15, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[8].s4;
  tmp.S1 = ((__global short16 *)source)[8].s3;
  vstore3(tmp, 16, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[8].Se;
  tmp.S1 = ((__global short16 *)source)[8].SE;
  vstore3(tmp, 17, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[9].s0;
  tmp.S2 = ((__global short16 *)source)[9].s7;
  vstore3(tmp, 18, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[9].s8;
  tmp.s2 = ((__global short16 *)source)[9].SD;
  vstore3(tmp, 19, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[10].s0;
  tmp.S2 = ((__global short16 *)source)[10].S5;
  vstore3(tmp, 20, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[10].s9;
  tmp.s2 = ((__global short16 *)source)[10].sf;
  vstore3(tmp, 21, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[11].s2;
  tmp.s1 = ((__global short16 *)source)[11].s7;
  vstore3(tmp, 22, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[11].Sa;
  tmp.s2 = ((__global short16 *)source)[11].sE;
  vstore3(tmp, 23, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[12].s1;
  tmp.S1 = ((__global short16 *)source)[12].s3;
  vstore3(tmp, 24, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[12].sA;
  tmp.S1 = ((__global short16 *)source)[12].S9;
  vstore3(tmp, 25, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[13].S1;
  tmp.s0 = ((__global short16 *)source)[13].s6;
  vstore3(tmp, 26, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[13].sf;
  tmp.S2 = ((__global short16 *)source)[13].Sc;
  vstore3(tmp, 27, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[14].s5;
  tmp.S2 = ((__global short16 *)source)[14].s2;
  vstore3(tmp, 28, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[14].se;
  tmp.S2 = ((__global short16 *)source)[14].s8;
  vstore3(tmp, 29, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[15].S3;
  tmp.s1 = ((__global short16 *)source)[15].S0;
  vstore3(tmp, 30, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[15].S8;
  tmp.s1 = ((__global short16 *)source)[15].Sf;
  vstore3(tmp, 31, (__global short *)dest);
}
