// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global uint16 *source, __global uint *dest) {
  if (get_global_id(0) != 0)
    return;
  // uint16 src1 /*, src2*/;
  uint3 tmp;
  tmp = (uint)((uint)0);
  tmp.s0 = ((__global uint16 *)source)[0].S0;
  vstore3(tmp, 0, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S1 = ((__global uint16 *)source)[1].s9;
  vstore3(tmp, 1, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s1 = ((__global uint16 *)source)[2].S8;
  vstore3(tmp, 2, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s1 = ((__global uint16 *)source)[3].sB;
  vstore3(tmp, 3, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[4].S2;
  vstore3(tmp, 4, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[5].S6;
  vstore3(tmp, 5, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s0 = ((__global uint16 *)source)[6].sc;
  vstore3(tmp, 6, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s0 = ((__global uint16 *)source)[7].SE;
  vstore3(tmp, 7, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s1 = ((__global uint16 *)source)[8].sa;
  vstore3(tmp, 8, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s1 = ((__global uint16 *)source)[9].s5;
  vstore3(tmp, 9, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S2 = ((__global uint16 *)source)[10].s7;
  vstore3(tmp, 10, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S2 = ((__global uint16 *)source)[11].s0;
  tmp.s0 = ((__global uint16 *)source)[11].Sd;
  vstore3(tmp, 11, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s0 = ((__global uint16 *)source)[12].SD;
  tmp.s2 = ((__global uint16 *)source)[12].S2;
  vstore3(tmp, 12, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S2 = ((__global uint16 *)source)[13].s0;
  tmp.s1 = ((__global uint16 *)source)[13].Sb;
  vstore3(tmp, 13, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s1 = ((__global uint16 *)source)[14].s1;
  tmp.S2 = ((__global uint16 *)source)[14].s7;
  vstore3(tmp, 14, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s0 = ((__global uint16 *)source)[15].s3;
  tmp.S2 = ((__global uint16 *)source)[15].S8;
  vstore3(tmp, 15, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S2 = ((__global uint16 *)source)[16].S6;
  tmp.S1 = ((__global uint16 *)source)[16].s3;
  vstore3(tmp, 16, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[17].sb;
  tmp.S1 = ((__global uint16 *)source)[17].S8;
  vstore3(tmp, 17, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[18].S8;
  tmp.s2 = ((__global uint16 *)source)[18].sA;
  vstore3(tmp, 18, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[19].S5;
  tmp.s1 = ((__global uint16 *)source)[19].s3;
  vstore3(tmp, 19, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S1 = ((__global uint16 *)source)[20].s3;
  tmp.S2 = ((__global uint16 *)source)[20].s1;
  vstore3(tmp, 20, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[21].se;
  tmp.s0 = ((__global uint16 *)source)[21].S1;
  vstore3(tmp, 21, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[22].S0;
  tmp.S2 = ((__global uint16 *)source)[22].s4;
  vstore3(tmp, 22, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[23].Se;
  tmp.s0 = ((__global uint16 *)source)[23].s9;
  vstore3(tmp, 23, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[24].s7;
  tmp.S2 = ((__global uint16 *)source)[24].S8;
  vstore3(tmp, 24, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[25].SA;
  tmp.S0 = ((__global uint16 *)source)[25].s2;
  vstore3(tmp, 25, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[26].sA;
  tmp.S2 = ((__global uint16 *)source)[26].s4;
  vstore3(tmp, 26, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S1 = ((__global uint16 *)source)[27].s1;
  tmp.S2 = ((__global uint16 *)source)[27].SA;
  vstore3(tmp, 27, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s0 = ((__global uint16 *)source)[28].Sc;
  tmp.s1 = ((__global uint16 *)source)[28].s1;
  vstore3(tmp, 28, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s0 = ((__global uint16 *)source)[29].sD;
  tmp.s1 = ((__global uint16 *)source)[29].S3;
  vstore3(tmp, 29, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s0 = ((__global uint16 *)source)[30].sF;
  tmp.s2 = ((__global uint16 *)source)[30].s2;
  vstore3(tmp, 30, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S2 = ((__global uint16 *)source)[31].sD;
  tmp.s0 = ((__global uint16 *)source)[31].S1;
  vstore3(tmp, 31, (__global uint *)dest);
}
