// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global long8 *source, __global long *dest) {
  if (get_global_id(0) != 0)
    return;
  // long8 src1 /*, src2*/;
  long3 tmp;
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[0].s1;
  vstore3(tmp, 0, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[0].SC;
  vstore3(tmp, 1, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[1].s4;
  vstore3(tmp, 2, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[1].S8;
  vstore3(tmp, 3, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[2].s4;
  vstore3(tmp, 4, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[2].sa;
  vstore3(tmp, 5, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[3].s7;
  vstore3(tmp, 6, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[3].s9;
  vstore3(tmp, 7, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[4].s6;
  vstore3(tmp, 8, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[4].S8;
  vstore3(tmp, 9, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[5].s0;
  vstore3(tmp, 10, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[5].sD;
  tmp.s2 = ((__global long16 *)source)[5].sc;
  vstore3(tmp, 11, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[6].s3;
  tmp.S0 = ((__global long16 *)source)[6].S5;
  vstore3(tmp, 12, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[6].sE;
  tmp.S2 = ((__global long16 *)source)[6].s9;
  vstore3(tmp, 13, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[7].s3;
  tmp.S1 = ((__global long16 *)source)[7].S2;
  vstore3(tmp, 14, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[7].SF;
  tmp.S0 = ((__global long16 *)source)[7].S9;
  vstore3(tmp, 15, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[8].s5;
  tmp.s2 = ((__global long16 *)source)[8].S1;
  vstore3(tmp, 16, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[8].sb;
  tmp.s0 = ((__global long16 *)source)[8].sf;
  vstore3(tmp, 17, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[9].s2;
  tmp.S2 = ((__global long16 *)source)[9].s4;
  vstore3(tmp, 18, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[9].Sc;
  tmp.s1 = ((__global long16 *)source)[9].sA;
  vstore3(tmp, 19, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[10].s2;
  tmp.s1 = ((__global long16 *)source)[10].s5;
  vstore3(tmp, 20, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[10].Sb;
  tmp.s2 = ((__global long16 *)source)[10].se;
  vstore3(tmp, 21, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[11].s6;
  tmp.S2 = ((__global long16 *)source)[11].S1;
  vstore3(tmp, 22, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[11].Se;
  tmp.s0 = ((__global long16 *)source)[11].sf;
  vstore3(tmp, 23, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[12].S0;
  tmp.s1 = ((__global long16 *)source)[12].s1;
  vstore3(tmp, 24, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[12].sE;
  tmp.s1 = ((__global long16 *)source)[12].sd;
  vstore3(tmp, 25, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[13].s6;
  tmp.s1 = ((__global long16 *)source)[13].S4;
  vstore3(tmp, 26, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[13].sa;
  tmp.s2 = ((__global long16 *)source)[13].Sb;
  vstore3(tmp, 27, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[14].S3;
  tmp.s1 = ((__global long16 *)source)[14].s2;
  vstore3(tmp, 28, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[14].sc;
  tmp.S0 = ((__global long16 *)source)[14].Sa;
  vstore3(tmp, 29, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[15].s6;
  tmp.S0 = ((__global long16 *)source)[15].S7;
  vstore3(tmp, 30, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[15].S8;
  tmp.S1 = ((__global long16 *)source)[15].sF;
  vstore3(tmp, 31, (__global long *)dest);
}
