// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global float16 *source, __global float *dest) {
  if (get_global_id(0) != 0)
    return;
  // float16 src1 /*, src2*/;
  float3 tmp;
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[0].s1;
  vstore3(tmp, 0, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[1].s9;
  vstore3(tmp, 1, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[2].s0;
  vstore3(tmp, 2, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[3].s4;
  vstore3(tmp, 3, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[4].sC;
  vstore3(tmp, 4, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[5].SB;
  vstore3(tmp, 5, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[6].s7;
  vstore3(tmp, 6, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[7].Sb;
  vstore3(tmp, 7, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[8].sa;
  vstore3(tmp, 8, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[9].s7;
  vstore3(tmp, 9, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[10].SD;
  vstore3(tmp, 10, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[11].S0;
  tmp.S2 = ((__global float16 *)source)[11].sC;
  vstore3(tmp, 11, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[12].sE;
  tmp.S2 = ((__global float16 *)source)[12].s7;
  vstore3(tmp, 12, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[13].s8;
  tmp.s0 = ((__global float16 *)source)[13].SB;
  vstore3(tmp, 13, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[14].s6;
  tmp.s0 = ((__global float16 *)source)[14].S1;
  vstore3(tmp, 14, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[15].sF;
  tmp.S1 = ((__global float16 *)source)[15].Sd;
  vstore3(tmp, 15, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[16].s3;
  tmp.s2 = ((__global float16 *)source)[16].s9;
  vstore3(tmp, 16, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[17].Sf;
  tmp.s2 = ((__global float16 *)source)[17].S4;
  vstore3(tmp, 17, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[18].s3;
  tmp.s0 = ((__global float16 *)source)[18].s6;
  vstore3(tmp, 18, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[19].s7;
  tmp.S0 = ((__global float16 *)source)[19].SC;
  vstore3(tmp, 19, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[20].SD;
  tmp.s0 = ((__global float16 *)source)[20].S4;
  vstore3(tmp, 20, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[21].SC;
  tmp.S1 = ((__global float16 *)source)[21].Sa;
  vstore3(tmp, 21, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[22].s3;
  tmp.S0 = ((__global float16 *)source)[22].sB;
  vstore3(tmp, 22, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[23].S5;
  tmp.S0 = ((__global float16 *)source)[23].s7;
  vstore3(tmp, 23, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[24].S9;
  tmp.S2 = ((__global float16 *)source)[24].s0;
  vstore3(tmp, 24, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[25].S3;
  tmp.S2 = ((__global float16 *)source)[25].S0;
  vstore3(tmp, 25, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[26].sc;
  tmp.s1 = ((__global float16 *)source)[26].SF;
  vstore3(tmp, 26, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[27].S9;
  tmp.S2 = ((__global float16 *)source)[27].s7;
  vstore3(tmp, 27, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[28].SC;
  tmp.S0 = ((__global float16 *)source)[28].s5;
  vstore3(tmp, 28, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[29].s5;
  tmp.s0 = ((__global float16 *)source)[29].S0;
  vstore3(tmp, 29, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[30].s8;
  tmp.S1 = ((__global float16 *)source)[30].S6;
  vstore3(tmp, 30, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[31].SB;
  tmp.s2 = ((__global float16 *)source)[31].sF;
  vstore3(tmp, 31, (__global float *)dest);
}
