// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global short *source, __global short *dest) {
  if (get_global_id(0) != 0)
    return;
  // short3 src1 /*, src2*/;
  short3 tmp;
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[0].S2;
  vstore3(tmp, 0, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[0].s5;
  vstore3(tmp, 1, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[0].s7;
  vstore3(tmp, 2, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[0].Sb;
  vstore3(tmp, 3, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s2 = ((__global short16 *)source)[0].sc;
  vstore3(tmp, 4, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[1].s1;
  vstore3(tmp, 5, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[1].s4;
  vstore3(tmp, 6, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s2 = ((__global short16 *)source)[1].S5;
  vstore3(tmp, 7, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[1].s8;
  vstore3(tmp, 8, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s2 = ((__global short16 *)source)[1].Sd;
  vstore3(tmp, 9, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[2].S0;
  vstore3(tmp, 10, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s2 = ((__global short16 *)source)[2].S1;
  tmp.S1 = ((__global short16 *)source)[2].s1;
  vstore3(tmp, 11, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[2].S4;
  tmp.s1 = ((__global short16 *)source)[2].s6;
  vstore3(tmp, 12, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[2].s9;
  tmp.S0 = ((__global short16 *)source)[2].S7;
  vstore3(tmp, 13, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[2].sA;
  tmp.S2 = ((__global short16 *)source)[2].SA;
  vstore3(tmp, 14, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s2 = ((__global short16 *)source)[2].sf;
  tmp.S1 = ((__global short16 *)source)[2].Sf;
  vstore3(tmp, 15, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s2 = ((__global short16 *)source)[3].S2;
  tmp.s1 = ((__global short16 *)source)[3].s1;
  vstore3(tmp, 16, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s2 = ((__global short16 *)source)[3].s5;
  tmp.S0 = ((__global short16 *)source)[3].s3;
  vstore3(tmp, 17, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[3].s6;
  tmp.s0 = ((__global short16 *)source)[3].S8;
  vstore3(tmp, 18, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[3].SA;
  tmp.s0 = ((__global short16 *)source)[3].sa;
  vstore3(tmp, 19, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[3].sE;
  tmp.S1 = ((__global short16 *)source)[3].se;
  vstore3(tmp, 20, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[3].Sf;
  tmp.s0 = ((__global short16 *)source)[4].S0;
  vstore3(tmp, 21, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[4].s2;
  tmp.S0 = ((__global short16 *)source)[4].s3;
  vstore3(tmp, 22, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[4].S5;
  tmp.s2 = ((__global short16 *)source)[4].s5;
  vstore3(tmp, 23, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[4].s8;
  tmp.S1 = ((__global short16 *)source)[4].sA;
  vstore3(tmp, 24, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[4].SB;
  tmp.S2 = ((__global short16 *)source)[4].SD;
  vstore3(tmp, 25, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[4].sF;
  tmp.S0 = ((__global short16 *)source)[4].SF;
  vstore3(tmp, 26, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[5].S1;
  tmp.S1 = ((__global short16 *)source)[5].S3;
  vstore3(tmp, 27, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[5].S4;
  tmp.S1 = ((__global short16 *)source)[5].s5;
  vstore3(tmp, 28, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[5].s8;
  tmp.S0 = ((__global short16 *)source)[5].s8;
  vstore3(tmp, 29, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[5].SA;
  tmp.s1 = ((__global short16 *)source)[5].Sa;
  vstore3(tmp, 30, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[5].SE;
  tmp.S0 = ((__global short16 *)source)[5].SE;
  vstore3(tmp, 31, (__global short *)dest);
}
