// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global float4 *source, __global float *dest) {
  if (get_global_id(0) != 0)
    return;
  // float4 src1 /*, src2*/;
  float3 tmp;
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[0].s0;
  vstore3(tmp, 0, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[0].S6;
  vstore3(tmp, 1, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[0].s9;
  vstore3(tmp, 2, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[0].SC;
  vstore3(tmp, 3, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[1].s0;
  vstore3(tmp, 4, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[1].S6;
  vstore3(tmp, 5, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[1].sB;
  vstore3(tmp, 6, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[1].sF;
  vstore3(tmp, 7, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[2].S2;
  vstore3(tmp, 8, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[2].s7;
  vstore3(tmp, 9, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s0 = ((__global float16 *)source)[2].sB;
  vstore3(tmp, 10, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[2].sD;
  tmp.s1 = ((__global float16 *)source)[2].SC;
  vstore3(tmp, 11, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[3].S0;
  tmp.S1 = ((__global float16 *)source)[3].S2;
  vstore3(tmp, 12, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[3].s7;
  tmp.S2 = ((__global float16 *)source)[3].s7;
  vstore3(tmp, 13, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[3].S9;
  tmp.S1 = ((__global float16 *)source)[3].Sa;
  vstore3(tmp, 14, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[3].SC;
  tmp.s0 = ((__global float16 *)source)[3].sf;
  vstore3(tmp, 15, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[4].S3;
  tmp.S1 = ((__global float16 *)source)[4].S0;
  vstore3(tmp, 16, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[4].S5;
  tmp.S0 = ((__global float16 *)source)[4].S5;
  vstore3(tmp, 17, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[4].s8;
  tmp.S1 = ((__global float16 *)source)[4].SB;
  vstore3(tmp, 18, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[4].Sd;
  tmp.s0 = ((__global float16 *)source)[4].sC;
  vstore3(tmp, 19, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[5].S3;
  tmp.s2 = ((__global float16 *)source)[5].s1;
  vstore3(tmp, 20, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[5].s4;
  tmp.S2 = ((__global float16 *)source)[5].S7;
  vstore3(tmp, 21, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[5].s8;
  tmp.s0 = ((__global float16 *)source)[5].sB;
  vstore3(tmp, 22, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[5].sc;
  tmp.s1 = ((__global float16 *)source)[5].SE;
  vstore3(tmp, 23, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s2 = ((__global float16 *)source)[6].s3;
  tmp.S1 = ((__global float16 *)source)[6].s3;
  vstore3(tmp, 24, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[6].s7;
  tmp.s2 = ((__global float16 *)source)[6].S7;
  vstore3(tmp, 25, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[6].S9;
  tmp.S0 = ((__global float16 *)source)[6].sb;
  vstore3(tmp, 26, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S0 = ((__global float16 *)source)[6].SE;
  tmp.S2 = ((__global float16 *)source)[6].Sc;
  vstore3(tmp, 27, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[7].S1;
  tmp.S0 = ((__global float16 *)source)[7].S1;
  vstore3(tmp, 28, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S1 = ((__global float16 *)source)[7].S5;
  tmp.s0 = ((__global float16 *)source)[7].S4;
  vstore3(tmp, 29, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.S2 = ((__global float16 *)source)[7].S9;
  tmp.s1 = ((__global float16 *)source)[7].sb;
  vstore3(tmp, 30, (__global float *)dest);
  tmp = (float)((float)0);
  tmp.s1 = ((__global float16 *)source)[7].sf;
  tmp.S0 = ((__global float16 *)source)[7].sC;
  vstore3(tmp, 31, (__global float *)dest);
}
