// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global ushort16 *source, __global ushort *dest) {
  if (get_global_id(0) != 0)
    return;
  // ushort16 src1 /*, src2*/;
  ushort3 tmp;
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[0].s5;
  vstore3(tmp, 0, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S0 = ((__global ushort16 *)source)[1].S6;
  vstore3(tmp, 1, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[2].SA;
  vstore3(tmp, 2, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S2 = ((__global ushort16 *)source)[3].S9;
  vstore3(tmp, 3, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[4].S8;
  vstore3(tmp, 4, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S2 = ((__global ushort16 *)source)[5].s6;
  vstore3(tmp, 5, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[6].sc;
  vstore3(tmp, 6, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[7].s5;
  vstore3(tmp, 7, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[8].sc;
  vstore3(tmp, 8, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[9].s2;
  vstore3(tmp, 9, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[10].S3;
  vstore3(tmp, 10, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[11].Sc;
  tmp.s0 = ((__global ushort16 *)source)[11].S5;
  vstore3(tmp, 11, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S0 = ((__global ushort16 *)source)[12].S4;
  tmp.S1 = ((__global ushort16 *)source)[12].sC;
  vstore3(tmp, 12, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[13].Sd;
  tmp.S2 = ((__global ushort16 *)source)[13].S2;
  vstore3(tmp, 13, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S0 = ((__global ushort16 *)source)[14].sD;
  tmp.s2 = ((__global ushort16 *)source)[14].sa;
  vstore3(tmp, 14, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s0 = ((__global ushort16 *)source)[15].s5;
  tmp.S1 = ((__global ushort16 *)source)[15].s6;
  vstore3(tmp, 15, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s0 = ((__global ushort16 *)source)[16].SC;
  tmp.s2 = ((__global ushort16 *)source)[16].S8;
  vstore3(tmp, 16, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[17].Sc;
  tmp.s0 = ((__global ushort16 *)source)[17].S4;
  vstore3(tmp, 17, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[18].s2;
  tmp.s1 = ((__global ushort16 *)source)[18].s1;
  vstore3(tmp, 18, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[19].Sb;
  tmp.S0 = ((__global ushort16 *)source)[19].sF;
  vstore3(tmp, 19, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[20].sB;
  tmp.s2 = ((__global ushort16 *)source)[20].S5;
  vstore3(tmp, 20, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[21].S8;
  tmp.s0 = ((__global ushort16 *)source)[21].SD;
  vstore3(tmp, 21, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S2 = ((__global ushort16 *)source)[22].s3;
  tmp.s0 = ((__global ushort16 *)source)[22].S3;
  vstore3(tmp, 22, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[23].s8;
  tmp.s0 = ((__global ushort16 *)source)[23].SF;
  vstore3(tmp, 23, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S0 = ((__global ushort16 *)source)[24].s1;
  tmp.S1 = ((__global ushort16 *)source)[24].SE;
  vstore3(tmp, 24, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S0 = ((__global ushort16 *)source)[25].s5;
  tmp.s1 = ((__global ushort16 *)source)[25].s4;
  vstore3(tmp, 25, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[26].S7;
  tmp.s0 = ((__global ushort16 *)source)[26].sb;
  vstore3(tmp, 26, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[27].SE;
  tmp.s2 = ((__global ushort16 *)source)[27].SB;
  vstore3(tmp, 27, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S2 = ((__global ushort16 *)source)[28].S6;
  tmp.S1 = ((__global ushort16 *)source)[28].SE;
  vstore3(tmp, 28, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[29].Sf;
  tmp.s0 = ((__global ushort16 *)source)[29].SB;
  vstore3(tmp, 29, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S2 = ((__global ushort16 *)source)[30].S6;
  tmp.S0 = ((__global ushort16 *)source)[30].Sb;
  vstore3(tmp, 30, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S0 = ((__global ushort16 *)source)[31].s4;
  tmp.S2 = ((__global ushort16 *)source)[31].s0;
  vstore3(tmp, 31, (__global ushort *)dest);
}
