// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
double4 shuffle_fn(double4 source);
double4 shuffle_fn(double4 source) { return source; }

__kernel void sample_test(__global double4 *source, __global double2 *dest) {
  if (get_global_id(0) != 0)
    return;
  // double4 src1 /*, src2*/;
  double2 tmp;
  tmp = (double2)((double)0);
  tmp.s1 = shuffle_fn(source[0]).s0;
  dest[0] = tmp;
  tmp = (double2)((double)0);
  tmp.S1 = shuffle_fn(source[1]).S1;
  dest[1] = tmp;
  tmp = (double2)((double)0);
  tmp.s0 = shuffle_fn(source[2]).S2;
  dest[2] = tmp;
  tmp = (double2)((double)0);
  tmp.S1 = shuffle_fn(source[3]).s1;
  dest[3] = tmp;
  tmp = (double2)((double)0);
  tmp.s1 = shuffle_fn(source[4]).s0;
  dest[4] = tmp;
  tmp = (double2)((double)0);
  tmp.s1 = shuffle_fn(source[5]).S1;
  dest[5] = tmp;
  tmp = (double2)((double)0);
  tmp.S0 = shuffle_fn(source[6]).s0;
  dest[6] = tmp;
  tmp = (double2)((double)0);
  tmp.s0 = shuffle_fn(source[7]).S2;
  dest[7] = tmp;
  tmp = (double2)((double)0);
  tmp.s0 = shuffle_fn(source[8]).s2;
  dest[8] = tmp;
  tmp = (double2)((double)0);
  tmp.s0 = shuffle_fn(source[9]).S2;
  dest[9] = tmp;
  tmp = (double2)((double)0);
  tmp.s1 = shuffle_fn(source[10]).S3;
  dest[10] = tmp;
  tmp = (double2)((double)0);
  tmp.s1 = shuffle_fn(source[11]).s0;
  dest[11] = tmp;
  tmp = (double2)((double)0);
  tmp.S1 = shuffle_fn(source[12]).s3;
  dest[12] = tmp;
  tmp = (double2)((double)0);
  tmp.S1 = shuffle_fn(source[13]).S2;
  dest[13] = tmp;
  tmp = (double2)((double)0);
  tmp.S0 = shuffle_fn(source[14]).s1;
  dest[14] = tmp;
  tmp = (double2)((double)0);
  tmp.S1 = shuffle_fn(source[15]).s3;
  dest[15] = tmp;
  tmp = (double2)((double)0);
  tmp.s10 = shuffle_fn(source[16]).S30;
  dest[16] = tmp;
  tmp = (double2)((double)0);
  tmp.S01 = shuffle_fn(source[17]).S22;
  dest[17] = tmp;
  tmp = (double2)((double)0);
  tmp.s01 = shuffle_fn(source[18]).s32;
  dest[18] = tmp;
  tmp = (double2)((double)0);
  tmp.s01 = shuffle_fn(source[19]).S31;
  dest[19] = tmp;
  tmp = (double2)((double)0);
  tmp.S10 = shuffle_fn(source[20]).s22;
  dest[20] = tmp;
  tmp = (double2)((double)0);
  tmp.S10 = shuffle_fn(source[21]).s12;
  dest[21] = tmp;
  tmp = (double2)((double)0);
  tmp.s01 = shuffle_fn(source[22]).s11;
  dest[22] = tmp;
  tmp = (double2)((double)0);
  tmp.S01 = shuffle_fn(source[23]).s23;
  dest[23] = tmp;
  tmp = (double2)((double)0);
  tmp.s10 = shuffle_fn(source[24]).S31;
  dest[24] = tmp;
  tmp = (double2)((double)0);
  tmp.s10 = shuffle_fn(source[25]).s23;
  dest[25] = tmp;
  tmp = (double2)((double)0);
  tmp.S01 = shuffle_fn(source[26]).s21;
  dest[26] = tmp;
  tmp = (double2)((double)0);
  tmp.S10 = shuffle_fn(source[27]).s01;
  dest[27] = tmp;
  tmp = (double2)((double)0);
  tmp.S10 = shuffle_fn(source[28]).S10;
  dest[28] = tmp;
  tmp = (double2)((double)0);
  tmp.s10 = shuffle_fn(source[29]).S32;
  dest[29] = tmp;
  tmp = (double2)((double)0);
  tmp.s01 = shuffle_fn(source[30]).S20;
  dest[30] = tmp;
  tmp = (double2)((double)0);
  tmp.s01 = shuffle_fn(source[31]).S03;
  dest[31] = tmp;
}
