// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
double3 shuffle_fn(double3 source);
double3 shuffle_fn(double3 source) { return source; }

__kernel void sample_test(__global double *source, __global double8 *dest) {
  if (get_global_id(0) != 0)
    return;
  // double3 src1 /*, src2*/;
  double8 tmp;
  tmp = (double8)((double)0);
  tmp.s7 = shuffle_fn(vload3(0, source)).s2;
  dest[0] = tmp;
  tmp = (double8)((double)0);
  tmp.S0 = shuffle_fn(vload3(1, source)).S2;
  dest[1] = tmp;
  tmp = (double8)((double)0);
  tmp.s0 = shuffle_fn(vload3(2, source)).s1;
  dest[2] = tmp;
  tmp = (double8)((double)0);
  tmp.S7 = shuffle_fn(vload3(3, source)).s0;
  dest[3] = tmp;
  tmp = (double8)((double)0);
  tmp.s5 = shuffle_fn(vload3(4, source)).s2;
  dest[4] = tmp;
  tmp = (double8)((double)0);
  tmp.s0 = shuffle_fn(vload3(5, source)).s0;
  dest[5] = tmp;
  tmp = (double8)((double)0);
  tmp.s1 = shuffle_fn(vload3(6, source)).S2;
  dest[6] = tmp;
  tmp = (double8)((double)0);
  tmp.s6 = shuffle_fn(vload3(7, source)).s1;
  dest[7] = tmp;
  tmp = (double8)((double)0);
  tmp.s0 = shuffle_fn(vload3(8, source)).S0;
  dest[8] = tmp;
  tmp = (double8)((double)0);
  tmp.s6 = shuffle_fn(vload3(9, source)).s2;
  dest[9] = tmp;
  tmp = (double8)((double)0);
  tmp.s4 = shuffle_fn(vload3(10, source)).s1;
  dest[10] = tmp;
  tmp = (double8)((double)0);
  tmp.s61 = shuffle_fn(vload3(11, source)).S12;
  dest[11] = tmp;
  tmp = (double8)((double)0);
  tmp.S40 = shuffle_fn(vload3(12, source)).s00;
  dest[12] = tmp;
  tmp = (double8)((double)0);
  tmp.S31 = shuffle_fn(vload3(13, source)).S20;
  dest[13] = tmp;
  tmp = (double8)((double)0);
  tmp.S14 = shuffle_fn(vload3(14, source)).S02;
  dest[14] = tmp;
  tmp = (double8)((double)0);
  tmp.S60 = shuffle_fn(vload3(15, source)).S22;
  dest[15] = tmp;
  tmp = (double8)((double)0);
  tmp.s13 = shuffle_fn(vload3(16, source)).s20;
  dest[16] = tmp;
  tmp = (double8)((double)0);
  tmp.S43 = shuffle_fn(vload3(17, source)).s10;
  dest[17] = tmp;
  tmp = (double8)((double)0);
  tmp.S53 = shuffle_fn(vload3(18, source)).S12;
  dest[18] = tmp;
  tmp = (double8)((double)0);
  tmp.S60 = shuffle_fn(vload3(19, source)).s20;
  dest[19] = tmp;
  tmp = (double8)((double)0);
  tmp.s65 = shuffle_fn(vload3(20, source)).s01;
  dest[20] = tmp;
  tmp = (double8)((double)0);
  tmp.S32 = shuffle_fn(vload3(21, source)).s01;
  dest[21] = tmp;
  tmp = (double8)((double)0);
  tmp.s25 = shuffle_fn(vload3(22, source)).s21;
  dest[22] = tmp;
  tmp = (double8)((double)0);
  tmp.s07 = shuffle_fn(vload3(23, source)).S01;
  dest[23] = tmp;
  tmp = (double8)((double)0);
  tmp.s21 = shuffle_fn(vload3(24, source)).s11;
  dest[24] = tmp;
  tmp = (double8)((double)0);
  tmp.S63 = shuffle_fn(vload3(25, source)).S02;
  dest[25] = tmp;
  tmp = (double8)((double)0);
  tmp.s46 = shuffle_fn(vload3(26, source)).S21;
  dest[26] = tmp;
  tmp = (double8)((double)0);
  tmp.S16 = shuffle_fn(vload3(27, source)).s00;
  dest[27] = tmp;
  tmp = (double8)((double)0);
  tmp.s06 = shuffle_fn(vload3(28, source)).S21;
  dest[28] = tmp;
  tmp = (double8)((double)0);
  tmp.S46 = shuffle_fn(vload3(29, source)).S20;
  dest[29] = tmp;
  tmp = (double8)((double)0);
  tmp.s06 = shuffle_fn(vload3(30, source)).S00;
  dest[30] = tmp;
  tmp = (double8)((double)0);
  tmp.S47 = shuffle_fn(vload3(31, source)).S10;
  dest[31] = tmp;
}
