// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global char *source, __global char *dest) {
  if (get_global_id(0) != 0)
    return;
  // char3 src1 /*, src2*/;
  char3 tmp;
  tmp = (char)((char)0);
  tmp.s1 = ((__global char16 *)source)[0].S1;
  vstore3(tmp, 0, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S1 = ((__global char16 *)source)[0].s4;
  vstore3(tmp, 1, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S0 = ((__global char16 *)source)[0].s6;
  vstore3(tmp, 2, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[0].Sa;
  vstore3(tmp, 3, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S1 = ((__global char16 *)source)[0].sD;
  vstore3(tmp, 4, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[1].S1;
  vstore3(tmp, 5, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[1].s4;
  vstore3(tmp, 6, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S2 = ((__global char16 *)source)[1].S6;
  vstore3(tmp, 7, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s0 = ((__global char16 *)source)[1].S9;
  vstore3(tmp, 8, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s0 = ((__global char16 *)source)[1].sC;
  vstore3(tmp, 9, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S0 = ((__global char16 *)source)[1].Sf;
  vstore3(tmp, 10, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S1 = ((__global char16 *)source)[2].s1;
  tmp.s0 = ((__global char16 *)source)[2].S1;
  vstore3(tmp, 11, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s1 = ((__global char16 *)source)[2].s6;
  tmp.S0 = ((__global char16 *)source)[2].S4;
  vstore3(tmp, 12, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s0 = ((__global char16 *)source)[2].S7;
  tmp.S2 = ((__global char16 *)source)[2].S8;
  vstore3(tmp, 13, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S1 = ((__global char16 *)source)[2].Sb;
  tmp.S0 = ((__global char16 *)source)[2].sC;
  vstore3(tmp, 14, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S1 = ((__global char16 *)source)[2].sd;
  tmp.S0 = ((__global char16 *)source)[2].sF;
  vstore3(tmp, 15, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s1 = ((__global char16 *)source)[3].S2;
  tmp.s0 = ((__global char16 *)source)[3].S1;
  vstore3(tmp, 16, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S0 = ((__global char16 *)source)[3].S4;
  tmp.s2 = ((__global char16 *)source)[3].S4;
  vstore3(tmp, 17, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s0 = ((__global char16 *)source)[3].s6;
  tmp.S2 = ((__global char16 *)source)[3].s7;
  vstore3(tmp, 18, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[3].s9;
  tmp.s0 = ((__global char16 *)source)[3].sB;
  vstore3(tmp, 19, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S1 = ((__global char16 *)source)[3].sC;
  tmp.s0 = ((__global char16 *)source)[3].Sd;
  vstore3(tmp, 20, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[3].SF;
  tmp.s1 = ((__global char16 *)source)[4].S0;
  vstore3(tmp, 21, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[4].S2;
  tmp.s1 = ((__global char16 *)source)[4].s3;
  vstore3(tmp, 22, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s0 = ((__global char16 *)source)[4].S7;
  tmp.s1 = ((__global char16 *)source)[4].s6;
  vstore3(tmp, 23, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s1 = ((__global char16 *)source)[4].S9;
  tmp.S2 = ((__global char16 *)source)[4].S9;
  vstore3(tmp, 24, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S2 = ((__global char16 *)source)[4].sB;
  tmp.S1 = ((__global char16 *)source)[4].Sd;
  vstore3(tmp, 25, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S2 = ((__global char16 *)source)[4].se;
  tmp.s0 = ((__global char16 *)source)[5].S0;
  vstore3(tmp, 26, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S2 = ((__global char16 *)source)[5].s3;
  tmp.S0 = ((__global char16 *)source)[5].s3;
  vstore3(tmp, 27, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S2 = ((__global char16 *)source)[5].s4;
  tmp.s0 = ((__global char16 *)source)[5].s5;
  vstore3(tmp, 28, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[5].s9;
  tmp.S0 = ((__global char16 *)source)[5].s8;
  vstore3(tmp, 29, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S1 = ((__global char16 *)source)[5].Sa;
  tmp.S2 = ((__global char16 *)source)[5].SA;
  vstore3(tmp, 30, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[5].sD;
  tmp.s1 = ((__global char16 *)source)[5].sE;
  vstore3(tmp, 31, (__global char *)dest);
}
