// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global short *source, __global short *dest) {
  if (get_global_id(0) != 0)
    return;
  // short src1 /*, src2*/;
  short3 tmp;
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[0].S0;
  vstore3(tmp, 0, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[0].s1;
  vstore3(tmp, 1, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[0].S2;
  vstore3(tmp, 2, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[0].s3;
  vstore3(tmp, 3, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s2 = ((__global short16 *)source)[0].s4;
  vstore3(tmp, 4, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[0].s5;
  vstore3(tmp, 5, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s2 = ((__global short16 *)source)[0].S6;
  vstore3(tmp, 6, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[0].s7;
  vstore3(tmp, 7, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[0].S8;
  vstore3(tmp, 8, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[0].s9;
  vstore3(tmp, 9, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[0].SA;
  vstore3(tmp, 10, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[0].SB;
  vstore3(tmp, 11, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[0].sc;
  vstore3(tmp, 12, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s0 = ((__global short16 *)source)[0].sd;
  vstore3(tmp, 13, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[0].SE;
  vstore3(tmp, 14, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[0].sf;
  vstore3(tmp, 15, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[1].S0;
  vstore3(tmp, 16, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[1].s1;
  vstore3(tmp, 17, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[1].S2;
  vstore3(tmp, 18, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[1].S3;
  vstore3(tmp, 19, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[1].s4;
  vstore3(tmp, 20, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[1].s5;
  vstore3(tmp, 21, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[1].S6;
  vstore3(tmp, 22, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S1 = ((__global short16 *)source)[1].S7;
  vstore3(tmp, 23, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s2 = ((__global short16 *)source)[1].s8;
  vstore3(tmp, 24, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[1].s9;
  vstore3(tmp, 25, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[1].SA;
  vstore3(tmp, 26, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[1].Sb;
  vstore3(tmp, 27, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[1].SC;
  vstore3(tmp, 28, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S0 = ((__global short16 *)source)[1].sD;
  vstore3(tmp, 29, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.S2 = ((__global short16 *)source)[1].sE;
  vstore3(tmp, 30, (__global short *)dest);
  tmp = (short)((short)0);
  tmp.s1 = ((__global short16 *)source)[1].sf;
  vstore3(tmp, 31, (__global short *)dest);
}
