// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
double2 shuffle_fn(double2 source);
double2 shuffle_fn(double2 source) { return source; }

__kernel void sample_test(__global double2 *source, __global double4 *dest) {
  if (get_global_id(0) != 0)
    return;
  // double2 src1 /*, src2*/;
  double4 tmp;
  tmp = (double4)((double)0);
  tmp.S3 = shuffle_fn(source[0]).S1;
  dest[0] = tmp;
  tmp = (double4)((double)0);
  tmp.s0 = shuffle_fn(source[1]).s1;
  dest[1] = tmp;
  tmp = (double4)((double)0);
  tmp.s0 = shuffle_fn(source[2]).S0;
  dest[2] = tmp;
  tmp = (double4)((double)0);
  tmp.S3 = shuffle_fn(source[3]).s1;
  dest[3] = tmp;
  tmp = (double4)((double)0);
  tmp.S0 = shuffle_fn(source[4]).S0;
  dest[4] = tmp;
  tmp = (double4)((double)0);
  tmp.S3 = shuffle_fn(source[5]).s1;
  dest[5] = tmp;
  tmp = (double4)((double)0);
  tmp.S2 = shuffle_fn(source[6]).S0;
  dest[6] = tmp;
  tmp = (double4)((double)0);
  tmp.s2 = shuffle_fn(source[7]).S1;
  dest[7] = tmp;
  tmp = (double4)((double)0);
  tmp.s0 = shuffle_fn(source[8]).S0;
  dest[8] = tmp;
  tmp = (double4)((double)0);
  tmp.s2 = shuffle_fn(source[9]).s1;
  dest[9] = tmp;
  tmp = (double4)((double)0);
  tmp.S3 = shuffle_fn(source[10]).s0;
  dest[10] = tmp;
  tmp = (double4)((double)0);
  tmp.S0 = shuffle_fn(source[11]).s1;
  dest[11] = tmp;
  tmp = (double4)((double)0);
  tmp.S0 = shuffle_fn(source[12]).s0;
  dest[12] = tmp;
  tmp = (double4)((double)0);
  tmp.S3 = shuffle_fn(source[13]).S1;
  dest[13] = tmp;
  tmp = (double4)((double)0);
  tmp.S3 = shuffle_fn(source[14]).s1;
  dest[14] = tmp;
  tmp = (double4)((double)0);
  tmp.S0 = shuffle_fn(source[15]).s1;
  dest[15] = tmp;
  tmp = (double4)((double)0);
  tmp.S12 = shuffle_fn(source[16]).s10;
  dest[16] = tmp;
  tmp = (double4)((double)0);
  tmp.s12 = shuffle_fn(source[17]).s11;
  dest[17] = tmp;
  tmp = (double4)((double)0);
  tmp.s32 = shuffle_fn(source[18]).s01;
  dest[18] = tmp;
  tmp = (double4)((double)0);
  tmp.s10 = shuffle_fn(source[19]).S01;
  dest[19] = tmp;
  tmp = (double4)((double)0);
  tmp.s31 = shuffle_fn(source[20]).s01;
  dest[20] = tmp;
  tmp = (double4)((double)0);
  tmp.s32 = shuffle_fn(source[21]).S11;
  dest[21] = tmp;
  tmp = (double4)((double)0);
  tmp.s10 = shuffle_fn(source[22]).s00;
  dest[22] = tmp;
  tmp = (double4)((double)0);
  tmp.S21 = shuffle_fn(source[23]).s10;
  dest[23] = tmp;
  tmp = (double4)((double)0);
  tmp.S01 = shuffle_fn(source[24]).S10;
  dest[24] = tmp;
  tmp = (double4)((double)0);
  tmp.s12 = shuffle_fn(source[25]).s10;
  dest[25] = tmp;
  tmp = (double4)((double)0);
  tmp.S21 = shuffle_fn(source[26]).s01;
  dest[26] = tmp;
  tmp = (double4)((double)0);
  tmp.S32 = shuffle_fn(source[27]).s11;
  dest[27] = tmp;
  tmp = (double4)((double)0);
  tmp.S20 = shuffle_fn(source[28]).s10;
  dest[28] = tmp;
  tmp = (double4)((double)0);
  tmp.S01 = shuffle_fn(source[29]).S10;
  dest[29] = tmp;
  tmp = (double4)((double)0);
  tmp.S23 = shuffle_fn(source[30]).S00;
  dest[30] = tmp;
  tmp = (double4)((double)0);
  tmp.s20 = shuffle_fn(source[31]).S10;
  dest[31] = tmp;
}
