// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
double8 shuffle_fn(double8 source);
double8 shuffle_fn(double8 source) { return source; }

__kernel void sample_test(__global double8 *source, __global double *dest) {
  if (get_global_id(0) != 0)
    return;
  // double8 src1 /*, src2*/;
  double3 tmp;
  tmp = (double)((double)0);
  tmp.S2 = shuffle_fn(source[0]).s1;
  vstore3(tmp, 0, dest);
  tmp = (double)((double)0);
  tmp.S1 = shuffle_fn(source[1]).S7;
  vstore3(tmp, 1, dest);
  tmp = (double)((double)0);
  tmp.s1 = shuffle_fn(source[2]).S3;
  vstore3(tmp, 2, dest);
  tmp = (double)((double)0);
  tmp.S0 = shuffle_fn(source[3]).s4;
  vstore3(tmp, 3, dest);
  tmp = (double)((double)0);
  tmp.S1 = shuffle_fn(source[4]).s0;
  vstore3(tmp, 4, dest);
  tmp = (double)((double)0);
  tmp.S1 = shuffle_fn(source[5]).s2;
  vstore3(tmp, 5, dest);
  tmp = (double)((double)0);
  tmp.S1 = shuffle_fn(source[6]).s2;
  vstore3(tmp, 6, dest);
  tmp = (double)((double)0);
  tmp.S0 = shuffle_fn(source[7]).S6;
  vstore3(tmp, 7, dest);
  tmp = (double)((double)0);
  tmp.s0 = shuffle_fn(source[8]).S3;
  vstore3(tmp, 8, dest);
  tmp = (double)((double)0);
  tmp.S0 = shuffle_fn(source[9]).S6;
  vstore3(tmp, 9, dest);
  tmp = (double)((double)0);
  tmp.s0 = shuffle_fn(source[10]).S5;
  vstore3(tmp, 10, dest);
  tmp = (double)((double)0);
  tmp.S21 = shuffle_fn(source[11]).S42;
  vstore3(tmp, 11, dest);
  tmp = (double)((double)0);
  tmp.S20 = shuffle_fn(source[12]).S42;
  vstore3(tmp, 12, dest);
  tmp = (double)((double)0);
  tmp.S01 = shuffle_fn(source[13]).s56;
  vstore3(tmp, 13, dest);
  tmp = (double)((double)0);
  tmp.S01 = shuffle_fn(source[14]).s01;
  vstore3(tmp, 14, dest);
  tmp = (double)((double)0);
  tmp.s01 = shuffle_fn(source[15]).S36;
  vstore3(tmp, 15, dest);
  tmp = (double)((double)0);
  tmp.s01 = shuffle_fn(source[16]).S02;
  vstore3(tmp, 16, dest);
  tmp = (double)((double)0);
  tmp.S21 = shuffle_fn(source[17]).s27;
  vstore3(tmp, 17, dest);
  tmp = (double)((double)0);
  tmp.S21 = shuffle_fn(source[18]).s21;
  vstore3(tmp, 18, dest);
  tmp = (double)((double)0);
  tmp.S02 = shuffle_fn(source[19]).s54;
  vstore3(tmp, 19, dest);
  tmp = (double)((double)0);
  tmp.S10 = shuffle_fn(source[20]).s02;
  vstore3(tmp, 20, dest);
  tmp = (double)((double)0);
  tmp.S02 = shuffle_fn(source[21]).s13;
  vstore3(tmp, 21, dest);
  tmp = (double)((double)0);
  tmp.S01 = shuffle_fn(source[22]).S46;
  vstore3(tmp, 22, dest);
  tmp = (double)((double)0);
  tmp.S10 = shuffle_fn(source[23]).s50;
  vstore3(tmp, 23, dest);
  tmp = (double)((double)0);
  tmp.S10 = shuffle_fn(source[24]).S62;
  vstore3(tmp, 24, dest);
  tmp = (double)((double)0);
  tmp.S01 = shuffle_fn(source[25]).s74;
  vstore3(tmp, 25, dest);
  tmp = (double)((double)0);
  tmp.s20 = shuffle_fn(source[26]).s26;
  vstore3(tmp, 26, dest);
  tmp = (double)((double)0);
  tmp.S21 = shuffle_fn(source[27]).s64;
  vstore3(tmp, 27, dest);
  tmp = (double)((double)0);
  tmp.s10 = shuffle_fn(source[28]).s33;
  vstore3(tmp, 28, dest);
  tmp = (double)((double)0);
  tmp.S02 = shuffle_fn(source[29]).s52;
  vstore3(tmp, 29, dest);
  tmp = (double)((double)0);
  tmp.s20 = shuffle_fn(source[30]).s04;
  vstore3(tmp, 30, dest);
  tmp = (double)((double)0);
  tmp.S01 = shuffle_fn(source[31]).S35;
  vstore3(tmp, 31, dest);
}
