// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global uint16 *source, __global uint *dest) {
  if (get_global_id(0) != 0)
    return;
  // uint16 src1 /*, src2*/;
  uint3 tmp;
  tmp = (uint)((uint)0);
  tmp.s1 = ((__global uint16 *)source)[0].S1;
  vstore3(tmp, 0, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[1].s0;
  vstore3(tmp, 1, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[2].sc;
  vstore3(tmp, 2, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s0 = ((__global uint16 *)source)[3].SA;
  vstore3(tmp, 3, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s1 = ((__global uint16 *)source)[4].s1;
  vstore3(tmp, 4, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S2 = ((__global uint16 *)source)[5].S4;
  vstore3(tmp, 5, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S1 = ((__global uint16 *)source)[6].S2;
  vstore3(tmp, 6, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S2 = ((__global uint16 *)source)[7].s8;
  vstore3(tmp, 7, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[8].s8;
  vstore3(tmp, 8, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[9].S4;
  vstore3(tmp, 9, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[10].s4;
  vstore3(tmp, 10, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[11].s5;
  tmp.s2 = ((__global uint16 *)source)[11].S3;
  vstore3(tmp, 11, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[12].s6;
  tmp.S1 = ((__global uint16 *)source)[12].S7;
  vstore3(tmp, 12, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[13].sf;
  tmp.s1 = ((__global uint16 *)source)[13].S9;
  vstore3(tmp, 13, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[14].s1;
  tmp.s1 = ((__global uint16 *)source)[14].Sf;
  vstore3(tmp, 14, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s1 = ((__global uint16 *)source)[15].S9;
  tmp.s0 = ((__global uint16 *)source)[15].s0;
  vstore3(tmp, 15, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[16].S9;
  tmp.S1 = ((__global uint16 *)source)[16].Sb;
  vstore3(tmp, 16, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S2 = ((__global uint16 *)source)[17].S9;
  tmp.s0 = ((__global uint16 *)source)[17].Sd;
  vstore3(tmp, 17, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S1 = ((__global uint16 *)source)[18].S1;
  tmp.S0 = ((__global uint16 *)source)[18].s4;
  vstore3(tmp, 18, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[19].S4;
  tmp.S0 = ((__global uint16 *)source)[19].s7;
  vstore3(tmp, 19, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[20].SB;
  tmp.s1 = ((__global uint16 *)source)[20].S2;
  vstore3(tmp, 20, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[21].s0;
  tmp.S2 = ((__global uint16 *)source)[21].s9;
  vstore3(tmp, 21, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S2 = ((__global uint16 *)source)[22].Sd;
  tmp.S0 = ((__global uint16 *)source)[22].SC;
  vstore3(tmp, 22, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S2 = ((__global uint16 *)source)[23].s9;
  tmp.s1 = ((__global uint16 *)source)[23].s2;
  vstore3(tmp, 23, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S2 = ((__global uint16 *)source)[24].s0;
  tmp.s1 = ((__global uint16 *)source)[24].S2;
  vstore3(tmp, 24, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[25].s1;
  tmp.S0 = ((__global uint16 *)source)[25].SB;
  vstore3(tmp, 25, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S2 = ((__global uint16 *)source)[26].sb;
  tmp.S1 = ((__global uint16 *)source)[26].SA;
  vstore3(tmp, 26, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[27].sD;
  tmp.s1 = ((__global uint16 *)source)[27].s4;
  vstore3(tmp, 27, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s0 = ((__global uint16 *)source)[28].S3;
  tmp.S2 = ((__global uint16 *)source)[28].sF;
  vstore3(tmp, 28, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[29].SC;
  tmp.s0 = ((__global uint16 *)source)[29].S2;
  vstore3(tmp, 29, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S2 = ((__global uint16 *)source)[30].s9;
  tmp.S0 = ((__global uint16 *)source)[30].SD;
  vstore3(tmp, 30, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[31].S3;
  tmp.s1 = ((__global uint16 *)source)[31].S1;
  vstore3(tmp, 31, (__global uint *)dest);
}
