// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global ulong4 *source, __global ulong *dest) {
  if (get_global_id(0) != 0)
    return;
  // ulong4 src1 /*, src2*/;
  ulong3 tmp;
  tmp = (ulong)((ulong)0);
  tmp.s2 = ((__global ulong16 *)source)[0].S3;
  vstore3(tmp, 0, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S2 = ((__global ulong16 *)source)[0].s7;
  vstore3(tmp, 1, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s1 = ((__global ulong16 *)source)[0].sA;
  vstore3(tmp, 2, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s1 = ((__global ulong16 *)source)[0].SF;
  vstore3(tmp, 3, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S0 = ((__global ulong16 *)source)[1].s1;
  vstore3(tmp, 4, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s2 = ((__global ulong16 *)source)[1].S4;
  vstore3(tmp, 5, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s1 = ((__global ulong16 *)source)[1].s8;
  vstore3(tmp, 6, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S0 = ((__global ulong16 *)source)[1].Sd;
  vstore3(tmp, 7, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S2 = ((__global ulong16 *)source)[2].s0;
  vstore3(tmp, 8, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S0 = ((__global ulong16 *)source)[2].s6;
  vstore3(tmp, 9, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s1 = ((__global ulong16 *)source)[2].s8;
  vstore3(tmp, 10, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S2 = ((__global ulong16 *)source)[2].sc;
  tmp.S0 = ((__global ulong16 *)source)[2].sD;
  vstore3(tmp, 11, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S1 = ((__global ulong16 *)source)[3].S3;
  tmp.S2 = ((__global ulong16 *)source)[3].s0;
  vstore3(tmp, 12, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s1 = ((__global ulong16 *)source)[3].s7;
  tmp.S0 = ((__global ulong16 *)source)[3].S4;
  vstore3(tmp, 13, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s1 = ((__global ulong16 *)source)[3].sA;
  tmp.s0 = ((__global ulong16 *)source)[3].S9;
  vstore3(tmp, 14, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S0 = ((__global ulong16 *)source)[3].sF;
  tmp.S2 = ((__global ulong16 *)source)[3].SD;
  vstore3(tmp, 15, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S1 = ((__global ulong16 *)source)[4].S3;
  tmp.S0 = ((__global ulong16 *)source)[4].S1;
  vstore3(tmp, 16, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[4].s7;
  tmp.s1 = ((__global ulong16 *)source)[4].S5;
  vstore3(tmp, 17, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S2 = ((__global ulong16 *)source)[4].S9;
  tmp.s1 = ((__global ulong16 *)source)[4].s8;
  vstore3(tmp, 18, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[4].SF;
  tmp.S1 = ((__global ulong16 *)source)[4].sF;
  vstore3(tmp, 19, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[5].s0;
  tmp.s1 = ((__global ulong16 *)source)[5].s2;
  vstore3(tmp, 20, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S1 = ((__global ulong16 *)source)[5].S5;
  tmp.s0 = ((__global ulong16 *)source)[5].S5;
  vstore3(tmp, 21, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S1 = ((__global ulong16 *)source)[5].sA;
  tmp.S0 = ((__global ulong16 *)source)[5].s8;
  vstore3(tmp, 22, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S0 = ((__global ulong16 *)source)[5].sE;
  tmp.s2 = ((__global ulong16 *)source)[5].Sc;
  vstore3(tmp, 23, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S1 = ((__global ulong16 *)source)[6].s0;
  tmp.s0 = ((__global ulong16 *)source)[6].S3;
  vstore3(tmp, 24, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s2 = ((__global ulong16 *)source)[6].S5;
  tmp.S0 = ((__global ulong16 *)source)[6].S7;
  vstore3(tmp, 25, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S1 = ((__global ulong16 *)source)[6].S9;
  tmp.s0 = ((__global ulong16 *)source)[6].sb;
  vstore3(tmp, 26, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S0 = ((__global ulong16 *)source)[6].sC;
  tmp.s1 = ((__global ulong16 *)source)[6].sE;
  vstore3(tmp, 27, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S2 = ((__global ulong16 *)source)[7].S3;
  tmp.S0 = ((__global ulong16 *)source)[7].S2;
  vstore3(tmp, 28, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s1 = ((__global ulong16 *)source)[7].S5;
  tmp.S2 = ((__global ulong16 *)source)[7].s5;
  vstore3(tmp, 29, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s2 = ((__global ulong16 *)source)[7].s9;
  tmp.S1 = ((__global ulong16 *)source)[7].s9;
  vstore3(tmp, 30, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s2 = ((__global ulong16 *)source)[7].SE;
  tmp.S1 = ((__global ulong16 *)source)[7].Se;
  vstore3(tmp, 31, (__global ulong *)dest);
}
