// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global long8 *source, __global long *dest) {
  if (get_global_id(0) != 0)
    return;
  // long8 src1 /*, src2*/;
  long3 tmp;
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[0].s4;
  vstore3(tmp, 0, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[0].SF;
  vstore3(tmp, 1, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[1].s0;
  vstore3(tmp, 2, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[1].sF;
  vstore3(tmp, 3, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[2].S6;
  vstore3(tmp, 4, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[2].SE;
  vstore3(tmp, 5, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[3].S6;
  vstore3(tmp, 6, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[3].SA;
  vstore3(tmp, 7, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[4].S3;
  vstore3(tmp, 8, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[4].sa;
  vstore3(tmp, 9, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[5].S7;
  vstore3(tmp, 10, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s0 = ((__global long16 *)source)[5].sb;
  tmp.S1 = ((__global long16 *)source)[5].sF;
  vstore3(tmp, 11, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[6].s4;
  tmp.S1 = ((__global long16 *)source)[6].s2;
  vstore3(tmp, 12, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[6].sb;
  tmp.s0 = ((__global long16 *)source)[6].s8;
  vstore3(tmp, 13, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[7].s5;
  tmp.s2 = ((__global long16 *)source)[7].S4;
  vstore3(tmp, 14, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[7].sc;
  tmp.s1 = ((__global long16 *)source)[7].sD;
  vstore3(tmp, 15, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[8].s3;
  tmp.S2 = ((__global long16 *)source)[8].s4;
  vstore3(tmp, 16, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[8].Sf;
  tmp.S0 = ((__global long16 *)source)[8].sD;
  vstore3(tmp, 17, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[9].s7;
  tmp.S1 = ((__global long16 *)source)[9].S7;
  vstore3(tmp, 18, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[9].s9;
  tmp.S2 = ((__global long16 *)source)[9].sF;
  vstore3(tmp, 19, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[10].s0;
  tmp.s1 = ((__global long16 *)source)[10].S6;
  vstore3(tmp, 20, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[10].s9;
  tmp.S2 = ((__global long16 *)source)[10].SC;
  vstore3(tmp, 21, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[11].s0;
  tmp.S2 = ((__global long16 *)source)[11].s1;
  vstore3(tmp, 22, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[11].S9;
  tmp.s2 = ((__global long16 *)source)[11].sD;
  vstore3(tmp, 23, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S0 = ((__global long16 *)source)[12].S7;
  tmp.S2 = ((__global long16 *)source)[12].s4;
  vstore3(tmp, 24, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[12].SF;
  tmp.S1 = ((__global long16 *)source)[12].sD;
  vstore3(tmp, 25, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[13].S5;
  tmp.s2 = ((__global long16 *)source)[13].s2;
  vstore3(tmp, 26, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S1 = ((__global long16 *)source)[13].sB;
  tmp.S0 = ((__global long16 *)source)[13].SD;
  vstore3(tmp, 27, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.S2 = ((__global long16 *)source)[14].s2;
  tmp.s0 = ((__global long16 *)source)[14].S5;
  vstore3(tmp, 28, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[14].S8;
  tmp.s2 = ((__global long16 *)source)[14].S8;
  vstore3(tmp, 29, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s2 = ((__global long16 *)source)[15].S0;
  tmp.S1 = ((__global long16 *)source)[15].S1;
  vstore3(tmp, 30, (__global long *)dest);
  tmp = (long)((long)0);
  tmp.s1 = ((__global long16 *)source)[15].Sd;
  tmp.s0 = ((__global long16 *)source)[15].s8;
  vstore3(tmp, 31, (__global long *)dest);
}
