// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
__kernel void sample_test(__global double8 *source, __global double *dest) {
  if (get_global_id(0) != 0)
    return;
  // double8 src1 /*, src2*/;
  double3 tmp;
  tmp = (double)((double)0);
  tmp.s2 = ((__global double16 *)source)[0].S1;
  vstore3(tmp, 0, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[0].sf;
  vstore3(tmp, 1, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[1].s3;
  vstore3(tmp, 2, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S0 = ((__global double16 *)source)[1].SC;
  vstore3(tmp, 3, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[2].S0;
  vstore3(tmp, 4, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[2].Sa;
  vstore3(tmp, 5, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[3].S2;
  vstore3(tmp, 6, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S0 = ((__global double16 *)source)[3].Se;
  vstore3(tmp, 7, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S0 = ((__global double16 *)source)[4].s3;
  vstore3(tmp, 8, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S0 = ((__global double16 *)source)[4].Se;
  vstore3(tmp, 9, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[5].S5;
  vstore3(tmp, 10, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s2 = ((__global double16 *)source)[5].sc;
  tmp.s1 = ((__global double16 *)source)[5].sA;
  vstore3(tmp, 11, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s2 = ((__global double16 *)source)[6].s4;
  tmp.S0 = ((__global double16 *)source)[6].s2;
  vstore3(tmp, 12, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[6].sD;
  tmp.S1 = ((__global double16 *)source)[6].sE;
  vstore3(tmp, 13, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[7].s0;
  tmp.s1 = ((__global double16 *)source)[7].s1;
  vstore3(tmp, 14, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[7].SB;
  tmp.s1 = ((__global double16 *)source)[7].SE;
  vstore3(tmp, 15, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[8].s0;
  tmp.S1 = ((__global double16 *)source)[8].s2;
  vstore3(tmp, 16, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s2 = ((__global double16 *)source)[8].SA;
  tmp.s1 = ((__global double16 *)source)[8].sF;
  vstore3(tmp, 17, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S2 = ((__global double16 *)source)[9].S2;
  tmp.s1 = ((__global double16 *)source)[9].s1;
  vstore3(tmp, 18, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[9].Sd;
  tmp.S2 = ((__global double16 *)source)[9].SC;
  vstore3(tmp, 19, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[10].s0;
  tmp.s0 = ((__global double16 *)source)[10].s2;
  vstore3(tmp, 20, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[10].s9;
  tmp.S2 = ((__global double16 *)source)[10].SB;
  vstore3(tmp, 21, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S0 = ((__global double16 *)source)[11].S4;
  tmp.S1 = ((__global double16 *)source)[11].s6;
  vstore3(tmp, 22, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[11].sd;
  tmp.S0 = ((__global double16 *)source)[11].s8;
  vstore3(tmp, 23, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[12].S6;
  tmp.S0 = ((__global double16 *)source)[12].s2;
  vstore3(tmp, 24, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[12].sf;
  tmp.S1 = ((__global double16 *)source)[12].sC;
  vstore3(tmp, 25, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S2 = ((__global double16 *)source)[13].S2;
  tmp.S0 = ((__global double16 *)source)[13].s6;
  vstore3(tmp, 26, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S2 = ((__global double16 *)source)[13].se;
  tmp.s1 = ((__global double16 *)source)[13].sc;
  vstore3(tmp, 27, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[14].s3;
  tmp.s0 = ((__global double16 *)source)[14].S3;
  vstore3(tmp, 28, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[14].SD;
  tmp.S2 = ((__global double16 *)source)[14].sa;
  vstore3(tmp, 29, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s2 = ((__global double16 *)source)[15].S0;
  tmp.S0 = ((__global double16 *)source)[15].s4;
  vstore3(tmp, 30, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S0 = ((__global double16 *)source)[15].sB;
  tmp.S1 = ((__global double16 *)source)[15].sD;
  vstore3(tmp, 31, (__global double *)dest);
}
