// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global char8 *source, __global char *dest) {
  if (get_global_id(0) != 0)
    return;
  // char8 src1 /*, src2*/;
  char3 tmp;
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[0].s6;
  vstore3(tmp, 0, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S1 = ((__global char16 *)source)[0].sD;
  vstore3(tmp, 1, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S1 = ((__global char16 *)source)[1].S1;
  vstore3(tmp, 2, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s0 = ((__global char16 *)source)[1].Sf;
  vstore3(tmp, 3, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s0 = ((__global char16 *)source)[2].S5;
  vstore3(tmp, 4, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s0 = ((__global char16 *)source)[2].sC;
  vstore3(tmp, 5, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S2 = ((__global char16 *)source)[3].S7;
  vstore3(tmp, 6, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s0 = ((__global char16 *)source)[3].s9;
  vstore3(tmp, 7, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s0 = ((__global char16 *)source)[4].S4;
  vstore3(tmp, 8, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S0 = ((__global char16 *)source)[4].se;
  vstore3(tmp, 9, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s1 = ((__global char16 *)source)[5].s4;
  vstore3(tmp, 10, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S0 = ((__global char16 *)source)[5].sc;
  tmp.s1 = ((__global char16 *)source)[5].SE;
  vstore3(tmp, 11, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S0 = ((__global char16 *)source)[6].S3;
  tmp.s1 = ((__global char16 *)source)[6].s0;
  vstore3(tmp, 12, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[6].sE;
  tmp.S1 = ((__global char16 *)source)[6].s8;
  vstore3(tmp, 13, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S0 = ((__global char16 *)source)[7].S1;
  tmp.s1 = ((__global char16 *)source)[7].S0;
  vstore3(tmp, 14, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[7].sb;
  tmp.s0 = ((__global char16 *)source)[7].Sf;
  vstore3(tmp, 15, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S2 = ((__global char16 *)source)[8].S3;
  tmp.S1 = ((__global char16 *)source)[8].s3;
  vstore3(tmp, 16, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S0 = ((__global char16 *)source)[8].sA;
  tmp.s1 = ((__global char16 *)source)[8].S9;
  vstore3(tmp, 17, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S0 = ((__global char16 *)source)[9].s5;
  tmp.S2 = ((__global char16 *)source)[9].S7;
  vstore3(tmp, 18, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[9].sC;
  tmp.S0 = ((__global char16 *)source)[9].Sd;
  vstore3(tmp, 19, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s1 = ((__global char16 *)source)[10].S2;
  tmp.s2 = ((__global char16 *)source)[10].s4;
  vstore3(tmp, 20, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S0 = ((__global char16 *)source)[10].S8;
  tmp.S2 = ((__global char16 *)source)[10].sF;
  vstore3(tmp, 21, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S2 = ((__global char16 *)source)[11].S1;
  tmp.S0 = ((__global char16 *)source)[11].s4;
  vstore3(tmp, 22, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S2 = ((__global char16 *)source)[11].sF;
  tmp.s0 = ((__global char16 *)source)[11].Sa;
  vstore3(tmp, 23, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s0 = ((__global char16 *)source)[12].S0;
  tmp.S2 = ((__global char16 *)source)[12].s7;
  vstore3(tmp, 24, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s1 = ((__global char16 *)source)[12].SD;
  tmp.S2 = ((__global char16 *)source)[12].sB;
  vstore3(tmp, 25, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s1 = ((__global char16 *)source)[13].S0;
  tmp.s0 = ((__global char16 *)source)[13].s1;
  vstore3(tmp, 26, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S2 = ((__global char16 *)source)[13].se;
  tmp.s0 = ((__global char16 *)source)[13].s9;
  vstore3(tmp, 27, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.s2 = ((__global char16 *)source)[14].s2;
  tmp.S0 = ((__global char16 *)source)[14].s4;
  vstore3(tmp, 28, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S2 = ((__global char16 *)source)[14].Se;
  tmp.S0 = ((__global char16 *)source)[14].sA;
  vstore3(tmp, 29, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S2 = ((__global char16 *)source)[15].s2;
  tmp.s0 = ((__global char16 *)source)[15].s0;
  vstore3(tmp, 30, (__global char *)dest);
  tmp = (char)((char)0);
  tmp.S2 = ((__global char16 *)source)[15].S8;
  tmp.s0 = ((__global char16 *)source)[15].SB;
  vstore3(tmp, 31, (__global char *)dest);
}
