// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global uchar2 *source, __global uchar *dest) {
  if (get_global_id(0) != 0)
    return;
  // uchar2 src1 /*, src2*/;
  uchar3 tmp;
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[0].s0;
  vstore3(tmp, 0, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[0].S2;
  vstore3(tmp, 1, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[0].S4;
  vstore3(tmp, 2, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S1 = ((__global uchar16 *)source)[0].S6;
  vstore3(tmp, 3, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s1 = ((__global uchar16 *)source)[0].s8;
  vstore3(tmp, 4, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s2 = ((__global uchar16 *)source)[0].Sa;
  vstore3(tmp, 5, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[0].SC;
  vstore3(tmp, 6, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S1 = ((__global uchar16 *)source)[0].SF;
  vstore3(tmp, 7, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s1 = ((__global uchar16 *)source)[1].s1;
  vstore3(tmp, 8, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s2 = ((__global uchar16 *)source)[1].s2;
  vstore3(tmp, 9, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s2 = ((__global uchar16 *)source)[1].S5;
  vstore3(tmp, 10, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s1 = ((__global uchar16 *)source)[1].s6;
  vstore3(tmp, 11, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S2 = ((__global uchar16 *)source)[1].s9;
  vstore3(tmp, 12, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S0 = ((__global uchar16 *)source)[1].sa;
  vstore3(tmp, 13, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S0 = ((__global uchar16 *)source)[1].Sd;
  vstore3(tmp, 14, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s1 = ((__global uchar16 *)source)[1].Sf;
  vstore3(tmp, 15, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S0 = ((__global uchar16 *)source)[2].s0;
  tmp.S1 = ((__global uchar16 *)source)[2].S1;
  vstore3(tmp, 16, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S1 = ((__global uchar16 *)source)[2].S2;
  tmp.s0 = ((__global uchar16 *)source)[2].S3;
  vstore3(tmp, 17, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s1 = ((__global uchar16 *)source)[2].s4;
  tmp.S0 = ((__global uchar16 *)source)[2].s4;
  vstore3(tmp, 18, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s1 = ((__global uchar16 *)source)[2].S6;
  tmp.s0 = ((__global uchar16 *)source)[2].s7;
  vstore3(tmp, 19, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s1 = ((__global uchar16 *)source)[2].s8;
  tmp.S2 = ((__global uchar16 *)source)[2].s9;
  vstore3(tmp, 20, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s2 = ((__global uchar16 *)source)[2].sA;
  tmp.S0 = ((__global uchar16 *)source)[2].Sa;
  vstore3(tmp, 21, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s2 = ((__global uchar16 *)source)[2].sc;
  tmp.S1 = ((__global uchar16 *)source)[2].sd;
  vstore3(tmp, 22, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[2].sE;
  tmp.S1 = ((__global uchar16 *)source)[2].SE;
  vstore3(tmp, 23, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S1 = ((__global uchar16 *)source)[3].S1;
  tmp.S0 = ((__global uchar16 *)source)[3].S0;
  vstore3(tmp, 24, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[3].S2;
  tmp.S2 = ((__global uchar16 *)source)[3].S2;
  vstore3(tmp, 25, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s2 = ((__global uchar16 *)source)[3].s5;
  tmp.S0 = ((__global uchar16 *)source)[3].s5;
  vstore3(tmp, 26, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[3].S6;
  tmp.s2 = ((__global uchar16 *)source)[3].S7;
  vstore3(tmp, 27, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.S1 = ((__global uchar16 *)source)[3].s8;
  tmp.s2 = ((__global uchar16 *)source)[3].s9;
  vstore3(tmp, 28, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s0 = ((__global uchar16 *)source)[3].SB;
  tmp.s2 = ((__global uchar16 *)source)[3].SA;
  vstore3(tmp, 29, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s2 = ((__global uchar16 *)source)[3].sd;
  tmp.S1 = ((__global uchar16 *)source)[3].Sc;
  vstore3(tmp, 30, (__global uchar *)dest);
  tmp = (uchar)((uchar)0);
  tmp.s2 = ((__global uchar16 *)source)[3].sf;
  tmp.s0 = ((__global uchar16 *)source)[3].sf;
  vstore3(tmp, 31, (__global uchar *)dest);
}
