// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global ushort *source, __global ushort *dest) {
  if (get_global_id(0) != 0)
    return;
  // ushort src1 /*, src2*/;
  ushort3 tmp;
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[0].s0;
  vstore3(tmp, 0, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[0].S1;
  vstore3(tmp, 1, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s0 = ((__global ushort16 *)source)[0].S2;
  vstore3(tmp, 2, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[0].S3;
  vstore3(tmp, 3, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[0].s4;
  vstore3(tmp, 4, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[0].S5;
  vstore3(tmp, 5, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[0].s6;
  vstore3(tmp, 6, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[0].s7;
  vstore3(tmp, 7, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S0 = ((__global ushort16 *)source)[0].S8;
  vstore3(tmp, 8, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S0 = ((__global ushort16 *)source)[0].s9;
  vstore3(tmp, 9, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[0].SA;
  vstore3(tmp, 10, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S2 = ((__global ushort16 *)source)[0].sb;
  vstore3(tmp, 11, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S2 = ((__global ushort16 *)source)[0].sc;
  vstore3(tmp, 12, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[0].SD;
  vstore3(tmp, 13, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[0].sE;
  vstore3(tmp, 14, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S0 = ((__global ushort16 *)source)[0].sf;
  vstore3(tmp, 15, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[1].S0;
  vstore3(tmp, 16, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S0 = ((__global ushort16 *)source)[1].s1;
  vstore3(tmp, 17, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[1].s2;
  vstore3(tmp, 18, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S2 = ((__global ushort16 *)source)[1].s3;
  vstore3(tmp, 19, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[1].S4;
  vstore3(tmp, 20, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s0 = ((__global ushort16 *)source)[1].s5;
  vstore3(tmp, 21, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s0 = ((__global ushort16 *)source)[1].s6;
  vstore3(tmp, 22, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[1].s7;
  vstore3(tmp, 23, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[1].S8;
  vstore3(tmp, 24, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S0 = ((__global ushort16 *)source)[1].S9;
  vstore3(tmp, 25, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[1].sa;
  vstore3(tmp, 26, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S2 = ((__global ushort16 *)source)[1].SB;
  vstore3(tmp, 27, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[1].sc;
  vstore3(tmp, 28, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[1].SD;
  vstore3(tmp, 29, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S0 = ((__global ushort16 *)source)[1].sE;
  vstore3(tmp, 30, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[1].sf;
  vstore3(tmp, 31, (__global ushort *)dest);
}
