// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global ulong8 *source, __global ulong *dest) {
  if (get_global_id(0) != 0)
    return;
  // ulong8 src1 /*, src2*/;
  ulong3 tmp;
  tmp = (ulong)((ulong)0);
  tmp.s1 = ((__global ulong16 *)source)[0].s5;
  vstore3(tmp, 0, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s1 = ((__global ulong16 *)source)[0].Sa;
  vstore3(tmp, 1, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[1].s3;
  vstore3(tmp, 2, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[1].sC;
  vstore3(tmp, 3, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S0 = ((__global ulong16 *)source)[2].S6;
  vstore3(tmp, 4, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[2].Sc;
  vstore3(tmp, 5, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s1 = ((__global ulong16 *)source)[3].S0;
  vstore3(tmp, 6, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S0 = ((__global ulong16 *)source)[3].SB;
  vstore3(tmp, 7, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S0 = ((__global ulong16 *)source)[4].S7;
  vstore3(tmp, 8, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s1 = ((__global ulong16 *)source)[4].Sd;
  vstore3(tmp, 9, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S0 = ((__global ulong16 *)source)[5].s6;
  vstore3(tmp, 10, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s2 = ((__global ulong16 *)source)[5].SB;
  tmp.S0 = ((__global ulong16 *)source)[5].Se;
  vstore3(tmp, 11, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S2 = ((__global ulong16 *)source)[6].s0;
  tmp.s0 = ((__global ulong16 *)source)[6].S0;
  vstore3(tmp, 12, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s2 = ((__global ulong16 *)source)[6].sd;
  tmp.S0 = ((__global ulong16 *)source)[6].SD;
  vstore3(tmp, 13, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s1 = ((__global ulong16 *)source)[7].S4;
  tmp.s0 = ((__global ulong16 *)source)[7].s7;
  vstore3(tmp, 14, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S1 = ((__global ulong16 *)source)[7].sc;
  tmp.S0 = ((__global ulong16 *)source)[7].sd;
  vstore3(tmp, 15, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S2 = ((__global ulong16 *)source)[8].S6;
  tmp.S1 = ((__global ulong16 *)source)[8].S5;
  vstore3(tmp, 16, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s2 = ((__global ulong16 *)source)[8].SB;
  tmp.S1 = ((__global ulong16 *)source)[8].sf;
  vstore3(tmp, 17, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S0 = ((__global ulong16 *)source)[9].s7;
  tmp.S2 = ((__global ulong16 *)source)[9].s6;
  vstore3(tmp, 18, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S0 = ((__global ulong16 *)source)[9].sb;
  tmp.S2 = ((__global ulong16 *)source)[9].Sb;
  vstore3(tmp, 19, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s2 = ((__global ulong16 *)source)[10].S4;
  tmp.S1 = ((__global ulong16 *)source)[10].S0;
  vstore3(tmp, 20, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[10].SC;
  tmp.S1 = ((__global ulong16 *)source)[10].SF;
  vstore3(tmp, 21, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s2 = ((__global ulong16 *)source)[11].s5;
  tmp.s0 = ((__global ulong16 *)source)[11].s7;
  vstore3(tmp, 22, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[11].Sf;
  tmp.S2 = ((__global ulong16 *)source)[11].Sb;
  vstore3(tmp, 23, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S1 = ((__global ulong16 *)source)[12].S6;
  tmp.s0 = ((__global ulong16 *)source)[12].s0;
  vstore3(tmp, 24, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s0 = ((__global ulong16 *)source)[12].Sa;
  tmp.S2 = ((__global ulong16 *)source)[12].SC;
  vstore3(tmp, 25, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S0 = ((__global ulong16 *)source)[13].S6;
  tmp.s1 = ((__global ulong16 *)source)[13].S5;
  vstore3(tmp, 26, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S1 = ((__global ulong16 *)source)[13].S9;
  tmp.s0 = ((__global ulong16 *)source)[13].sE;
  vstore3(tmp, 27, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S2 = ((__global ulong16 *)source)[14].S5;
  tmp.s0 = ((__global ulong16 *)source)[14].s5;
  vstore3(tmp, 28, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S0 = ((__global ulong16 *)source)[14].sb;
  tmp.s2 = ((__global ulong16 *)source)[14].sf;
  vstore3(tmp, 29, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.S0 = ((__global ulong16 *)source)[15].S7;
  tmp.s2 = ((__global ulong16 *)source)[15].S4;
  vstore3(tmp, 30, (__global ulong *)dest);
  tmp = (ulong)((ulong)0);
  tmp.s1 = ((__global ulong16 *)source)[15].sC;
  tmp.S0 = ((__global ulong16 *)source)[15].sf;
  vstore3(tmp, 31, (__global ulong *)dest);
}
