// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
__kernel void sample_test(__global double8 *source, __global double *dest) {
  if (get_global_id(0) != 0)
    return;
  // double8 src1 /*, src2*/;
  double3 tmp;
  tmp = (double)((double)0);
  tmp.S2 = ((__global double16 *)source)[0].S5;
  vstore3(tmp, 0, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[0].sF;
  vstore3(tmp, 1, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S0 = ((__global double16 *)source)[1].S7;
  vstore3(tmp, 2, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[1].sE;
  vstore3(tmp, 3, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s2 = ((__global double16 *)source)[2].s4;
  vstore3(tmp, 4, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S0 = ((__global double16 *)source)[2].SB;
  vstore3(tmp, 5, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s2 = ((__global double16 *)source)[3].s3;
  vstore3(tmp, 6, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S2 = ((__global double16 *)source)[3].sa;
  vstore3(tmp, 7, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[4].s1;
  vstore3(tmp, 8, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[4].sc;
  vstore3(tmp, 9, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S0 = ((__global double16 *)source)[5].s4;
  vstore3(tmp, 10, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[5].sC;
  tmp.S2 = ((__global double16 *)source)[5].sF;
  vstore3(tmp, 11, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[6].s7;
  tmp.s2 = ((__global double16 *)source)[6].S0;
  vstore3(tmp, 12, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s2 = ((__global double16 *)source)[6].se;
  tmp.S0 = ((__global double16 *)source)[6].Sd;
  vstore3(tmp, 13, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[7].S4;
  tmp.s2 = ((__global double16 *)source)[7].S1;
  vstore3(tmp, 14, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[7].sC;
  tmp.s0 = ((__global double16 *)source)[7].sE;
  vstore3(tmp, 15, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[8].s1;
  tmp.s2 = ((__global double16 *)source)[8].s4;
  vstore3(tmp, 16, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s1 = ((__global double16 *)source)[8].Se;
  tmp.s2 = ((__global double16 *)source)[8].s9;
  vstore3(tmp, 17, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S0 = ((__global double16 *)source)[9].S6;
  tmp.S1 = ((__global double16 *)source)[9].s1;
  vstore3(tmp, 18, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[9].SD;
  tmp.S1 = ((__global double16 *)source)[9].Sc;
  vstore3(tmp, 19, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s2 = ((__global double16 *)source)[10].s7;
  tmp.s1 = ((__global double16 *)source)[10].s4;
  vstore3(tmp, 20, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S0 = ((__global double16 *)source)[10].SA;
  tmp.s1 = ((__global double16 *)source)[10].S8;
  vstore3(tmp, 21, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[11].S2;
  tmp.S2 = ((__global double16 *)source)[11].s3;
  vstore3(tmp, 22, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S2 = ((__global double16 *)source)[11].sf;
  tmp.S1 = ((__global double16 *)source)[11].sB;
  vstore3(tmp, 23, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[12].S6;
  tmp.s2 = ((__global double16 *)source)[12].S0;
  vstore3(tmp, 24, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[12].Sc;
  tmp.S2 = ((__global double16 *)source)[12].sd;
  vstore3(tmp, 25, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.s0 = ((__global double16 *)source)[13].s7;
  tmp.s1 = ((__global double16 *)source)[13].s3;
  vstore3(tmp, 26, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[13].SD;
  tmp.S2 = ((__global double16 *)source)[13].S9;
  vstore3(tmp, 27, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S2 = ((__global double16 *)source)[14].s1;
  tmp.s0 = ((__global double16 *)source)[14].S6;
  vstore3(tmp, 28, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[14].sd;
  tmp.S2 = ((__global double16 *)source)[14].SD;
  vstore3(tmp, 29, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S2 = ((__global double16 *)source)[15].s4;
  tmp.s0 = ((__global double16 *)source)[15].S0;
  vstore3(tmp, 30, (__global double *)dest);
  tmp = (double)((double)0);
  tmp.S1 = ((__global double16 *)source)[15].sd;
  tmp.S2 = ((__global double16 *)source)[15].s8;
  vstore3(tmp, 31, (__global double *)dest);
}
