// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global ushort2 *source, __global ushort *dest) {
  if (get_global_id(0) != 0)
    return;
  // ushort2 src1 /*, src2*/;
  ushort3 tmp;
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[0].s1;
  vstore3(tmp, 0, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[0].S2;
  vstore3(tmp, 1, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S2 = ((__global ushort16 *)source)[0].S4;
  vstore3(tmp, 2, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[0].s6;
  vstore3(tmp, 3, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S0 = ((__global ushort16 *)source)[0].s9;
  vstore3(tmp, 4, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s0 = ((__global ushort16 *)source)[0].Sa;
  vstore3(tmp, 5, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[0].SD;
  vstore3(tmp, 6, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S2 = ((__global ushort16 *)source)[0].sF;
  vstore3(tmp, 7, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[1].S0;
  vstore3(tmp, 8, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S2 = ((__global ushort16 *)source)[1].s2;
  vstore3(tmp, 9, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s0 = ((__global ushort16 *)source)[1].s5;
  vstore3(tmp, 10, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[1].S6;
  vstore3(tmp, 11, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s0 = ((__global ushort16 *)source)[1].s9;
  vstore3(tmp, 12, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[1].sB;
  vstore3(tmp, 13, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[1].sd;
  vstore3(tmp, 14, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[1].SE;
  vstore3(tmp, 15, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[2].s0;
  tmp.s2 = ((__global ushort16 *)source)[2].S0;
  vstore3(tmp, 16, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[2].S3;
  tmp.s2 = ((__global ushort16 *)source)[2].S3;
  vstore3(tmp, 17, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[2].S5;
  tmp.S0 = ((__global ushort16 *)source)[2].S5;
  vstore3(tmp, 18, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[2].s6;
  tmp.s0 = ((__global ushort16 *)source)[2].s7;
  vstore3(tmp, 19, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S0 = ((__global ushort16 *)source)[2].S9;
  tmp.S2 = ((__global ushort16 *)source)[2].S9;
  vstore3(tmp, 20, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[2].sA;
  tmp.S2 = ((__global ushort16 *)source)[2].sA;
  vstore3(tmp, 21, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[2].SC;
  tmp.S2 = ((__global ushort16 *)source)[2].sC;
  vstore3(tmp, 22, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s0 = ((__global ushort16 *)source)[2].se;
  tmp.S1 = ((__global ushort16 *)source)[2].SE;
  vstore3(tmp, 23, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s0 = ((__global ushort16 *)source)[3].s0;
  tmp.S1 = ((__global ushort16 *)source)[3].s1;
  vstore3(tmp, 24, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[3].s2;
  tmp.S2 = ((__global ushort16 *)source)[3].S2;
  vstore3(tmp, 25, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[3].s4;
  tmp.S0 = ((__global ushort16 *)source)[3].S4;
  vstore3(tmp, 26, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[3].s6;
  tmp.s2 = ((__global ushort16 *)source)[3].S6;
  vstore3(tmp, 27, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S2 = ((__global ushort16 *)source)[3].S8;
  tmp.S1 = ((__global ushort16 *)source)[3].S9;
  vstore3(tmp, 28, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S0 = ((__global ushort16 *)source)[3].Sb;
  tmp.s1 = ((__global ushort16 *)source)[3].sA;
  vstore3(tmp, 29, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S0 = ((__global ushort16 *)source)[3].sC;
  tmp.s2 = ((__global ushort16 *)source)[3].sd;
  vstore3(tmp, 30, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s0 = ((__global ushort16 *)source)[3].SF;
  tmp.S2 = ((__global ushort16 *)source)[3].sE;
  vstore3(tmp, 31, (__global ushort *)dest);
}
