// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global ushort4 *source, __global ushort *dest) {
  if (get_global_id(0) != 0)
    return;
  // ushort4 src1 /*, src2*/;
  ushort3 tmp;
  tmp = (ushort)((ushort)0);
  tmp.S2 = ((__global ushort16 *)source)[0].S1;
  vstore3(tmp, 0, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[0].S4;
  vstore3(tmp, 1, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S2 = ((__global ushort16 *)source)[0].s9;
  vstore3(tmp, 2, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[0].sc;
  vstore3(tmp, 3, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[1].S2;
  vstore3(tmp, 4, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S0 = ((__global ushort16 *)source)[1].S4;
  vstore3(tmp, 5, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S0 = ((__global ushort16 *)source)[1].sa;
  vstore3(tmp, 6, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s0 = ((__global ushort16 *)source)[1].Se;
  vstore3(tmp, 7, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s0 = ((__global ushort16 *)source)[2].S3;
  vstore3(tmp, 8, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S2 = ((__global ushort16 *)source)[2].s6;
  vstore3(tmp, 9, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S2 = ((__global ushort16 *)source)[2].S8;
  vstore3(tmp, 10, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S2 = ((__global ushort16 *)source)[2].Sd;
  tmp.S1 = ((__global ushort16 *)source)[2].se;
  vstore3(tmp, 11, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S0 = ((__global ushort16 *)source)[3].s3;
  tmp.s2 = ((__global ushort16 *)source)[3].s1;
  vstore3(tmp, 12, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S2 = ((__global ushort16 *)source)[3].s4;
  tmp.s0 = ((__global ushort16 *)source)[3].s4;
  vstore3(tmp, 13, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[3].sb;
  tmp.s1 = ((__global ushort16 *)source)[3].Sa;
  vstore3(tmp, 14, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S0 = ((__global ushort16 *)source)[3].SE;
  tmp.s2 = ((__global ushort16 *)source)[3].sF;
  vstore3(tmp, 15, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[4].s1;
  tmp.s1 = ((__global ushort16 *)source)[4].S2;
  vstore3(tmp, 16, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[4].S7;
  tmp.s0 = ((__global ushort16 *)source)[4].S5;
  vstore3(tmp, 17, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[4].SA;
  tmp.S2 = ((__global ushort16 *)source)[4].s8;
  vstore3(tmp, 18, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s0 = ((__global ushort16 *)source)[4].sD;
  tmp.S1 = ((__global ushort16 *)source)[4].sd;
  vstore3(tmp, 19, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s0 = ((__global ushort16 *)source)[5].s2;
  tmp.S2 = ((__global ushort16 *)source)[5].s1;
  vstore3(tmp, 20, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[5].s5;
  tmp.S0 = ((__global ushort16 *)source)[5].S6;
  vstore3(tmp, 21, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s0 = ((__global ushort16 *)source)[5].S9;
  tmp.S1 = ((__global ushort16 *)source)[5].s9;
  vstore3(tmp, 22, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[5].Sc;
  tmp.s0 = ((__global ushort16 *)source)[5].se;
  vstore3(tmp, 23, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[6].s1;
  tmp.S0 = ((__global ushort16 *)source)[6].S1;
  vstore3(tmp, 24, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[6].S4;
  tmp.s0 = ((__global ushort16 *)source)[6].S6;
  vstore3(tmp, 25, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[6].SB;
  tmp.S0 = ((__global ushort16 *)source)[6].S8;
  vstore3(tmp, 26, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[6].sc;
  tmp.S1 = ((__global ushort16 *)source)[6].Se;
  vstore3(tmp, 27, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S2 = ((__global ushort16 *)source)[7].S2;
  tmp.s0 = ((__global ushort16 *)source)[7].S0;
  vstore3(tmp, 28, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s2 = ((__global ushort16 *)source)[7].s6;
  tmp.S1 = ((__global ushort16 *)source)[7].s4;
  vstore3(tmp, 29, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.s1 = ((__global ushort16 *)source)[7].s8;
  tmp.s2 = ((__global ushort16 *)source)[7].S8;
  vstore3(tmp, 30, (__global ushort *)dest);
  tmp = (ushort)((ushort)0);
  tmp.S1 = ((__global ushort16 *)source)[7].sD;
  tmp.s2 = ((__global ushort16 *)source)[7].SE;
  vstore3(tmp, 31, (__global ushort *)dest);
}
