// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global uint8 *source, __global uint *dest) {
  if (get_global_id(0) != 0)
    return;
  // uint8 src1 /*, src2*/;
  uint3 tmp;
  tmp = (uint)((uint)0);
  tmp.S2 = ((__global uint16 *)source)[0].s7;
  vstore3(tmp, 0, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[0].SD;
  vstore3(tmp, 1, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[1].S1;
  vstore3(tmp, 2, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s0 = ((__global uint16 *)source)[1].Sb;
  vstore3(tmp, 3, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[2].S3;
  vstore3(tmp, 4, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s1 = ((__global uint16 *)source)[2].sA;
  vstore3(tmp, 5, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[3].s7;
  vstore3(tmp, 6, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S2 = ((__global uint16 *)source)[3].Se;
  vstore3(tmp, 7, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s0 = ((__global uint16 *)source)[4].s2;
  vstore3(tmp, 8, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S1 = ((__global uint16 *)source)[4].Sc;
  vstore3(tmp, 9, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s1 = ((__global uint16 *)source)[5].S4;
  vstore3(tmp, 10, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[5].S8;
  tmp.S2 = ((__global uint16 *)source)[5].sF;
  vstore3(tmp, 11, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S2 = ((__global uint16 *)source)[6].s1;
  tmp.s1 = ((__global uint16 *)source)[6].S1;
  vstore3(tmp, 12, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[6].sE;
  tmp.s2 = ((__global uint16 *)source)[6].SF;
  vstore3(tmp, 13, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[7].S7;
  tmp.S1 = ((__global uint16 *)source)[7].S5;
  vstore3(tmp, 14, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S1 = ((__global uint16 *)source)[7].SA;
  tmp.s2 = ((__global uint16 *)source)[7].S9;
  vstore3(tmp, 15, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[8].s3;
  tmp.s1 = ((__global uint16 *)source)[8].S5;
  vstore3(tmp, 16, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S2 = ((__global uint16 *)source)[8].sB;
  tmp.S0 = ((__global uint16 *)source)[8].SA;
  vstore3(tmp, 17, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S2 = ((__global uint16 *)source)[9].s0;
  tmp.s1 = ((__global uint16 *)source)[9].S0;
  vstore3(tmp, 18, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[9].Sf;
  tmp.S1 = ((__global uint16 *)source)[9].s9;
  vstore3(tmp, 19, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[10].s5;
  tmp.S1 = ((__global uint16 *)source)[10].s2;
  vstore3(tmp, 20, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S1 = ((__global uint16 *)source)[10].sA;
  tmp.S2 = ((__global uint16 *)source)[10].sd;
  vstore3(tmp, 21, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S2 = ((__global uint16 *)source)[11].s3;
  tmp.s1 = ((__global uint16 *)source)[11].s3;
  vstore3(tmp, 22, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[11].SA;
  tmp.s0 = ((__global uint16 *)source)[11].s9;
  vstore3(tmp, 23, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s0 = ((__global uint16 *)source)[12].s6;
  tmp.S1 = ((__global uint16 *)source)[12].s5;
  vstore3(tmp, 24, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s0 = ((__global uint16 *)source)[12].Sd;
  tmp.S1 = ((__global uint16 *)source)[12].Sd;
  vstore3(tmp, 25, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S1 = ((__global uint16 *)source)[13].S0;
  tmp.S0 = ((__global uint16 *)source)[13].S7;
  vstore3(tmp, 26, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s2 = ((__global uint16 *)source)[13].s9;
  tmp.s1 = ((__global uint16 *)source)[13].se;
  vstore3(tmp, 27, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.s1 = ((__global uint16 *)source)[14].S3;
  tmp.S0 = ((__global uint16 *)source)[14].s6;
  vstore3(tmp, 28, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[14].sb;
  tmp.s1 = ((__global uint16 *)source)[14].Sa;
  vstore3(tmp, 29, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S2 = ((__global uint16 *)source)[15].S3;
  tmp.s1 = ((__global uint16 *)source)[15].S3;
  vstore3(tmp, 30, (__global uint *)dest);
  tmp = (uint)((uint)0);
  tmp.S0 = ((__global uint16 *)source)[15].Sc;
  tmp.S2 = ((__global uint16 *)source)[15].sb;
  vstore3(tmp, 31, (__global uint *)dest);
}
