// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global int *source, __global int *dest) {
  if (get_global_id(0) != 0)
    return;
  // int3 src1 /*, src2*/;
  int3 tmp;
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[0].S0;
  vstore3(tmp, 0, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[0].S3;
  vstore3(tmp, 1, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[0].s8;
  vstore3(tmp, 2, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[0].sA;
  vstore3(tmp, 3, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[0].sc;
  vstore3(tmp, 4, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[0].Sf;
  vstore3(tmp, 5, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[1].s3;
  vstore3(tmp, 6, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[1].s7;
  vstore3(tmp, 7, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[1].S8;
  vstore3(tmp, 8, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[1].sc;
  vstore3(tmp, 9, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[1].SE;
  vstore3(tmp, 10, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[2].s3;
  tmp.S2 = ((__global int16 *)source)[2].S2;
  vstore3(tmp, 11, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[2].S6;
  tmp.s1 = ((__global int16 *)source)[2].S6;
  vstore3(tmp, 12, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[2].S9;
  tmp.S2 = ((__global int16 *)source)[2].S8;
  vstore3(tmp, 13, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[2].sc;
  tmp.S2 = ((__global int16 *)source)[2].sC;
  vstore3(tmp, 14, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[2].SD;
  tmp.s1 = ((__global int16 *)source)[2].Sf;
  vstore3(tmp, 15, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[3].S1;
  tmp.s1 = ((__global int16 *)source)[3].s0;
  vstore3(tmp, 16, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[3].S5;
  tmp.s2 = ((__global int16 *)source)[3].S4;
  vstore3(tmp, 17, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[3].S7;
  tmp.s1 = ((__global int16 *)source)[3].S7;
  vstore3(tmp, 18, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[3].sb;
  tmp.s1 = ((__global int16 *)source)[3].S9;
  vstore3(tmp, 19, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[3].sc;
  tmp.S2 = ((__global int16 *)source)[3].SD;
  vstore3(tmp, 20, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[4].s1;
  tmp.S2 = ((__global int16 *)source)[3].Sf;
  vstore3(tmp, 21, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[4].S4;
  tmp.S2 = ((__global int16 *)source)[4].S2;
  vstore3(tmp, 22, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[4].s5;
  tmp.S0 = ((__global int16 *)source)[4].S5;
  vstore3(tmp, 23, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[4].s9;
  tmp.s0 = ((__global int16 *)source)[4].S8;
  vstore3(tmp, 24, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[4].SD;
  tmp.S0 = ((__global int16 *)source)[4].SB;
  vstore3(tmp, 25, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[4].sF;
  tmp.S0 = ((__global int16 *)source)[4].Sf;
  vstore3(tmp, 26, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[5].s2;
  tmp.S1 = ((__global int16 *)source)[5].S2;
  vstore3(tmp, 27, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[5].s6;
  tmp.s1 = ((__global int16 *)source)[5].s6;
  vstore3(tmp, 28, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[5].s9;
  tmp.s1 = ((__global int16 *)source)[5].S7;
  vstore3(tmp, 29, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[5].sC;
  tmp.S2 = ((__global int16 *)source)[5].Sa;
  vstore3(tmp, 30, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[5].sd;
  tmp.s1 = ((__global int16 *)source)[5].sD;
  vstore3(tmp, 31, (__global int *)dest);
}
