// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
double16 shuffle_fn(double16 source);
double16 shuffle_fn(double16 source) { return source; }

__kernel void sample_test(__global double16 *source, __global double2 *dest) {
  if (get_global_id(0) != 0)
    return;
  // double16 src1 /*, src2*/;
  double2 tmp;
  tmp = (double2)((double)0);
  tmp.s1 = shuffle_fn(source[0]).sD;
  dest[0] = tmp;
  tmp = (double2)((double)0);
  tmp.s1 = shuffle_fn(source[1]).S5;
  dest[1] = tmp;
  tmp = (double2)((double)0);
  tmp.S1 = shuffle_fn(source[2]).SF;
  dest[2] = tmp;
  tmp = (double2)((double)0);
  tmp.s1 = shuffle_fn(source[3]).sF;
  dest[3] = tmp;
  tmp = (double2)((double)0);
  tmp.s1 = shuffle_fn(source[4]).sF;
  dest[4] = tmp;
  tmp = (double2)((double)0);
  tmp.S0 = shuffle_fn(source[5]).s8;
  dest[5] = tmp;
  tmp = (double2)((double)0);
  tmp.s0 = shuffle_fn(source[6]).sA;
  dest[6] = tmp;
  tmp = (double2)((double)0);
  tmp.S1 = shuffle_fn(source[7]).S5;
  dest[7] = tmp;
  tmp = (double2)((double)0);
  tmp.S1 = shuffle_fn(source[8]).sf;
  dest[8] = tmp;
  tmp = (double2)((double)0);
  tmp.S0 = shuffle_fn(source[9]).S6;
  dest[9] = tmp;
  tmp = (double2)((double)0);
  tmp.s0 = shuffle_fn(source[10]).s4;
  dest[10] = tmp;
  tmp = (double2)((double)0);
  tmp.s0 = shuffle_fn(source[11]).s4;
  dest[11] = tmp;
  tmp = (double2)((double)0);
  tmp.S1 = shuffle_fn(source[12]).s3;
  dest[12] = tmp;
  tmp = (double2)((double)0);
  tmp.s1 = shuffle_fn(source[13]).sd;
  dest[13] = tmp;
  tmp = (double2)((double)0);
  tmp.s1 = shuffle_fn(source[14]).S9;
  dest[14] = tmp;
  tmp = (double2)((double)0);
  tmp.s1 = shuffle_fn(source[15]).sc;
  dest[15] = tmp;
  tmp = (double2)((double)0);
  tmp.s10 = shuffle_fn(source[16]).S3a;
  dest[16] = tmp;
  tmp = (double2)((double)0);
  tmp.S10 = shuffle_fn(source[17]).S4b;
  dest[17] = tmp;
  tmp = (double2)((double)0);
  tmp.s01 = shuffle_fn(source[18]).s26;
  dest[18] = tmp;
  tmp = (double2)((double)0);
  tmp.S01 = shuffle_fn(source[19]).sF6;
  dest[19] = tmp;
  tmp = (double2)((double)0);
  tmp.S01 = shuffle_fn(source[20]).s96;
  dest[20] = tmp;
  tmp = (double2)((double)0);
  tmp.s10 = shuffle_fn(source[21]).Sde;
  dest[21] = tmp;
  tmp = (double2)((double)0);
  tmp.s10 = shuffle_fn(source[22]).s2E;
  dest[22] = tmp;
  tmp = (double2)((double)0);
  tmp.S01 = shuffle_fn(source[23]).Sf2;
  dest[23] = tmp;
  tmp = (double2)((double)0);
  tmp.S10 = shuffle_fn(source[24]).S99;
  dest[24] = tmp;
  tmp = (double2)((double)0);
  tmp.S01 = shuffle_fn(source[25]).S26;
  dest[25] = tmp;
  tmp = (double2)((double)0);
  tmp.s01 = shuffle_fn(source[26]).s96;
  dest[26] = tmp;
  tmp = (double2)((double)0);
  tmp.S10 = shuffle_fn(source[27]).s0B;
  dest[27] = tmp;
  tmp = (double2)((double)0);
  tmp.s10 = shuffle_fn(source[28]).s78;
  dest[28] = tmp;
  tmp = (double2)((double)0);
  tmp.S10 = shuffle_fn(source[29]).S65;
  dest[29] = tmp;
  tmp = (double2)((double)0);
  tmp.S10 = shuffle_fn(source[30]).S70;
  dest[30] = tmp;
  tmp = (double2)((double)0);
  tmp.S01 = shuffle_fn(source[31]).se4;
  dest[31] = tmp;
}
