// RUN: %occ-cli %s --cl-options= --cl-device=%cl_device %cfg_path
__kernel void sample_test(__global int4 *source, __global int *dest) {
  if (get_global_id(0) != 0)
    return;
  // int4 src1 /*, src2*/;
  int3 tmp;
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[0].s2;
  vstore3(tmp, 0, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[0].S5;
  vstore3(tmp, 1, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[0].sb;
  vstore3(tmp, 2, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[0].sF;
  vstore3(tmp, 3, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[1].S1;
  vstore3(tmp, 4, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[1].s6;
  vstore3(tmp, 5, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[1].S8;
  vstore3(tmp, 6, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[1].sd;
  vstore3(tmp, 7, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s2 = ((__global int16 *)source)[2].s1;
  vstore3(tmp, 8, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[2].s7;
  vstore3(tmp, 9, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[2].Sa;
  vstore3(tmp, 10, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[2].SF;
  tmp.S0 = ((__global int16 *)source)[2].sC;
  vstore3(tmp, 11, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[3].S2;
  tmp.S0 = ((__global int16 *)source)[3].S1;
  vstore3(tmp, 12, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[3].s7;
  tmp.S2 = ((__global int16 *)source)[3].S7;
  vstore3(tmp, 13, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[3].s8;
  tmp.S0 = ((__global int16 *)source)[3].SA;
  vstore3(tmp, 14, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[3].sf;
  tmp.s1 = ((__global int16 *)source)[3].SF;
  vstore3(tmp, 15, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[4].s3;
  tmp.S1 = ((__global int16 *)source)[4].S3;
  vstore3(tmp, 16, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[4].s7;
  tmp.s0 = ((__global int16 *)source)[4].s5;
  vstore3(tmp, 17, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[4].S8;
  tmp.s2 = ((__global int16 *)source)[4].sa;
  vstore3(tmp, 18, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[4].SE;
  tmp.s2 = ((__global int16 *)source)[4].SE;
  vstore3(tmp, 19, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s0 = ((__global int16 *)source)[5].S1;
  tmp.S1 = ((__global int16 *)source)[5].s1;
  vstore3(tmp, 20, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[5].S4;
  tmp.S2 = ((__global int16 *)source)[5].s4;
  vstore3(tmp, 21, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S1 = ((__global int16 *)source)[5].S9;
  tmp.s0 = ((__global int16 *)source)[5].SB;
  vstore3(tmp, 22, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[5].se;
  tmp.S0 = ((__global int16 *)source)[5].SC;
  vstore3(tmp, 23, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[6].S2;
  tmp.S1 = ((__global int16 *)source)[6].S1;
  vstore3(tmp, 24, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[6].s5;
  tmp.s2 = ((__global int16 *)source)[6].S5;
  vstore3(tmp, 25, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[6].sa;
  tmp.S1 = ((__global int16 *)source)[6].sA;
  vstore3(tmp, 26, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[6].se;
  tmp.S2 = ((__global int16 *)source)[6].sE;
  vstore3(tmp, 27, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[7].S0;
  tmp.S2 = ((__global int16 *)source)[7].S2;
  vstore3(tmp, 28, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S0 = ((__global int16 *)source)[7].s7;
  tmp.S2 = ((__global int16 *)source)[7].s5;
  vstore3(tmp, 29, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.s1 = ((__global int16 *)source)[7].sb;
  tmp.s2 = ((__global int16 *)source)[7].s8;
  vstore3(tmp, 30, (__global int *)dest);
  tmp = (int)((int)0);
  tmp.S2 = ((__global int16 *)source)[7].SE;
  tmp.s1 = ((__global int16 *)source)[7].SE;
  vstore3(tmp, 31, (__global int *)dest);
}
