name: On push verification
run-name: '${{ github.event_name }}: ${{ github.ref_name }} ${{ github.base_ref }}'

on:
  push:
    branches:
      - master
      - ocl-open-*
  pull_request:
    branches:
      - master
      - ocl-open-*
    types: [ opened, reopened, edited ]

jobs:

  verify_default_branch:
     # ref_name for 'on: push'
     # base_ref for 'on: pull_request'
    if: ${{ (github.event_name == 'push' && github.ref_name == 'master') || (github.event_name == 'pull_request' && github.base_ref == 'master') }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout opencl-clang sources for action files
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-opencl-clang
        with:
          ref_llvm: main
          ref_translator: main
          ref_opencl-clang: ${{ github.ref }}

  verify_release_branch:
    # ref_name for 'on: push'
    # base_ref for 'on: pull_request'
    if: ${{ github.ref_name != 'master' && github.base_ref != 'master' }}
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout opencl-clang sources for action files
        uses: actions/checkout@v3

      # This step will fail when the branch naming scheme 'ocl-open-XXX' changes!
      - name: Parse LLVM version from branch name
        id: check-llvm-version
        run: |
          BRANCH="${{ github.base_name }}"         # on: pull_request, otherwise null
          BRANCH=${BRANCH:-${{ github.ref_name }}} # on: push
          LLVM_VERSION_LONG=$(echo $BRANCH | grep -oP '\d+') # Eg. 150 for LLVM 15
          LLVM_VERSION_SHORT=${LLVM_VERSION_LONG::-1}        # Eg. 15  for LLVM 15
          echo "llvm_version=$LLVM_VERSION_SHORT" >> $GITHUB_OUTPUT

      - uses: ./.github/actions/build-opencl-clang
        with:
          ref_llvm: release/${{ steps.check-llvm-version.outputs.llvm_version }}.x
          ref_translator: llvm_release_${{ steps.check-llvm-version.outputs.llvm_version }}0
          ref_opencl-clang: ${{ github.ref }}
